# Generated by `python -m amzn_selling_partner.stubgen`; do not edit.
from __future__ import annotations
from typing import Any, Literal, overload
from amzn_selling_partner.compile.resources import AsyncResource, SyncResource
from amzn_selling_partner.models.listings_restrictions import v2021_08_01 as models
from amzn_selling_partner.runtime import NOT_GIVEN, NotGiven, Pagination, RequestOptions

class ListingsRestrictions(SyncResource):
    models: Any
    @overload
    def get_listings_restrictions(self, *, asin: str, seller_id: str, marketplace_ids: list[str], condition_type: Literal['new_new', 'new_open_box', 'new_oem', 'refurbished_refurbished', 'used_like_new', 'used_very_good', 'used_good', 'used_acceptable', 'collectible_like_new', 'collectible_very_good', 'collectible_good', 'collectible_acceptable', 'club_club'] | NotGiven = NOT_GIVEN, reason_locale: str | NotGiven = NOT_GIVEN, product_type: str | NotGiven = NOT_GIVEN, raw: Literal[False] = ..., paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.RestrictionList: ...
    @overload
    def get_listings_restrictions(self, *, asin: str, seller_id: str, marketplace_ids: list[str], condition_type: Literal['new_new', 'new_open_box', 'new_oem', 'refurbished_refurbished', 'used_like_new', 'used_very_good', 'used_good', 'used_acceptable', 'collectible_like_new', 'collectible_very_good', 'collectible_good', 'collectible_acceptable', 'club_club'] | NotGiven = NOT_GIVEN, reason_locale: str | NotGiven = NOT_GIVEN, product_type: str | NotGiven = NOT_GIVEN, raw: Literal[True], paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.RestrictionListDict: ...
    def get_listings_restrictions(self, *, asin: str, seller_id: str, marketplace_ids: list[str], condition_type: Literal['new_new', 'new_open_box', 'new_oem', 'refurbished_refurbished', 'used_like_new', 'used_very_good', 'used_good', 'used_acceptable', 'collectible_like_new', 'collectible_very_good', 'collectible_good', 'collectible_acceptable', 'club_club'] | NotGiven = NOT_GIVEN, reason_locale: str | NotGiven = NOT_GIVEN, product_type: str | NotGiven = NOT_GIVEN, raw: bool = False, paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.RestrictionList:
        """Returns listing restrictions for an item in the Amazon Catalog. """

class AsyncListingsRestrictions(AsyncResource):
    models: Any
    @overload
    async def get_listings_restrictions(self, *, asin: str, seller_id: str, marketplace_ids: list[str], condition_type: Literal['new_new', 'new_open_box', 'new_oem', 'refurbished_refurbished', 'used_like_new', 'used_very_good', 'used_good', 'used_acceptable', 'collectible_like_new', 'collectible_very_good', 'collectible_good', 'collectible_acceptable', 'club_club'] | NotGiven = NOT_GIVEN, reason_locale: str | NotGiven = NOT_GIVEN, product_type: str | NotGiven = NOT_GIVEN, raw: Literal[False] = ..., paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.RestrictionList: ...
    @overload
    async def get_listings_restrictions(self, *, asin: str, seller_id: str, marketplace_ids: list[str], condition_type: Literal['new_new', 'new_open_box', 'new_oem', 'refurbished_refurbished', 'used_like_new', 'used_very_good', 'used_good', 'used_acceptable', 'collectible_like_new', 'collectible_very_good', 'collectible_good', 'collectible_acceptable', 'club_club'] | NotGiven = NOT_GIVEN, reason_locale: str | NotGiven = NOT_GIVEN, product_type: str | NotGiven = NOT_GIVEN, raw: Literal[True], paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.RestrictionListDict: ...
    async def get_listings_restrictions(self, *, asin: str, seller_id: str, marketplace_ids: list[str], condition_type: Literal['new_new', 'new_open_box', 'new_oem', 'refurbished_refurbished', 'used_like_new', 'used_very_good', 'used_good', 'used_acceptable', 'collectible_like_new', 'collectible_very_good', 'collectible_good', 'collectible_acceptable', 'club_club'] | NotGiven = NOT_GIVEN, reason_locale: str | NotGiven = NOT_GIVEN, product_type: str | NotGiven = NOT_GIVEN, raw: bool = False, paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.RestrictionList:
        """Returns listing restrictions for an item in the Amazon Catalog. """
