"""Operations of fba_inventory v1 (Selling Partner API for FBA Inventory).

Generated by codegen/ (oagen) from the pinned spec; do not edit by hand.
"""

from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, Literal

from amzn_selling_partner.models.fba_inventory import v1 as models
from amzn_selling_partner.runtime._op import Body, Op, header, json_decoder, path, query
from amzn_selling_partner.runtime._pagination import AsyncPage, Pagination, SyncPage
from amzn_selling_partner.runtime._resources import AsyncResource, SyncResource
from amzn_selling_partner.runtime._throttle import RateLimit
from amzn_selling_partner.runtime._types import NOT_GIVEN, NotGiven, RequestOptions

_op_get_inventory_summaries_d1 = json_decoder(lambda: models.GetInventorySummariesResponse)
_op_get_inventory_summaries = Op(
    key="fba_inventory.v1.getInventorySummaries",
    name="get_inventory_summaries",
    operation_id="getInventorySummaries",
    api="fba_inventory",
    version="v1",
    method="GET",
    path="/fba/inventory/v1/summaries",
    url_template="/fba/inventory/v1/summaries",
    path_params=(),
    query_params=(
        query("details", "details"),
        query("granularity_type", "granularityType", required=True),
        query("granularity_id", "granularityId", required=True),
        query("start_date_time", "startDateTime"),
        query("seller_skus", "sellerSkus", kind="array", explode=False),
        query("seller_sku", "sellerSku"),
        query("next_token", "nextToken"),
        query("marketplace_ids", "marketplaceIds", required=True, kind="array", explode=False),
    ),
    header_params=(),
    default_decoder=_op_get_inventory_summaries_d1,
    error_decoders={
        400: _op_get_inventory_summaries_d1,
        403: _op_get_inventory_summaries_d1,
        404: _op_get_inventory_summaries_d1,
        429: _op_get_inventory_summaries_d1,
        500: _op_get_inventory_summaries_d1,
        503: _op_get_inventory_summaries_d1,
    },
    default_error=_op_get_inventory_summaries_d1,
    rate_limit=RateLimit(rate=2, burst=2),
    pagination=Pagination(
        items_path="payload.inventorySummaries",
        next_token_path="pagination.nextToken",
        next_token_param="nextToken",
        drop_params_on_next=True,
        source="plugin",
    ),
    doc="Returns a list of inventory summaries. The summaries returned depend on the presence or absence of the startDateTime, sellerSkus and sellerSku parameters:\n\n- All inventory summaries with available details are returned when the startDateTime, sellerSkus and sellerSku parameters are omitted.\n- When startDateTime is provided, the operation returns inventory summaries that have had changes after the date and time specified. The sellerSkus and sellerSku parameters are ignored. Important: To avoid errors, use both startDateTime and nextToken to get the next page of inventory summaries that have changed after the date and time specified.\n- When the sellerSkus parameter is provided, the operation returns inventory summaries for only the specified sellerSkus. The sellerSku parameter is ignored.\n- When the sellerSku parameter is provided, the operation returns inventory summaries for only the specified sellerSku.\n\nNote: The parameters associated with this operation may contain special characters that must be encoded to successfully call the API. To avoid errors with SKUs when encoding URLs, refer to [URL Encoding](https://developer-docs.amazon.com/sp-api/docs/url-encoding).\n\nUsage Plan:\n\n| Rate (requests per second) | Burst |\n| ---- | ---- |\n| 2 | 2 |\n\nThe x-amzn-RateLimit-Limit response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits).\n\nGET /fba/inventory/v1/summaries",
)

_op_create_inventory_item_d1 = json_decoder(lambda: models.CreateInventoryItemResponse)
_op_create_inventory_item = Op(
    key="fba_inventory.v1.createInventoryItem",
    name="create_inventory_item",
    operation_id="createInventoryItem",
    api="fba_inventory",
    version="v1",
    method="POST",
    path="/fba/inventory/v1/items",
    url_template="/fba/inventory/v1/items",
    path_params=(),
    query_params=(),
    header_params=(),
    body=Body("json", "application/json", required=True),
    default_decoder=_op_create_inventory_item_d1,
    error_decoders={
        400: _op_create_inventory_item_d1,
        403: _op_create_inventory_item_d1,
        404: _op_create_inventory_item_d1,
        429: _op_create_inventory_item_d1,
        500: _op_create_inventory_item_d1,
        503: _op_create_inventory_item_d1,
    },
    default_error=_op_create_inventory_item_d1,
    doc="Requests that Amazon create product-details in the Sandbox Inventory in the sandbox environment. This is a sandbox-only operation and must be directed to a sandbox endpoint. Refer to [Selling Partner API sandbox](https://developer-docs.amazon.com/sp-api/docs/the-selling-partner-api-sandbox) for more information.\n\nPOST /fba/inventory/v1/items",
)

_op_delete_inventory_item_d1 = json_decoder(lambda: models.DeleteInventoryItemResponse)
_op_delete_inventory_item = Op(
    key="fba_inventory.v1.deleteInventoryItem",
    name="delete_inventory_item",
    operation_id="deleteInventoryItem",
    api="fba_inventory",
    version="v1",
    method="DELETE",
    path="/fba/inventory/v1/items/{sellerSku}",
    url_template="/fba/inventory/v1/items/{}",
    path_params=(path("seller_sku", "sellerSku"),),
    query_params=(query("marketplace_id", "marketplaceId", required=True),),
    header_params=(),
    default_decoder=_op_delete_inventory_item_d1,
    error_decoders={
        400: _op_delete_inventory_item_d1,
        403: _op_delete_inventory_item_d1,
        404: _op_delete_inventory_item_d1,
        429: _op_delete_inventory_item_d1,
        500: _op_delete_inventory_item_d1,
        503: _op_delete_inventory_item_d1,
    },
    default_error=_op_delete_inventory_item_d1,
    doc="Requests that Amazon Deletes an item from the Sandbox Inventory in the sandbox environment. This is a sandbox-only operation and must be directed to a sandbox endpoint. Refer to [Selling Partner API sandbox](https://developer-docs.amazon.com/sp-api/docs/the-selling-partner-api-sandbox) for more information.\n\nDELETE /fba/inventory/v1/items/{sellerSku}",
)

_op_add_inventory_d1 = json_decoder(lambda: models.AddInventoryResponse)
_op_add_inventory = Op(
    key="fba_inventory.v1.addInventory",
    name="add_inventory",
    operation_id="addInventory",
    api="fba_inventory",
    version="v1",
    method="POST",
    path="/fba/inventory/v1/items/inventory",
    url_template="/fba/inventory/v1/items/inventory",
    path_params=(),
    query_params=(),
    header_params=(header("x_amzn_idempotency_token", "x-amzn-idempotency-token", required=True),),
    body=Body("json", "application/json", required=True),
    default_decoder=_op_add_inventory_d1,
    error_decoders={
        400: _op_add_inventory_d1,
        403: _op_add_inventory_d1,
        404: _op_add_inventory_d1,
        429: _op_add_inventory_d1,
        500: _op_add_inventory_d1,
        503: _op_add_inventory_d1,
    },
    default_error=_op_add_inventory_d1,
    doc="Requests that Amazon add items to the Sandbox Inventory with desired amount of quantity in the sandbox environment. This is a sandbox-only operation and must be directed to a sandbox endpoint. Refer to [Selling Partner API sandbox](https://developer-docs.amazon.com/sp-api/docs/the-selling-partner-api-sandbox) for more information.\n\nPOST /fba/inventory/v1/items/inventory",
)


class FbaInventoryV1(SyncResource):
    """Sync resource for fba_inventory v1."""

    __slots__ = ()
    _resource_name = "fba_inventory.v1"
    models = models
    _ops = {
        "get_inventory_summaries": _op_get_inventory_summaries,
        "create_inventory_item": _op_create_inventory_item,
        "delete_inventory_item": _op_delete_inventory_item,
        "add_inventory": _op_add_inventory,
    }

    def get_inventory_summaries(
        self,
        *,
        granularity_type: Literal["Marketplace"],
        granularity_id: str,
        marketplace_ids: list[str],
        details: bool | NotGiven = NOT_GIVEN,
        start_date_time: datetime.datetime | NotGiven = NOT_GIVEN,
        seller_skus: list[str] | NotGiven = NOT_GIVEN,
        seller_sku: str | NotGiven = NOT_GIVEN,
        next_token: str | NotGiven = NOT_GIVEN,
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> SyncPage[models.InventorySummary]:
        """Returns a list of inventory summaries. The summaries returned depend on the presence or absence of the startDateTime, sellerSkus and sellerSku parameters:

        - All inventory summaries with available details are returned when the startDateTime, sellerSkus and sellerSku parameters are omitted.
        - When startDateTime is provided, the operation returns inventory summaries that have had changes after the date and time specified. The sellerSkus and sellerSku parameters are ignored. Important: To avoid errors, use both startDateTime and nextToken to get the next page of inventory summaries that have changed after the date and time specified.
        - When the sellerSkus parameter is provided, the operation returns inventory summaries for only the specified sellerSkus. The sellerSku parameter is ignored.
        - When the sellerSku parameter is provided, the operation returns inventory summaries for only the specified sellerSku.

        Note: The parameters associated with this operation may contain special characters that must be encoded to successfully call the API. To avoid errors with SKUs when encoding URLs, refer to [URL Encoding](https://developer-docs.amazon.com/sp-api/docs/url-encoding).

        Usage Plan:

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 2 | 2 |

        The x-amzn-RateLimit-Limit response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits).

        GET /fba/inventory/v1/summaries
        """
        return self._client.call(
            _op_get_inventory_summaries,
            {
                "details": details,
                "granularity_type": granularity_type,
                "granularity_id": granularity_id,
                "start_date_time": start_date_time,
                "seller_skus": seller_skus,
                "seller_sku": seller_sku,
                "next_token": next_token,
                "marketplace_ids": marketplace_ids,
            },
            raw,
            paginate,
            request_options,
        )

    def create_inventory_item(
        self,
        *,
        body: models.CreateInventoryItemRequest | Mapping[str, Any],
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.CreateInventoryItemResponse:
        """Requests that Amazon create product-details in the Sandbox Inventory in the sandbox environment. This is a sandbox-only operation and must be directed to a sandbox endpoint. Refer to [Selling Partner API sandbox](https://developer-docs.amazon.com/sp-api/docs/the-selling-partner-api-sandbox) for more information.

        POST /fba/inventory/v1/items
        """
        return self._client.call(_op_create_inventory_item, {"body": body}, raw, paginate, request_options)

    def delete_inventory_item(
        self,
        *,
        seller_sku: str,
        marketplace_id: str,
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.DeleteInventoryItemResponse:
        """Requests that Amazon Deletes an item from the Sandbox Inventory in the sandbox environment. This is a sandbox-only operation and must be directed to a sandbox endpoint. Refer to [Selling Partner API sandbox](https://developer-docs.amazon.com/sp-api/docs/the-selling-partner-api-sandbox) for more information.

        DELETE /fba/inventory/v1/items/{sellerSku}
        """
        return self._client.call(
            _op_delete_inventory_item, {"seller_sku": seller_sku, "marketplace_id": marketplace_id}, raw, paginate, request_options
        )

    def add_inventory(
        self,
        *,
        x_amzn_idempotency_token: str,
        body: models.AddInventoryRequest | Mapping[str, Any],
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.AddInventoryResponse:
        """Requests that Amazon add items to the Sandbox Inventory with desired amount of quantity in the sandbox environment. This is a sandbox-only operation and must be directed to a sandbox endpoint. Refer to [Selling Partner API sandbox](https://developer-docs.amazon.com/sp-api/docs/the-selling-partner-api-sandbox) for more information.

        POST /fba/inventory/v1/items/inventory
        """
        return self._client.call(
            _op_add_inventory, {"x_amzn_idempotency_token": x_amzn_idempotency_token, "body": body}, raw, paginate, request_options
        )


class AsyncFbaInventoryV1(AsyncResource):
    """Async resource for fba_inventory v1."""

    __slots__ = ()
    _resource_name = "fba_inventory.v1"
    models = models
    _ops = {
        "get_inventory_summaries": _op_get_inventory_summaries,
        "create_inventory_item": _op_create_inventory_item,
        "delete_inventory_item": _op_delete_inventory_item,
        "add_inventory": _op_add_inventory,
    }

    async def get_inventory_summaries(
        self,
        *,
        granularity_type: Literal["Marketplace"],
        granularity_id: str,
        marketplace_ids: list[str],
        details: bool | NotGiven = NOT_GIVEN,
        start_date_time: datetime.datetime | NotGiven = NOT_GIVEN,
        seller_skus: list[str] | NotGiven = NOT_GIVEN,
        seller_sku: str | NotGiven = NOT_GIVEN,
        next_token: str | NotGiven = NOT_GIVEN,
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> AsyncPage[models.InventorySummary]:
        """Returns a list of inventory summaries. The summaries returned depend on the presence or absence of the startDateTime, sellerSkus and sellerSku parameters:

        - All inventory summaries with available details are returned when the startDateTime, sellerSkus and sellerSku parameters are omitted.
        - When startDateTime is provided, the operation returns inventory summaries that have had changes after the date and time specified. The sellerSkus and sellerSku parameters are ignored. Important: To avoid errors, use both startDateTime and nextToken to get the next page of inventory summaries that have changed after the date and time specified.
        - When the sellerSkus parameter is provided, the operation returns inventory summaries for only the specified sellerSkus. The sellerSku parameter is ignored.
        - When the sellerSku parameter is provided, the operation returns inventory summaries for only the specified sellerSku.

        Note: The parameters associated with this operation may contain special characters that must be encoded to successfully call the API. To avoid errors with SKUs when encoding URLs, refer to [URL Encoding](https://developer-docs.amazon.com/sp-api/docs/url-encoding).

        Usage Plan:

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 2 | 2 |

        The x-amzn-RateLimit-Limit response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits).

        GET /fba/inventory/v1/summaries
        """
        return await self._client.call(
            _op_get_inventory_summaries,
            {
                "details": details,
                "granularity_type": granularity_type,
                "granularity_id": granularity_id,
                "start_date_time": start_date_time,
                "seller_skus": seller_skus,
                "seller_sku": seller_sku,
                "next_token": next_token,
                "marketplace_ids": marketplace_ids,
            },
            raw,
            paginate,
            request_options,
        )

    async def create_inventory_item(
        self,
        *,
        body: models.CreateInventoryItemRequest | Mapping[str, Any],
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.CreateInventoryItemResponse:
        """Requests that Amazon create product-details in the Sandbox Inventory in the sandbox environment. This is a sandbox-only operation and must be directed to a sandbox endpoint. Refer to [Selling Partner API sandbox](https://developer-docs.amazon.com/sp-api/docs/the-selling-partner-api-sandbox) for more information.

        POST /fba/inventory/v1/items
        """
        return await self._client.call(_op_create_inventory_item, {"body": body}, raw, paginate, request_options)

    async def delete_inventory_item(
        self,
        *,
        seller_sku: str,
        marketplace_id: str,
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.DeleteInventoryItemResponse:
        """Requests that Amazon Deletes an item from the Sandbox Inventory in the sandbox environment. This is a sandbox-only operation and must be directed to a sandbox endpoint. Refer to [Selling Partner API sandbox](https://developer-docs.amazon.com/sp-api/docs/the-selling-partner-api-sandbox) for more information.

        DELETE /fba/inventory/v1/items/{sellerSku}
        """
        return await self._client.call(
            _op_delete_inventory_item, {"seller_sku": seller_sku, "marketplace_id": marketplace_id}, raw, paginate, request_options
        )

    async def add_inventory(
        self,
        *,
        x_amzn_idempotency_token: str,
        body: models.AddInventoryRequest | Mapping[str, Any],
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.AddInventoryResponse:
        """Requests that Amazon add items to the Sandbox Inventory with desired amount of quantity in the sandbox environment. This is a sandbox-only operation and must be directed to a sandbox endpoint. Refer to [Selling Partner API sandbox](https://developer-docs.amazon.com/sp-api/docs/the-selling-partner-api-sandbox) for more information.

        POST /fba/inventory/v1/items/inventory
        """
        return await self._client.call(
            _op_add_inventory, {"x_amzn_idempotency_token": x_amzn_idempotency_token, "body": body}, raw, paginate, request_options
        )


__all__ = ["AsyncFbaInventoryV1", "FbaInventoryV1"]
