"""Operations of app_integrations v2024_04_01 (The Selling Partner API for third party application integrations.).

Generated by codegen/ (oagen) from the pinned spec; do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from amzn_selling_partner.models.app_integrations import v2024_04_01 as models
from amzn_selling_partner.runtime._op import NONE, Body, Op, json_decoder, path
from amzn_selling_partner.runtime._pagination import Pagination
from amzn_selling_partner.runtime._resources import AsyncResource, SyncResource
from amzn_selling_partner.runtime._throttle import RateLimit
from amzn_selling_partner.runtime._types import NOT_GIVEN, NotGiven, RequestOptions

_op_create_notification_d1 = json_decoder(lambda: models.CreateNotificationResponse)
_op_create_notification_d2 = json_decoder(lambda: models.ErrorList)
_op_create_notification = Op(
    key="app_integrations.v2024_04_01.createNotification",
    name="create_notification",
    operation_id="createNotification",
    api="app_integrations",
    version="v2024_04_01",
    method="POST",
    path="/appIntegrations/2024-04-01/notifications",
    url_template="/appIntegrations/2024-04-01/notifications",
    path_params=(),
    query_params=(),
    header_params=(),
    body=Body("json", "application/json", required=True),
    default_decoder=_op_create_notification_d1,
    error_decoders={
        400: _op_create_notification_d2,
        401: _op_create_notification_d2,
        403: _op_create_notification_d2,
        404: _op_create_notification_d2,
        413: _op_create_notification_d2,
        415: _op_create_notification_d2,
        429: _op_create_notification_d2,
        500: _op_create_notification_d2,
        503: _op_create_notification_d2,
    },
    default_error=_op_create_notification_d2,
    rate_limit=RateLimit(rate=1, burst=5),
    doc="Create a notification for sellers in Seller Central.\n\n**Usage Plan:**\n\n| Rate (requests per second) | Burst |\n| ---- | ---- |\n| 1 | 5 |\n\nThe `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Sellers whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).\n\nPOST /appIntegrations/2024-04-01/notifications",
)

_op_delete_notifications_d1 = json_decoder(lambda: models.ErrorList)
_op_delete_notifications = Op(
    key="app_integrations.v2024_04_01.deleteNotifications",
    name="delete_notifications",
    operation_id="deleteNotifications",
    api="app_integrations",
    version="v2024_04_01",
    method="POST",
    path="/appIntegrations/2024-04-01/notifications/deletion",
    url_template="/appIntegrations/2024-04-01/notifications/deletion",
    path_params=(),
    query_params=(),
    header_params=(),
    body=Body("json", "application/json", required=True),
    default_decoder=NONE,
    error_decoders={
        400: _op_delete_notifications_d1,
        403: _op_delete_notifications_d1,
        404: _op_delete_notifications_d1,
        413: _op_delete_notifications_d1,
        415: _op_delete_notifications_d1,
        429: _op_delete_notifications_d1,
        500: _op_delete_notifications_d1,
        503: _op_delete_notifications_d1,
    },
    default_error=_op_delete_notifications_d1,
    rate_limit=RateLimit(rate=1, burst=5),
    doc="Remove your application's notifications from the Appstore notifications dashboard.\n\n**Usage Plan:**\n\n| Rate (requests per second) | Burst |\n| ---- | ---- |\n| 1 | 5 |\n\nThe `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Sellers whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).\n\nPOST /appIntegrations/2024-04-01/notifications/deletion",
)

_op_record_action_feedback_d1 = json_decoder(lambda: models.ErrorList)
_op_record_action_feedback = Op(
    key="app_integrations.v2024_04_01.recordActionFeedback",
    name="record_action_feedback",
    operation_id="recordActionFeedback",
    api="app_integrations",
    version="v2024_04_01",
    method="POST",
    path="/appIntegrations/2024-04-01/notifications/{notificationId}/feedback",
    url_template="/appIntegrations/2024-04-01/notifications/{}/feedback",
    path_params=(path("notification_id", "notificationId"),),
    query_params=(),
    header_params=(),
    body=Body("json", "application/json", required=True),
    default_decoder=NONE,
    error_decoders={
        400: _op_record_action_feedback_d1,
        401: _op_record_action_feedback_d1,
        403: _op_record_action_feedback_d1,
        404: _op_record_action_feedback_d1,
        413: _op_record_action_feedback_d1,
        415: _op_record_action_feedback_d1,
        429: _op_record_action_feedback_d1,
        500: _op_record_action_feedback_d1,
        503: _op_record_action_feedback_d1,
    },
    default_error=_op_record_action_feedback_d1,
    rate_limit=RateLimit(rate=1, burst=5),
    doc="Records the seller's response to a notification.\n\n**Usage Plan:**\n\n| Rate (requests per second) | Burst |\n| ---- | ---- |\n| 1 | 5 |\n\nThe `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Sellers whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).\n\nPOST /appIntegrations/2024-04-01/notifications/{notificationId}/feedback",
)


class AppIntegrationsV20240401(SyncResource):
    """Sync resource for app_integrations v2024_04_01."""

    __slots__ = ()
    _resource_name = "app_integrations.v2024_04_01"
    models = models
    _ops = {
        "create_notification": _op_create_notification,
        "delete_notifications": _op_delete_notifications,
        "record_action_feedback": _op_record_action_feedback,
    }

    def create_notification(
        self,
        *,
        body: models.CreateNotificationRequest | Mapping[str, Any],
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.CreateNotificationResponse:
        """Create a notification for sellers in Seller Central.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Sellers whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /appIntegrations/2024-04-01/notifications
        """
        return self._client.call(_op_create_notification, {"body": body}, raw, paginate, request_options)

    def delete_notifications(
        self,
        *,
        body: models.DeleteNotificationsRequest | Mapping[str, Any],
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> None:
        """Remove your application's notifications from the Appstore notifications dashboard.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Sellers whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /appIntegrations/2024-04-01/notifications/deletion
        """
        return self._client.call(_op_delete_notifications, {"body": body}, raw, paginate, request_options)

    def record_action_feedback(
        self,
        *,
        notification_id: str,
        body: models.RecordActionFeedbackRequest | Mapping[str, Any],
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> None:
        """Records the seller's response to a notification.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Sellers whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /appIntegrations/2024-04-01/notifications/{notificationId}/feedback
        """
        return self._client.call(
            _op_record_action_feedback, {"notification_id": notification_id, "body": body}, raw, paginate, request_options
        )


class AsyncAppIntegrationsV20240401(AsyncResource):
    """Async resource for app_integrations v2024_04_01."""

    __slots__ = ()
    _resource_name = "app_integrations.v2024_04_01"
    models = models
    _ops = {
        "create_notification": _op_create_notification,
        "delete_notifications": _op_delete_notifications,
        "record_action_feedback": _op_record_action_feedback,
    }

    async def create_notification(
        self,
        *,
        body: models.CreateNotificationRequest | Mapping[str, Any],
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.CreateNotificationResponse:
        """Create a notification for sellers in Seller Central.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Sellers whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /appIntegrations/2024-04-01/notifications
        """
        return await self._client.call(_op_create_notification, {"body": body}, raw, paginate, request_options)

    async def delete_notifications(
        self,
        *,
        body: models.DeleteNotificationsRequest | Mapping[str, Any],
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> None:
        """Remove your application's notifications from the Appstore notifications dashboard.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Sellers whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /appIntegrations/2024-04-01/notifications/deletion
        """
        return await self._client.call(_op_delete_notifications, {"body": body}, raw, paginate, request_options)

    async def record_action_feedback(
        self,
        *,
        notification_id: str,
        body: models.RecordActionFeedbackRequest | Mapping[str, Any],
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> None:
        """Records the seller's response to a notification.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Sellers whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /appIntegrations/2024-04-01/notifications/{notificationId}/feedback
        """
        return await self._client.call(
            _op_record_action_feedback, {"notification_id": notification_id, "body": body}, raw, paginate, request_options
        )


__all__ = ["AsyncAppIntegrationsV20240401", "AppIntegrationsV20240401"]
