# Auto-generated by oagen. Do not edit.

"""Models package ``notifications.ReportProcessingFinishedNotification``.

Auto-generated by oagen from the OpenAPI spec; do not edit by hand.
"""

from __future__ import annotations

from .enums import ReportProcessingFinishedNotificationPayloadReportProcessingFinishedNotificationProcessingStatus
from .models import (
    ReportProcessingFinishedNotification,
    ReportProcessingFinishedNotificationNotificationMetadata,
    ReportProcessingFinishedNotificationPayload,
    ReportProcessingFinishedNotificationPayloadReportProcessingFinishedNotification,
)

__all__ = [
    "ReportProcessingFinishedNotification",
    "ReportProcessingFinishedNotificationNotificationMetadata",
    "ReportProcessingFinishedNotificationPayload",
    "ReportProcessingFinishedNotificationPayloadReportProcessingFinishedNotification",
    "ReportProcessingFinishedNotificationPayloadReportProcessingFinishedNotificationProcessingStatus",
]
