[project]
name = "amzn-selling-partner"
version = "0.1.7"
description = "Amazon Selling Partner API for Python"
authors = [
  { name = "Danilo Britto", email = "dbritto.dev@gmail.com" },
]
classifiers = [
  "Intended Audience :: Information Technology",
  "Intended Audience :: System Administrators",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python",
  "Topic :: Internet",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development",
  "Typing :: Typed",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Internet :: WWW/HTTP",
  "Topic :: Security",
]
dependencies = [
  "requests==2.34.2", "requests_aws4auth==1.2.2", "boto3==1.43.86",
  "pydantic==1.10.13"
]
readme = "README.md"
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
  "ruff==0.16.5", "pytest==9.1.1", "coverage==7.10.6",
  "pytest-cov==7.1.0", "nox>=2024.4.15", "bandit==1.9.4", "safety==2.3.4",
  "responses==0.26.3", "ty==0.0.77"
]
lint = ["ruff==0.16.5"]
test = [
  "pytest==9.1.1", "coverage==7.10.6", "pytest-cov==7.1.0", "nox>=2024.4.15",
  "responses==0.26.3"
]
security-test = ["bandit==1.9.4", "safety==2.3.4", "setuptools<81"]

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""

[tool.ruff]
line-length = 99
target-version = "py310"
exclude = [
  "build", "configs", "*.egg-info", ".github", ".githooks", ".vscode", ".nox"
]

[tool.ruff.lint]
select = [
  # flake8-bugbear
  "B",
  # flake8-comprehensions and mccabe
  "C",
  # pycodestyle
  "E", "W",
  # pyflakes
  "F",
  # isort
  "I",
  # bandit
  "S",
  # flake8-quotes
  "Q",
  # pylint
  "PLE", "PLR", "PLW"
]
ignore = ["E501", "B904", "B008"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["S101", "S106"]

[tool.ruff.lint.pylint]
max-args = 10

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ty.rules]
deprecated = "ignore"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]

[tool.coverage.run]
branch = true
source = ["amzn_selling_partner"]
omit = ["amzn_selling_partner/client/auth.py"]

[tool.coverage.report]
fail_under = 90
