"""Models for definitions_product_types v2020_09_01 (Selling Partner API for Product Type Definitions).

Generated by codegen/ (oagen) from the pinned spec; do not edit by hand.
"""

from __future__ import annotations

from typing import Literal, TypeAlias

from pydantic import Field

from amzn_selling_partner.runtime._models import SpecModel

DefinitionsLocale: TypeAlias = Literal[
    "DEFAULT",
    "ar",
    "ar_AE",
    "de",
    "de_DE",
    "en",
    "en_AE",
    "en_AU",
    "en_CA",
    "en_GB",
    "en_IN",
    "en_SG",
    "en_US",
    "es",
    "es_ES",
    "es_MX",
    "es_US",
    "fr",
    "fr_CA",
    "fr_FR",
    "it",
    "it_IT",
    "ja",
    "ja_JP",
    "nl",
    "nl_NL",
    "pl",
    "pl_PL",
    "pt",
    "pt_BR",
    "pt_PT",
    "sv",
    "sv_SE",
    "tr",
    "tr_TR",
    "zh",
    "zh_CN",
    "zh_TW",
]
DefinitionsParentageLevel: TypeAlias = Literal["NONE", "CHILD", "PARENT"]
DefinitionsRequirements: TypeAlias = Literal["LISTING", "LISTING_PRODUCT_ONLY", "LISTING_OFFER_ONLY"]
DefinitionsRequirementsEnforced: TypeAlias = Literal["ENFORCED", "NOT_ENFORCED"]
ProductTypeDefinitionRequirements: TypeAlias = Literal["LISTING", "LISTING_PRODUCT_ONLY", "LISTING_OFFER_ONLY"]
ProductTypeDefinitionRequirementsEnforced: TypeAlias = Literal["ENFORCED", "NOT_ENFORCED"]


class Error(SpecModel):
    """Error response returned when the request is unsuccessful."""

    code: str
    message: str
    details: str | None = None


class ErrorList(SpecModel):
    """A list of error responses returned when a request is unsuccessful."""

    errors: list[Error]


class ProductType(SpecModel):
    """An Amazon product type with a definition available."""

    name: str
    display_name: str = Field(alias="displayName")
    marketplace_ids: list[str] = Field(alias="marketplaceIds")


class ProductTypeDefinition(SpecModel):
    """A product type definition represents the attributes and data requirements for a product type in the Amazon catalog. Product type definitions are used interchangeably between the Selling Partner API for Listings Items, Selling Partner API for Catalog Items, and JSON-based listings feeds in the Selling Partner API for Feeds."""

    meta_schema: SchemaLink | None = Field(default=None, alias="metaSchema")
    schema_: SchemaLink = Field(alias="schema")
    requirements: ProductTypeDefinitionRequirements
    requirements_enforced: ProductTypeDefinitionRequirementsEnforced = Field(alias="requirementsEnforced")
    property_groups: dict[str, PropertyGroup] = Field(alias="propertyGroups")
    locale: str
    marketplace_ids: list[str] = Field(alias="marketplaceIds")
    product_type: str = Field(alias="productType")
    display_name: str = Field(alias="displayName")
    product_type_version: ProductTypeVersion = Field(alias="productTypeVersion")


class ProductTypeList(SpecModel):
    """A list of Amazon product types with definitions available."""

    product_types: list[ProductType] = Field(alias="productTypes")
    product_type_version: str = Field(alias="productTypeVersion")


class ProductTypeVersion(SpecModel):
    """The version details for an Amazon product type."""

    version: str
    latest: bool
    release_candidate: bool | None = Field(default=None, alias="releaseCandidate")


class PropertyGroup(SpecModel):
    """A property group represents a logical grouping of schema properties that can be used for display or informational purposes."""

    title: str | None = None
    description: str | None = None
    property_names: list[str] | None = Field(default=None, alias="propertyNames")


class SchemaLink(SpecModel):
    """A link to metadata schema."""

    link: SchemaLinkLink
    checksum: str


class SchemaLinkLink(SpecModel):
    resource: str
    verb: Literal["GET"]


__all__ = [
    "DefinitionsLocale",
    "DefinitionsParentageLevel",
    "DefinitionsRequirements",
    "DefinitionsRequirementsEnforced",
    "Error",
    "ErrorList",
    "ProductType",
    "ProductTypeDefinition",
    "ProductTypeDefinitionRequirements",
    "ProductTypeDefinitionRequirementsEnforced",
    "ProductTypeList",
    "ProductTypeVersion",
    "PropertyGroup",
    "SchemaLink",
    "SchemaLinkLink",
]
