# Generated by `python -m amzn_selling_partner.stubgen`; do not edit.
from __future__ import annotations
import datetime
from typing import Any, TypedDict

from pydantic import BaseModel, Field

class BrowseNodeResponse(BaseModel):
    """The response for the `getItemBrowseNode` operation."""
    browse_node_id: str = Field(alias="browseNodeId")
    display_name: str = Field(alias="displayName")
    def __init__(self, **data: Any) -> None: ...

class DateRange(BaseModel):
    """A date range."""
    start_date: datetime.datetime = Field(alias="startDate")
    end_date: datetime.datetime = Field(alias="endDate")
    def __init__(self, **data: Any) -> None: ...

class ItemReviewTopicMetrics(BaseModel):
    """The item review topic metrics."""
    number_of_mentions: int | None = Field(default=None, alias="numberOfMentions")
    occurrence_percentage: float | None = Field(default=None, alias="occurrencePercentage")
    star_rating_impact: float | None = Field(default=None, alias="starRatingImpact")
    def __init__(self, **data: Any) -> None: ...

class BrowseNodeOccurrence(BaseModel):
    """The browse node review trend occurrence metrics."""
    all_products: float = Field(alias="allProducts")
    def __init__(self, **data: Any) -> None: ...

class BrowseNodeStarRatingImpact(BaseModel):
    """The effects of a topic on a browse node's star rating."""
    all_products: float = Field(alias="allProducts")
    def __init__(self, **data: Any) -> None: ...

class ItemReviewBrowseNodeMetrics(BaseModel):
    """The browse node review topic metrics."""
    occurrence_percentage: BrowseNodeOccurrence | None = Field(default=None, alias="occurrencePercentage")
    star_rating_impact: BrowseNodeStarRatingImpact | None = Field(default=None, alias="starRatingImpact")
    def __init__(self, **data: Any) -> None: ...

class ChildAsinMentionMetrics(BaseModel):
    """The child ASIN review topic mention metrics."""
    asin: str
    number_of_mentions: int = Field(alias="numberOfMentions")
    def __init__(self, **data: Any) -> None: ...

class ChildAsinMetrics(BaseModel):
    """The review topic metrics for other child ASINs that have the same parent ASIN. This value is `null` if there isn't any child ASIN metric data."""
    most_mentions: ChildAsinMentionMetrics | None = Field(default=None, alias="mostMentions")
    least_mentions: ChildAsinMentionMetrics | None = Field(default=None, alias="leastMentions")
    def __init__(self, **data: Any) -> None: ...

class ItemReviewSubtopicMetrics(BaseModel):
    """The item review subtopic metrics."""
    number_of_mentions: int = Field(alias="numberOfMentions")
    occurrence_percentage: float = Field(alias="occurrencePercentage")
    def __init__(self, **data: Any) -> None: ...

class ItemReviewSubtopic(BaseModel):
    """Details of the subtopic for an item review topic."""
    subtopic: str
    metrics: ItemReviewSubtopicMetrics
    review_snippets: list[str] | None = Field(default=None, alias="reviewSnippets")
    def __init__(self, **data: Any) -> None: ...

class ItemReviewTopic(BaseModel):
    """Details of item review topic."""
    topic: str
    asin_metrics: ItemReviewTopicMetrics = Field(alias="asinMetrics")
    parent_asin_metrics: ItemReviewTopicMetrics | None = Field(default=None, alias="parentAsinMetrics")
    browse_node_metrics: ItemReviewBrowseNodeMetrics | None = Field(default=None, alias="browseNodeMetrics")
    child_asin_metrics: ChildAsinMetrics | None = Field(default=None, alias="childAsinMetrics")
    review_snippets: list[str] | None = Field(default=None, alias="reviewSnippets")
    subtopics: list[ItemReviewSubtopic] | None = Field(default=None)
    def __init__(self, **data: Any) -> None: ...

class ItemReviewTopics(BaseModel):
    """The top 10 positive and negative item review topics."""
    positive_topics: list[ItemReviewTopic] | None = Field(default=None, alias="positiveTopics")
    negative_topics: list[ItemReviewTopic] | None = Field(default=None, alias="negativeTopics")
    def __init__(self, **data: Any) -> None: ...

class ItemReviewTopicsResponse(BaseModel):
    """The response for the `getItemReviewTopics` operation."""
    asin: str
    item_name: str = Field(alias="itemName")
    marketplace_id: str = Field(alias="marketplaceId")
    country_code: str = Field(alias="countryCode")
    date_range: DateRange = Field(alias="dateRange")
    topics: ItemReviewTopics
    def __init__(self, **data: Any) -> None: ...

class BrowseNodeReviewSubtopicMetrics(BaseModel):
    """The browse node review subtopic metrics."""
    occurrence_percentage: float = Field(alias="occurrencePercentage")
    def __init__(self, **data: Any) -> None: ...

class BrowseNodeAllOccurrence(BaseModel):
    """The browse node review occurrence metrics."""
    top_twenty_five_percent_products: float = Field(alias="topTwentyFivePercentProducts")
    all_products: float = Field(alias="allProducts")
    def __init__(self, **data: Any) -> None: ...

class BrowseNodeAllStarRatingImpact(BaseModel):
    """The effects of a topic on the star ratings in a browse node."""
    top_twenty_five_percent_products: float = Field(alias="topTwentyFivePercentProducts")
    all_products: float = Field(alias="allProducts")
    def __init__(self, **data: Any) -> None: ...

class BrowseNodeReviewTopicMetrics(BaseModel):
    """The browse node review topic metrics."""
    occurrence_percentage: BrowseNodeAllOccurrence | None = Field(default=None, alias="occurrencePercentage")
    star_rating_impact: BrowseNodeAllStarRatingImpact | None = Field(default=None, alias="starRatingImpact")
    def __init__(self, **data: Any) -> None: ...

class BrowseNodeSubtopic(BaseModel):
    """The browse node review subtopic."""
    subtopic: str
    metrics: BrowseNodeReviewSubtopicMetrics
    review_snippets: list[str] | None = Field(default=None, alias="reviewSnippets")
    def __init__(self, **data: Any) -> None: ...

class BrowseNodeReviewTopic(BaseModel):
    """The browse node review topic."""
    topic: str
    browse_node_metrics: BrowseNodeReviewTopicMetrics = Field(alias="browseNodeMetrics")
    review_snippets: list[str] | None = Field(default=None, alias="reviewSnippets")
    subtopics: list[BrowseNodeSubtopic] | None = Field(default=None)
    def __init__(self, **data: Any) -> None: ...

class BrowseNodeReviewTopics(BaseModel):
    """The 10 most positive and most negative review topics for all items in a browse node."""
    positive_topics: list[BrowseNodeReviewTopic] | None = Field(default=None, alias="positiveTopics")
    negative_topics: list[BrowseNodeReviewTopic] | None = Field(default=None, alias="negativeTopics")
    def __init__(self, **data: Any) -> None: ...

class BrowseNodeReviewTopicsResponse(BaseModel):
    """The response for the `getBrowseNodeReviewTopics` operation."""
    browse_node_id: str = Field(alias="browseNodeId")
    display_name: str = Field(alias="displayName")
    marketplace_id: str = Field(alias="marketplaceId")
    country_code: str = Field(alias="countryCode")
    date_range: DateRange = Field(alias="dateRange")
    topics: BrowseNodeReviewTopics
    def __init__(self, **data: Any) -> None: ...

class ReviewTrendMetrics(BaseModel):
    """The item review trend metrics."""
    occurrence_percentage: float = Field(alias="occurrencePercentage")
    def __init__(self, **data: Any) -> None: ...

class BrowseNodeTrendMetrics(BaseModel):
    """A single browse node review or return trend metric."""
    occurrence_percentage: BrowseNodeOccurrence = Field(alias="occurrencePercentage")
    def __init__(self, **data: Any) -> None: ...

class ItemReviewTrendPoint(BaseModel):
    """The review metrics for a certain month."""
    date_range: DateRange = Field(alias="dateRange")
    asin_metrics: ReviewTrendMetrics = Field(alias="asinMetrics")
    parent_asin_metrics: ReviewTrendMetrics | None = Field(default=None, alias="parentAsinMetrics")
    browse_node_metrics: BrowseNodeTrendMetrics | None = Field(default=None, alias="browseNodeMetrics")
    def __init__(self, **data: Any) -> None: ...

class ItemReviewTrend(BaseModel):
    """The trend of review topic metrics for the requested item."""
    topic: str
    trend_metrics: list[ItemReviewTrendPoint] = Field(alias="trendMetrics")
    def __init__(self, **data: Any) -> None: ...

class ItemReviewTrends(BaseModel):
    """The 10 most positive and most negative review topics for all items in a browse node."""
    positive_topics: list[ItemReviewTrend] | None = Field(default=None, alias="positiveTopics")
    negative_topics: list[ItemReviewTrend] | None = Field(default=None, alias="negativeTopics")
    def __init__(self, **data: Any) -> None: ...

class ItemReviewTrendsResponse(BaseModel):
    """The response for the `getItemReviewTrends` operation."""
    asin: str
    item_name: str = Field(alias="itemName")
    marketplace_id: str = Field(alias="marketplaceId")
    country_code: str = Field(alias="countryCode")
    date_range: DateRange = Field(alias="dateRange")
    review_trends: ItemReviewTrends = Field(alias="reviewTrends")
    def __init__(self, **data: Any) -> None: ...

class BrowseNodeReviewTrendMetrics(BaseModel):
    """The browse node review topic metrics."""
    occurrence_percentage: BrowseNodeAllOccurrence = Field(alias="occurrencePercentage")
    def __init__(self, **data: Any) -> None: ...

class BrowseNodeReviewTrendPoint(BaseModel):
    """The browse node's review metrics for a certain month."""
    date_range: DateRange = Field(alias="dateRange")
    browse_node_metrics: BrowseNodeReviewTrendMetrics = Field(alias="browseNodeMetrics")
    def __init__(self, **data: Any) -> None: ...

class BrowseNodeReviewTrend(BaseModel):
    """The trend of review topic metrics for all items in the requested browse node."""
    topic: str
    trend_metrics: list[BrowseNodeReviewTrendPoint] = Field(alias="trendMetrics")
    def __init__(self, **data: Any) -> None: ...

class BrowseNodeReviewTrends(BaseModel):
    """The 10 most positive and most negative review topics for all items in a browse node."""
    positive_topics: list[BrowseNodeReviewTrend] | None = Field(default=None, alias="positiveTopics")
    negative_topics: list[BrowseNodeReviewTrend] | None = Field(default=None, alias="negativeTopics")
    def __init__(self, **data: Any) -> None: ...

class BrowseNodeReviewTrendsResponse(BaseModel):
    """The response for the `getBrowseNodeReviewTrends` operation."""
    browse_node_id: str = Field(alias="browseNodeId")
    display_name: str = Field(alias="displayName")
    marketplace_id: str = Field(alias="marketplaceId")
    country_code: str = Field(alias="countryCode")
    date_range: DateRange = Field(alias="dateRange")
    review_trends: BrowseNodeReviewTrends = Field(alias="reviewTrends")
    def __init__(self, **data: Any) -> None: ...

class BrowseNodeReturnTopics(BaseModel):
    """Topics from returns for all items in a browse node."""
    topic: str
    browse_node_metrics: BrowseNodeTrendMetrics = Field(alias="browseNodeMetrics")
    def __init__(self, **data: Any) -> None: ...

class BrowseNodeReturnTopicsResponse(BaseModel):
    """The response for the `getBrowseNodeReturnTopics` operation."""
    browse_node_id: str = Field(alias="browseNodeId")
    display_name: str = Field(alias="displayName")
    marketplace_id: str = Field(alias="marketplaceId")
    country_code: str = Field(alias="countryCode")
    date_range: DateRange = Field(alias="dateRange")
    topics: list[BrowseNodeReturnTopics]
    def __init__(self, **data: Any) -> None: ...

class BrowseNodeReturnTrendPoint(BaseModel):
    """The return metrics for a certain month."""
    date_range: DateRange = Field(alias="dateRange")
    browse_node_metrics: BrowseNodeTrendMetrics = Field(alias="browseNodeMetrics")
    def __init__(self, **data: Any) -> None: ...

class BrowseNodeReturnTrend(BaseModel):
    """The trend of return topic metrics for all items in the requested browse node."""
    topic: str
    trend_metrics: list[BrowseNodeReturnTrendPoint] = Field(alias="trendMetrics")
    def __init__(self, **data: Any) -> None: ...

class BrowseNodeReturnTrendsResponse(BaseModel):
    """The response for the `getBrowseNodeReturnTrends` operation."""
    browse_node_id: str = Field(alias="browseNodeId")
    display_name: str = Field(alias="displayName")
    marketplace_id: str = Field(alias="marketplaceId")
    country_code: str = Field(alias="countryCode")
    date_range: DateRange = Field(alias="dateRange")
    return_trends: list[BrowseNodeReturnTrend] = Field(alias="returnTrends")
    def __init__(self, **data: Any) -> None: ...

class Error(BaseModel):
    """Error response returned when the request is unsuccessful."""
    code: str
    message: str
    details: str | None = Field(default=None)
    def __init__(self, **data: Any) -> None: ...

class ErrorList(BaseModel):
    """A list of error responses returned when a request is unsuccessful."""
    errors: list[Error]
    def __init__(self, **data: Any) -> None: ...

# raw-mode shapes (``raw=True``)

class BrowseNodeResponseDict(TypedDict, total=False):
    browseNodeId: str
    displayName: str

class DateRangeDict(TypedDict, total=False):
    startDate: datetime.datetime
    endDate: datetime.datetime

class ItemReviewTopicMetricsDict(TypedDict, total=False):
    numberOfMentions: int
    occurrencePercentage: float
    starRatingImpact: float

class BrowseNodeOccurrenceDict(TypedDict, total=False):
    allProducts: float

class BrowseNodeStarRatingImpactDict(TypedDict, total=False):
    allProducts: float

class ItemReviewBrowseNodeMetricsDict(TypedDict, total=False):
    occurrencePercentage: BrowseNodeOccurrenceDict
    starRatingImpact: BrowseNodeStarRatingImpactDict

class ChildAsinMentionMetricsDict(TypedDict, total=False):
    asin: str
    numberOfMentions: int

class ChildAsinMetricsDict(TypedDict, total=False):
    mostMentions: ChildAsinMentionMetricsDict
    leastMentions: ChildAsinMentionMetricsDict

class ItemReviewSubtopicMetricsDict(TypedDict, total=False):
    numberOfMentions: int
    occurrencePercentage: float

class ItemReviewSubtopicDict(TypedDict, total=False):
    subtopic: str
    metrics: ItemReviewSubtopicMetricsDict
    reviewSnippets: list[str]

class ItemReviewTopicDict(TypedDict, total=False):
    topic: str
    asinMetrics: ItemReviewTopicMetricsDict
    parentAsinMetrics: ItemReviewTopicMetricsDict
    browseNodeMetrics: ItemReviewBrowseNodeMetricsDict
    childAsinMetrics: ChildAsinMetricsDict
    reviewSnippets: list[str]
    subtopics: list[ItemReviewSubtopicDict]

class ItemReviewTopicsDict(TypedDict, total=False):
    positiveTopics: list[ItemReviewTopicDict]
    negativeTopics: list[ItemReviewTopicDict]

class ItemReviewTopicsResponseDict(TypedDict, total=False):
    asin: str
    itemName: str
    marketplaceId: str
    countryCode: str
    dateRange: DateRangeDict
    topics: ItemReviewTopicsDict

class BrowseNodeReviewSubtopicMetricsDict(TypedDict, total=False):
    occurrencePercentage: float

class BrowseNodeAllOccurrenceDict(TypedDict, total=False):
    topTwentyFivePercentProducts: float
    allProducts: float

class BrowseNodeAllStarRatingImpactDict(TypedDict, total=False):
    topTwentyFivePercentProducts: float
    allProducts: float

class BrowseNodeReviewTopicMetricsDict(TypedDict, total=False):
    occurrencePercentage: BrowseNodeAllOccurrenceDict
    starRatingImpact: BrowseNodeAllStarRatingImpactDict

class BrowseNodeSubtopicDict(TypedDict, total=False):
    subtopic: str
    metrics: BrowseNodeReviewSubtopicMetricsDict
    reviewSnippets: list[str]

class BrowseNodeReviewTopicDict(TypedDict, total=False):
    topic: str
    browseNodeMetrics: BrowseNodeReviewTopicMetricsDict
    reviewSnippets: list[str]
    subtopics: list[BrowseNodeSubtopicDict]

class BrowseNodeReviewTopicsDict(TypedDict, total=False):
    positiveTopics: list[BrowseNodeReviewTopicDict]
    negativeTopics: list[BrowseNodeReviewTopicDict]

class BrowseNodeReviewTopicsResponseDict(TypedDict, total=False):
    browseNodeId: str
    displayName: str
    marketplaceId: str
    countryCode: str
    dateRange: DateRangeDict
    topics: BrowseNodeReviewTopicsDict

class ReviewTrendMetricsDict(TypedDict, total=False):
    occurrencePercentage: float

class BrowseNodeTrendMetricsDict(TypedDict, total=False):
    occurrencePercentage: BrowseNodeOccurrenceDict

class ItemReviewTrendPointDict(TypedDict, total=False):
    dateRange: DateRangeDict
    asinMetrics: ReviewTrendMetricsDict
    parentAsinMetrics: ReviewTrendMetricsDict
    browseNodeMetrics: BrowseNodeTrendMetricsDict

class ItemReviewTrendDict(TypedDict, total=False):
    topic: str
    trendMetrics: list[ItemReviewTrendPointDict]

class ItemReviewTrendsDict(TypedDict, total=False):
    positiveTopics: list[ItemReviewTrendDict]
    negativeTopics: list[ItemReviewTrendDict]

class ItemReviewTrendsResponseDict(TypedDict, total=False):
    asin: str
    itemName: str
    marketplaceId: str
    countryCode: str
    dateRange: DateRangeDict
    reviewTrends: ItemReviewTrendsDict

class BrowseNodeReviewTrendMetricsDict(TypedDict, total=False):
    occurrencePercentage: BrowseNodeAllOccurrenceDict

class BrowseNodeReviewTrendPointDict(TypedDict, total=False):
    dateRange: DateRangeDict
    browseNodeMetrics: BrowseNodeReviewTrendMetricsDict

class BrowseNodeReviewTrendDict(TypedDict, total=False):
    topic: str
    trendMetrics: list[BrowseNodeReviewTrendPointDict]

class BrowseNodeReviewTrendsDict(TypedDict, total=False):
    positiveTopics: list[BrowseNodeReviewTrendDict]
    negativeTopics: list[BrowseNodeReviewTrendDict]

class BrowseNodeReviewTrendsResponseDict(TypedDict, total=False):
    browseNodeId: str
    displayName: str
    marketplaceId: str
    countryCode: str
    dateRange: DateRangeDict
    reviewTrends: BrowseNodeReviewTrendsDict

class BrowseNodeReturnTopicsDict(TypedDict, total=False):
    topic: str
    browseNodeMetrics: BrowseNodeTrendMetricsDict

class BrowseNodeReturnTopicsResponseDict(TypedDict, total=False):
    browseNodeId: str
    displayName: str
    marketplaceId: str
    countryCode: str
    dateRange: DateRangeDict
    topics: list[BrowseNodeReturnTopicsDict]

class BrowseNodeReturnTrendPointDict(TypedDict, total=False):
    dateRange: DateRangeDict
    browseNodeMetrics: BrowseNodeTrendMetricsDict

class BrowseNodeReturnTrendDict(TypedDict, total=False):
    topic: str
    trendMetrics: list[BrowseNodeReturnTrendPointDict]

class BrowseNodeReturnTrendsResponseDict(TypedDict, total=False):
    browseNodeId: str
    displayName: str
    marketplaceId: str
    countryCode: str
    dateRange: DateRangeDict
    returnTrends: list[BrowseNodeReturnTrendDict]

class ErrorDict(TypedDict, total=False):
    code: str
    message: str
    details: str

class ErrorListDict(TypedDict, total=False):
    errors: list[ErrorDict]
