"""Models for vendor_orders v1 (Selling Partner API for Retail Procurement Orders).

Generated by codegen/ (oagen) from the pinned spec; do not edit by hand.
"""

from __future__ import annotations

import datetime
from typing import Literal, TypeAlias

from pydantic import Field

from amzn_selling_partner.runtime._models import SpecModel

ImportDetailsInternationalCommercialTerms: TypeAlias = Literal[
    "ExWorks",
    "FreeCarrier",
    "FreeOnBoard",
    "FreeAlongSideShip",
    "CarriagePaidTo",
    "CostAndFreight",
    "CarriageAndInsurancePaidTo",
    "CostInsuranceAndFreight",
    "DeliveredAtTerminal",
    "DeliveredAtPlace",
    "DeliverDutyPaid",
]
ImportDetailsMethodOfPayment: TypeAlias = Literal[
    "PaidByBuyer", "CollectOnDelivery", "DefinedByBuyerAndSeller", "FOBPortOfCall", "PrepaidBySeller", "PaidBySeller"
]
ItemQuantityUnitOfMeasure: TypeAlias = Literal["Cases", "Eaches"]
MoneyUnitOfMeasure: TypeAlias = Literal["POUNDS", "OUNCES", "GRAMS", "KILOGRAMS"]
OrderDetailsPaymentMethod: TypeAlias = Literal["Invoice", "Consignment", "CreditCard", "Prepaid"]
OrderDetailsPurchaseOrderType: TypeAlias = Literal["RegularOrder", "ConsignedOrder", "NewProductIntroduction", "RushOrder"]
OrderItemAcknowledgementAcknowledgementCode: TypeAlias = Literal["Accepted", "Backordered", "Rejected"]
OrderItemAcknowledgementRejectionReason: TypeAlias = Literal["TemporarilyUnavailable", "InvalidProductIdentifier", "ObsoleteProduct"]
OrderItemStatusAcknowledgementStatusConfirmationStatus: TypeAlias = Literal["ACCEPTED", "PARTIALLY_ACCEPTED", "REJECTED", "UNCONFIRMED"]
OrderItemStatusReceivingStatusReceiveStatus: TypeAlias = Literal["NOT_RECEIVED", "PARTIALLY_RECEIVED", "RECEIVED"]
OrderPurchaseOrderState: TypeAlias = Literal["New", "Acknowledged", "Closed"]
OrderStatusPurchaseOrderStatus: TypeAlias = Literal["OPEN", "CLOSED"]
TaxRegistrationDetailsTaxRegistrationType: TypeAlias = Literal["VAT", "GST"]
VendorOrdersItemConfirmationStatus: TypeAlias = Literal["ACCEPTED", "PARTIALLY_ACCEPTED", "REJECTED", "UNCONFIRMED"]
VendorOrdersItemReceiveStatus: TypeAlias = Literal["NOT_RECEIVED", "PARTIALLY_RECEIVED", "RECEIVED"]
VendorOrdersPurchaseOrderState: TypeAlias = Literal["New", "Acknowledged", "Closed"]
VendorOrdersPurchaseOrderStatus: TypeAlias = Literal["OPEN", "CLOSED"]
VendorOrdersSortOrder: TypeAlias = Literal["ASC", "DESC"]


class AcknowledgementStatusDetails(SpecModel):
    """Details of item quantity ordered"""

    acknowledgement_date: datetime.datetime | None = Field(default=None, alias="acknowledgementDate")
    accepted_quantity: ItemQuantity | None = Field(default=None, alias="acceptedQuantity")
    rejected_quantity: ItemQuantity | None = Field(default=None, alias="rejectedQuantity")


class Address(SpecModel):
    """Address of the party."""

    name: str
    address_line1: str = Field(alias="addressLine1")
    address_line2: str | None = Field(default=None, alias="addressLine2")
    address_line3: str | None = Field(default=None, alias="addressLine3")
    city: str | None = None
    county: str | None = None
    district: str | None = None
    state_or_region: str | None = Field(default=None, alias="stateOrRegion")
    postal_code: str | None = Field(default=None, alias="postalCode")
    country_code: str = Field(alias="countryCode")
    phone: str | None = None


class Error(SpecModel):
    """Error response returned when the request is unsuccessful."""

    code: str
    message: str
    details: str | None = None


class GetPurchaseOrderResponse(SpecModel):
    """The response schema for the getPurchaseOrder operation."""

    payload: Order | None = None
    errors: list[Error] | None = None


class GetPurchaseOrdersResponse(SpecModel):
    """The response schema for the getPurchaseOrders operation."""

    payload: OrderList | None = None
    errors: list[Error] | None = None


class GetPurchaseOrdersStatusResponse(SpecModel):
    """The response schema for the getPurchaseOrdersStatus operation."""

    payload: OrderListStatus | None = None
    errors: list[Error] | None = None


class ImportDetails(SpecModel):
    """Import details for an import order."""

    method_of_payment: ImportDetailsMethodOfPayment | None = Field(default=None, alias="methodOfPayment")
    international_commercial_terms: ImportDetailsInternationalCommercialTerms | None = Field(
        default=None, alias="internationalCommercialTerms"
    )
    port_of_delivery: str | None = Field(default=None, alias="portOfDelivery")
    import_containers: str | None = Field(default=None, alias="importContainers")
    shipping_instructions: str | None = Field(default=None, alias="shippingInstructions")


class ItemQuantity(SpecModel):
    """Details of quantity ordered."""

    amount: int | None = None
    unit_of_measure: ItemQuantityUnitOfMeasure | None = Field(default=None, alias="unitOfMeasure")
    unit_size: int | None = Field(default=None, alias="unitSize")


class Money(SpecModel):
    """An amount of money. Includes the currency code and an optional unit of measure for items priced by weight."""

    currency_code: str | None = Field(default=None, alias="currencyCode")
    amount: str | None = None
    unit_of_measure: MoneyUnitOfMeasure | None = Field(default=None, alias="unitOfMeasure")


class Order(SpecModel):
    """Represents an order placed by Amazon, including the purchase order number, current state, and order details."""

    purchase_order_number: str = Field(alias="purchaseOrderNumber")
    purchase_order_state: OrderPurchaseOrderState = Field(alias="purchaseOrderState")
    order_details: OrderDetails | None = Field(default=None, alias="orderDetails")


class OrderAcknowledgement(SpecModel):
    """Represents an acknowledgement for an order, including the purchase order number, selling party details, acknowledgement date, and a list of acknowledged items."""

    purchase_order_number: str = Field(alias="purchaseOrderNumber")
    selling_party: PartyIdentification = Field(alias="sellingParty")
    acknowledgement_date: datetime.datetime = Field(alias="acknowledgementDate")
    items: list[OrderAcknowledgementItem]


class OrderAcknowledgementItem(SpecModel):
    """Details of the item being acknowledged."""

    item_sequence_number: str | None = Field(default=None, alias="itemSequenceNumber")
    amazon_product_identifier: str | None = Field(default=None, alias="amazonProductIdentifier")
    vendor_product_identifier: str | None = Field(default=None, alias="vendorProductIdentifier")
    ordered_quantity: ItemQuantity = Field(alias="orderedQuantity")
    net_cost: Money | None = Field(default=None, alias="netCost")
    list_price: Money | None = Field(default=None, alias="listPrice")
    discount_multiplier: str | None = Field(default=None, alias="discountMultiplier")
    item_acknowledgements: list[OrderItemAcknowledgement] = Field(alias="itemAcknowledgements")


class OrderDetails(SpecModel):
    """Details of an order."""

    purchase_order_date: datetime.datetime = Field(alias="purchaseOrderDate")
    purchase_order_changed_date: datetime.datetime | None = Field(default=None, alias="purchaseOrderChangedDate")
    purchase_order_state_changed_date: datetime.datetime = Field(alias="purchaseOrderStateChangedDate")
    purchase_order_type: OrderDetailsPurchaseOrderType | None = Field(default=None, alias="purchaseOrderType")
    import_details: ImportDetails | None = Field(default=None, alias="importDetails")
    deal_code: str | None = Field(default=None, alias="dealCode")
    payment_method: OrderDetailsPaymentMethod | None = Field(default=None, alias="paymentMethod")
    buying_party: PartyIdentification | None = Field(default=None, alias="buyingParty")
    selling_party: PartyIdentification | None = Field(default=None, alias="sellingParty")
    ship_to_party: PartyIdentification | None = Field(default=None, alias="shipToParty")
    bill_to_party: PartyIdentification | None = Field(default=None, alias="billToParty")
    ship_window: str | None = Field(default=None, alias="shipWindow")
    delivery_window: str | None = Field(default=None, alias="deliveryWindow")
    items: list[OrderItem]


class OrderedQuantityDetails(SpecModel):
    """Details of item quantity ordered."""

    updated_date: datetime.datetime | None = Field(default=None, alias="updatedDate")
    ordered_quantity: ItemQuantity | None = Field(default=None, alias="orderedQuantity")
    cancelled_quantity: ItemQuantity | None = Field(default=None, alias="cancelledQuantity")


class OrderItem(SpecModel):
    """Represents an individual item in an order, including item details, quantities, pricing, and backorder information."""

    item_sequence_number: str = Field(alias="itemSequenceNumber")
    amazon_product_identifier: str | None = Field(default=None, alias="amazonProductIdentifier")
    vendor_product_identifier: str | None = Field(default=None, alias="vendorProductIdentifier")
    ordered_quantity: ItemQuantity = Field(alias="orderedQuantity")
    is_back_order_allowed: bool = Field(alias="isBackOrderAllowed")
    net_cost: Money | None = Field(default=None, alias="netCost")
    list_price: Money | None = Field(default=None, alias="listPrice")


class OrderItemAcknowledgement(SpecModel):
    """Represents the acknowledgement details for an individual order item, including the acknowledgement code, acknowledged quantity, scheduled ship and delivery dates, and rejection reason (if applicable)."""

    acknowledgement_code: OrderItemAcknowledgementAcknowledgementCode = Field(alias="acknowledgementCode")
    acknowledged_quantity: ItemQuantity = Field(alias="acknowledgedQuantity")
    scheduled_ship_date: datetime.datetime | None = Field(default=None, alias="scheduledShipDate")
    scheduled_delivery_date: datetime.datetime | None = Field(default=None, alias="scheduledDeliveryDate")
    rejection_reason: OrderItemAcknowledgementRejectionReason | None = Field(default=None, alias="rejectionReason")


class OrderItemStatus(SpecModel):
    """Represents the current status of an order item, including acknowledgement and receiving details."""

    item_sequence_number: str = Field(alias="itemSequenceNumber")
    buyer_product_identifier: str | None = Field(default=None, alias="buyerProductIdentifier")
    vendor_product_identifier: str | None = Field(default=None, alias="vendorProductIdentifier")
    net_cost: Money | None = Field(default=None, alias="netCost")
    list_price: Money | None = Field(default=None, alias="listPrice")
    ordered_quantity: OrderItemStatusOrderedQuantity | None = Field(default=None, alias="orderedQuantity")
    acknowledgement_status: OrderItemStatusAcknowledgementStatus | None = Field(default=None, alias="acknowledgementStatus")
    receiving_status: OrderItemStatusReceivingStatus | None = Field(default=None, alias="receivingStatus")


class OrderItemStatusAcknowledgementStatus(SpecModel):
    confirmation_status: OrderItemStatusAcknowledgementStatusConfirmationStatus | None = Field(default=None, alias="confirmationStatus")
    accepted_quantity: ItemQuantity | None = Field(default=None, alias="acceptedQuantity")
    rejected_quantity: ItemQuantity | None = Field(default=None, alias="rejectedQuantity")
    acknowledgement_status_details: list[AcknowledgementStatusDetails] | None = Field(default=None, alias="acknowledgementStatusDetails")


class OrderItemStatusOrderedQuantity(SpecModel):
    ordered_quantity: ItemQuantity | None = Field(default=None, alias="orderedQuantity")
    ordered_quantity_details: list[OrderedQuantityDetails] | None = Field(default=None, alias="orderedQuantityDetails")


class OrderItemStatusReceivingStatus(SpecModel):
    receive_status: OrderItemStatusReceivingStatusReceiveStatus | None = Field(default=None, alias="receiveStatus")
    received_quantity: ItemQuantity | None = Field(default=None, alias="receivedQuantity")
    last_receive_date: datetime.datetime | None = Field(default=None, alias="lastReceiveDate")


class OrderList(SpecModel):
    """A list of orders returned as response."""

    pagination: Pagination | None = None
    orders: list[Order] | None = None


class OrderListStatus(SpecModel):
    """A list of order statuses."""

    pagination: Pagination | None = None
    orders_status: list[OrderStatus] | None = Field(default=None, alias="ordersStatus")


class OrderStatus(SpecModel):
    """Current status of a purchase order."""

    purchase_order_number: str = Field(alias="purchaseOrderNumber")
    purchase_order_status: OrderStatusPurchaseOrderStatus = Field(alias="purchaseOrderStatus")
    purchase_order_date: datetime.datetime = Field(alias="purchaseOrderDate")
    last_updated_date: datetime.datetime | None = Field(default=None, alias="lastUpdatedDate")
    selling_party: PartyIdentification = Field(alias="sellingParty")
    ship_to_party: PartyIdentification = Field(alias="shipToParty")
    item_status: list[OrderItemStatus] = Field(alias="itemStatus")


class Pagination(SpecModel):
    """The pagination elements required to retrieve the remaining data."""

    next_token: str | None = Field(default=None, alias="nextToken")


class PartyIdentification(SpecModel):
    """Name, address and tax details of a party."""

    party_id: str = Field(alias="partyId")
    address: Address | None = None
    tax_info: TaxRegistrationDetails | None = Field(default=None, alias="taxInfo")


class SubmitAcknowledgementRequest(SpecModel):
    """The request schema for the submitAcknowledgment operation."""

    acknowledgements: list[OrderAcknowledgement] | None = None


class SubmitAcknowledgementResponse(SpecModel):
    """The response schema for the submitAcknowledgement operation"""

    payload: TransactionId | None = None
    errors: list[Error] | None = None


class TaxRegistrationDetails(SpecModel):
    """Tax registration details of the entity."""

    tax_registration_type: TaxRegistrationDetailsTaxRegistrationType = Field(alias="taxRegistrationType")
    tax_registration_number: str = Field(alias="taxRegistrationNumber")


class TransactionId(SpecModel):
    """Response containing the transaction ID."""

    transaction_id: str | None = Field(default=None, alias="transactionId")


__all__ = [
    "AcknowledgementStatusDetails",
    "Address",
    "Error",
    "GetPurchaseOrderResponse",
    "GetPurchaseOrdersResponse",
    "GetPurchaseOrdersStatusResponse",
    "ImportDetails",
    "ImportDetailsInternationalCommercialTerms",
    "ImportDetailsMethodOfPayment",
    "ItemQuantity",
    "ItemQuantityUnitOfMeasure",
    "Money",
    "MoneyUnitOfMeasure",
    "Order",
    "OrderAcknowledgement",
    "OrderAcknowledgementItem",
    "OrderDetails",
    "OrderDetailsPaymentMethod",
    "OrderDetailsPurchaseOrderType",
    "OrderItem",
    "OrderItemAcknowledgement",
    "OrderItemAcknowledgementAcknowledgementCode",
    "OrderItemAcknowledgementRejectionReason",
    "OrderItemStatus",
    "OrderItemStatusAcknowledgementStatus",
    "OrderItemStatusAcknowledgementStatusConfirmationStatus",
    "OrderItemStatusOrderedQuantity",
    "OrderItemStatusReceivingStatus",
    "OrderItemStatusReceivingStatusReceiveStatus",
    "OrderList",
    "OrderListStatus",
    "OrderPurchaseOrderState",
    "OrderStatus",
    "OrderStatusPurchaseOrderStatus",
    "OrderedQuantityDetails",
    "Pagination",
    "PartyIdentification",
    "SubmitAcknowledgementRequest",
    "SubmitAcknowledgementResponse",
    "TaxRegistrationDetails",
    "TaxRegistrationDetailsTaxRegistrationType",
    "TransactionId",
    "VendorOrdersItemConfirmationStatus",
    "VendorOrdersItemReceiveStatus",
    "VendorOrdersPurchaseOrderState",
    "VendorOrdersPurchaseOrderStatus",
    "VendorOrdersSortOrder",
]
