# Generated by `python -m spapi.stubgen`; do not edit.
from __future__ import annotations
from typing import Any, Literal, overload
from spapi.compile.resources import AsyncResource, SyncResource
from spapi.models.vendor_transaction_status import v1 as models
from spapi.runtime import NOT_GIVEN, NotGiven, Pagination, RequestOptions

class VendorTransactionStatus(SyncResource):
    models: Any
    @overload
    def get_transaction(self, *, transaction_id: str, raw: Literal[False] = ..., paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.GetTransactionResponse: ...
    @overload
    def get_transaction(self, *, transaction_id: str, raw: Literal[True], paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.GetTransactionResponseDict: ...
    def get_transaction(self, *, transaction_id: str, raw: bool = False, paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.GetTransactionResponse:
        """Returns the status of the transaction that you specify."""

class AsyncVendorTransactionStatus(AsyncResource):
    models: Any
    @overload
    async def get_transaction(self, *, transaction_id: str, raw: Literal[False] = ..., paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.GetTransactionResponse: ...
    @overload
    async def get_transaction(self, *, transaction_id: str, raw: Literal[True], paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.GetTransactionResponseDict: ...
    async def get_transaction(self, *, transaction_id: str, raw: bool = False, paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.GetTransactionResponse:
        """Returns the status of the transaction that you specify."""
