# Auto-generated by oagen. Do not edit.

"""Enums of supply_sources_v2020_07_01.

Auto-generated by oagen from the OpenAPI spec; do not edit by hand.
"""

from __future__ import annotations

from enum import Enum


class ParkingCostType(str, Enum):
    FREE = "Free"
    OTHER = "Other"

    __str__ = str.__str__


class ParkingSpotIdentificationType(str, Enum):
    NUMBERED = "Numbered"
    OTHER = "Other"

    __str__ = str.__str__


class SupplySourceStatus(str, Enum):
    ACTIVE = "Active"
    INACTIVE = "Inactive"

    __str__ = str.__str__


class SupplySourceStatusReadOnly(str, Enum):
    ACTIVE = "Active"
    INACTIVE = "Inactive"
    ARCHIVED = "Archived"

    __str__ = str.__str__


class ThroughputUnit(str, Enum):
    ORDER = "Order"

    __str__ = str.__str__


class TimeUnit(str, Enum):
    HOURS = "Hours"
    MINUTES = "Minutes"
    DAYS = "Days"

    __str__ = str.__str__


__all__ = [
    "ParkingCostType",
    "ParkingSpotIdentificationType",
    "SupplySourceStatus",
    "SupplySourceStatusReadOnly",
    "ThroughputUnit",
    "TimeUnit",
]
