# Auto-generated by oagen. Do not edit.

"""Models of supply_sources_v2020_07_01.

Auto-generated by oagen from the OpenAPI spec; do not edit by hand.
"""

from __future__ import annotations

from pydantic import Field

from .._base import SpecModel
from .enums import ParkingCostType, ParkingSpotIdentificationType, SupplySourceStatus, SupplySourceStatusReadOnly, ThroughputUnit, TimeUnit


class Address(SpecModel):
    """A physical address."""

    name: str
    address_line1: str = Field(alias="addressLine1")
    state_or_region: str = Field(alias="stateOrRegion")
    country_code: str = Field(alias="countryCode")
    address_line2: str | None = Field(default=None, alias="addressLine2")
    address_line3: str | None = Field(default=None, alias="addressLine3")
    city: str | None = None
    county: str | None = None
    district: str | None = None
    postal_code: str | None = Field(default=None, alias="postalCode")
    phone: str | None = None


class AddressWithContact(SpecModel):
    """The address and contact details."""

    contact_details: ContactDetails | None = Field(default=None, alias="contactDetails")
    address: Address | None = None


class ContactDetails(SpecModel):
    """The contact details"""

    primary: ContactDetailsPrimary | None = None


class ContactDetailsPrimary(SpecModel):
    email: str | None = None
    phone: str | None = None


class CreateSupplySourceRequest(SpecModel):
    """A request to create a supply source."""

    supply_source_code: str = Field(alias="supplySourceCode")
    alias: str
    address: Address


class CreateSupplySourceResponse(SpecModel):
    """The result of creating a new supply source."""

    supply_source_id: str = Field(alias="supplySourceId")
    supply_source_code: str = Field(alias="supplySourceCode")


class CurbsidePickupConfiguration(SpecModel):
    """The curbside pickup configuration of a supply source."""

    is_supported: bool | None = Field(default=None, alias="isSupported")
    operational_configuration: OperationalConfiguration | None = Field(default=None, alias="operationalConfiguration")
    parking_with_address_configuration: ParkingWithAddressConfiguration | None = Field(
        default=None, alias="parkingWithAddressConfiguration"
    )


class DeliveryChannel(SpecModel):
    """The delivery channel of a supply source."""

    is_supported: bool | None = Field(default=None, alias="isSupported")
    operational_configuration: OperationalConfiguration | None = Field(default=None, alias="operationalConfiguration")


class Duration(SpecModel):
    """The duration of time."""

    value: int | None = None
    time_unit: TimeUnit | None = Field(default=None, alias="timeUnit")


class Error(SpecModel):
    """An error response returned when the request is unsuccessful."""

    code: str
    message: str
    details: str | None = None


class ErrorList(SpecModel):
    """A list of error responses returned when a request is unsuccessful."""

    errors: list[Error]


class GetSupplySourcesResponse(SpecModel):
    """The paginated list of supply sources."""

    supply_sources: list[GetSupplySourcesResponseSupplySource] | None = Field(default=None, alias="supplySources")
    next_page_token: str | None = Field(default=None, alias="nextPageToken")


class GetSupplySourcesResponseSupplySource(SpecModel):
    alias: str | None = None
    supply_source_id: str | None = Field(default=None, alias="supplySourceId")
    supply_source_code: str | None = Field(default=None, alias="supplySourceCode")
    address: Address | None = None


class InStorePickupConfiguration(SpecModel):
    """The in-store pickup configuration of a supply source."""

    is_supported: bool | None = Field(default=None, alias="isSupported")
    parking_configuration: ParkingConfiguration | None = Field(default=None, alias="parkingConfiguration")


class OperatingHour(SpecModel):
    """The operating hour schema"""

    start_time: str | None = Field(default=None, alias="startTime")
    end_time: str | None = Field(default=None, alias="endTime")


class OperatingHoursByDay(SpecModel):
    """The operating hours per day"""

    monday: list[OperatingHour] | None = None
    tuesday: list[OperatingHour] | None = None
    wednesday: list[OperatingHour] | None = None
    thursday: list[OperatingHour] | None = None
    friday: list[OperatingHour] | None = None
    saturday: list[OperatingHour] | None = None
    sunday: list[OperatingHour] | None = None


class OperationalConfiguration(SpecModel):
    """The operational configuration of `supplySources`."""

    contact_details: ContactDetails | None = Field(default=None, alias="contactDetails")
    throughput_config: ThroughputConfig | None = Field(default=None, alias="throughputConfig")
    operating_hours_by_day: OperatingHoursByDay | None = Field(default=None, alias="operatingHoursByDay")
    handling_time: Duration | None = Field(default=None, alias="handlingTime")


class OutboundCapability(SpecModel):
    """The outbound capability of a supply source."""

    is_supported: bool | None = Field(default=None, alias="isSupported")
    operational_configuration: OperationalConfiguration | None = Field(default=None, alias="operationalConfiguration")
    return_location: ReturnLocation | None = Field(default=None, alias="returnLocation")
    delivery_channel: DeliveryChannel | None = Field(default=None, alias="deliveryChannel")
    pickup_channel: PickupChannel | None = Field(default=None, alias="pickupChannel")


class ParkingConfiguration(SpecModel):
    """The parking configuration."""

    parking_cost_type: ParkingCostType | None = Field(default=None, alias="parkingCostType")
    parking_spot_identification_type: ParkingSpotIdentificationType | None = Field(default=None, alias="parkingSpotIdentificationType")
    number_of_parking_spots: int | None = Field(default=None, alias="numberOfParkingSpots")


class ParkingWithAddressConfiguration(SpecModel):
    """The parking configuration with the address."""

    parking_cost_type: ParkingCostType | None = Field(default=None, alias="parkingCostType")
    parking_spot_identification_type: ParkingSpotIdentificationType | None = Field(default=None, alias="parkingSpotIdentificationType")
    number_of_parking_spots: int | None = Field(default=None, alias="numberOfParkingSpots")
    address: Address | None = None


class PickupChannel(SpecModel):
    """The pick up channel of a supply source."""

    inventory_hold_period: Duration | None = Field(default=None, alias="inventoryHoldPeriod")
    is_supported: bool | None = Field(default=None, alias="isSupported")
    operational_configuration: OperationalConfiguration | None = Field(default=None, alias="operationalConfiguration")
    in_store_pickup_configuration: InStorePickupConfiguration | None = Field(default=None, alias="inStorePickupConfiguration")
    curbside_pickup_configuration: CurbsidePickupConfiguration | None = Field(default=None, alias="curbsidePickupConfiguration")


class ReturnLocation(SpecModel):
    """The address or reference to another `supplySourceId` to act as a return location."""

    supply_source_id: str | None = Field(default=None, alias="supplySourceId")
    address_with_contact: AddressWithContact | None = Field(default=None, alias="addressWithContact")


class ServicesCapability(SpecModel):
    """The services capability of a supply source."""

    is_supported: bool | None = Field(default=None, alias="isSupported")
    operational_configuration: OperationalConfiguration | None = Field(default=None, alias="operationalConfiguration")


class SupplySource(SpecModel):
    """The supply source details, including configurations and capabilities."""

    supply_source_id: str | None = Field(default=None, alias="supplySourceId")
    supply_source_code: str | None = Field(default=None, alias="supplySourceCode")
    alias: str | None = None
    status: SupplySourceStatusReadOnly | None = None
    address: Address | None = None
    configuration: SupplySourceConfiguration | None = None
    capabilities: SupplySourceCapabilities | None = None
    created_at: str | None = Field(default=None, alias="createdAt")
    updated_at: str | None = Field(default=None, alias="updatedAt")


class SupplySourceCapabilities(SpecModel):
    """The capabilities of a supply source."""

    outbound: OutboundCapability | None = None
    services: ServicesCapability | None = None


class SupplySourceConfiguration(SpecModel):
    """Includes configuration and timezone of a supply source."""

    operational_configuration: OperationalConfiguration | None = Field(default=None, alias="operationalConfiguration")
    timezone: str | None = None


class ThroughputCap(SpecModel):
    """The throughput capacity"""

    value: int | None = None
    time_unit: TimeUnit | None = Field(default=None, alias="timeUnit")


class ThroughputConfig(SpecModel):
    """The throughput configuration."""

    throughput_unit: ThroughputUnit = Field(alias="throughputUnit")
    throughput_cap: ThroughputCap | None = Field(default=None, alias="throughputCap")


class UpdateSupplySourceRequest(SpecModel):
    """A request to update the configuration and capabilities of a supply source."""

    alias: str | None = None
    configuration: SupplySourceConfiguration | None = None
    capabilities: SupplySourceCapabilities | None = None


class UpdateSupplySourceStatusRequest(SpecModel):
    """A request to update the status of a supply source."""

    status: SupplySourceStatus | None = None


__all__ = [
    "Address",
    "AddressWithContact",
    "ContactDetails",
    "ContactDetailsPrimary",
    "CreateSupplySourceRequest",
    "CreateSupplySourceResponse",
    "CurbsidePickupConfiguration",
    "DeliveryChannel",
    "Duration",
    "Error",
    "ErrorList",
    "GetSupplySourcesResponse",
    "GetSupplySourcesResponseSupplySource",
    "InStorePickupConfiguration",
    "OperatingHour",
    "OperatingHoursByDay",
    "OperationalConfiguration",
    "OutboundCapability",
    "ParkingConfiguration",
    "ParkingWithAddressConfiguration",
    "PickupChannel",
    "ReturnLocation",
    "ServicesCapability",
    "SupplySource",
    "SupplySourceCapabilities",
    "SupplySourceConfiguration",
    "ThroughputCap",
    "ThroughputConfig",
    "UpdateSupplySourceRequest",
    "UpdateSupplySourceStatusRequest",
]
