# Auto-generated by oagen. Do not edit.

"""Models package ``data_kiosk_v2023_11_15``.

Auto-generated by oagen from the OpenAPI spec; do not edit by hand.
"""

from __future__ import annotations

from .enums import DataKioskV20231115ProcessingStatuses, QueryProcessingStatus
from .models import (
    CreateQueryResponse,
    CreateQuerySpecification,
    Error,
    ErrorList,
    GetDocumentResponse,
    GetQueriesResponse,
    GetQueriesResponsePagination,
    Query,
    QueryPagination,
)

__all__ = [
    "CreateQueryResponse",
    "CreateQuerySpecification",
    "DataKioskV20231115ProcessingStatuses",
    "Error",
    "ErrorList",
    "GetDocumentResponse",
    "GetQueriesResponse",
    "GetQueriesResponsePagination",
    "Query",
    "QueryPagination",
    "QueryProcessingStatus",
]
