"""Models for vendor_direct_fulfillment_shipping v2021_12_28 (Selling Partner API for Direct Fulfillment Shipping).

Generated by codegen/ (oagen) from the pinned spec; do not edit by hand.
"""

from __future__ import annotations

import datetime
from typing import Literal, TypeAlias

from pydantic import Field

from amzn_selling_partner.runtime._models import SpecModel

CarrierId: TypeAlias = Literal["SWA"]
ContainerLabelFormat: TypeAlias = Literal["PNG", "ZPL"]
ContainerType: TypeAlias = Literal["Carton", "Pallet"]
CustomerInvoicesSortOrder: TypeAlias = Literal["ASC", "DESC"]
DimensionsUnitOfMeasure: TypeAlias = Literal["IN", "CM"]
ShipmentDetailsShipmentStatus: TypeAlias = Literal["SHIPPED", "FLOOR_DENIAL"]
ShippingLabelLabelFormat: TypeAlias = Literal["PNG", "ZPL"]
TaxRegistrationDetailsTaxRegistrationType: TypeAlias = Literal["VAT", "GST"]
VendorShippingLabelsSortOrder: TypeAlias = Literal["ASC", "DESC"]
VendorShippingSortOrder: TypeAlias = Literal["ASC", "DESC"]
WeightUnitOfMeasure: TypeAlias = Literal["KG", "LB"]


class Address(SpecModel):
    """Address of the party."""

    name: str
    address_line1: str = Field(alias="addressLine1")
    address_line2: str | None = Field(default=None, alias="addressLine2")
    address_line3: str | None = Field(default=None, alias="addressLine3")
    city: str | None = None
    county: str | None = None
    district: str | None = None
    state_or_region: str | None = Field(default=None, alias="stateOrRegion")
    postal_code: str | None = Field(default=None, alias="postalCode")
    country_code: str = Field(alias="countryCode")
    phone: str | None = None


class Container(SpecModel):
    """A container used for shipping and packing items."""

    container_type: ContainerType = Field(alias="containerType")
    container_identifier: str = Field(alias="containerIdentifier")
    tracking_number: str | None = Field(default=None, alias="trackingNumber")
    manifest_id: str | None = Field(default=None, alias="manifestId")
    manifest_date: str | None = Field(default=None, alias="manifestDate")
    ship_method: str | None = Field(default=None, alias="shipMethod")
    scac_code: str | None = Field(default=None, alias="scacCode")
    carrier: str | None = None
    container_sequence_number: int | None = Field(default=None, alias="containerSequenceNumber")
    dimensions: Dimensions | None = None
    weight: Weight
    packed_items: list[PackedItem] = Field(alias="packedItems")


class ContainerLabel(SpecModel):
    """The details of the container label."""

    container_tracking_number: str | None = Field(default=None, alias="containerTrackingNumber")
    content: str
    format: ContainerLabelFormat


class CreateContainerLabelRequest(SpecModel):
    """The request body schema for the `createContainerLabel` operation."""

    selling_party: PartyIdentification = Field(alias="sellingParty")
    ship_from_party: PartyIdentification = Field(alias="shipFromParty")
    carrier_id: CarrierId = Field(alias="carrierId")
    vendor_container_id: str = Field(alias="vendorContainerId")
    packages: list[Package]


class CreateContainerLabelResponse(SpecModel):
    """The response schema for the `createContainerLabel` operation."""

    container_label: ContainerLabel = Field(alias="containerLabel")


class CreateShippingLabelsRequest(SpecModel):
    """The request body for the createShippingLabels operation."""

    selling_party: PartyIdentification = Field(alias="sellingParty")
    ship_from_party: PartyIdentification = Field(alias="shipFromParty")
    containers: list[Container] | None = None


class CustomerInvoice(SpecModel):
    """Represents a customer invoice associated with a purchase order."""

    purchase_order_number: str = Field(alias="purchaseOrderNumber")
    content: str


class CustomerInvoiceList(SpecModel):
    """Represents a list of customer invoices, potentially paginated."""

    pagination: Pagination | None = None
    customer_invoices: list[CustomerInvoice] | None = Field(default=None, alias="customerInvoices")


class Dimensions(SpecModel):
    """Physical dimensional measurements of a container."""

    length: str
    width: str
    height: str
    unit_of_measure: DimensionsUnitOfMeasure = Field(alias="unitOfMeasure")


class Error(SpecModel):
    """Error response returned when the request is unsuccessful."""

    code: str
    message: str
    details: str | None = None


class ErrorList(SpecModel):
    """A list of error responses returned when a request is unsuccessful."""

    errors: list[Error]


class Item(SpecModel):
    """Details of the item being shipped."""

    item_sequence_number: int = Field(alias="itemSequenceNumber")
    buyer_product_identifier: str | None = Field(default=None, alias="buyerProductIdentifier")
    vendor_product_identifier: str | None = Field(default=None, alias="vendorProductIdentifier")
    shipped_quantity: ItemQuantity = Field(alias="shippedQuantity")


class ItemQuantity(SpecModel):
    """Details of item quantity."""

    amount: int
    unit_of_measure: str = Field(alias="unitOfMeasure")


class LabelData(SpecModel):
    """Details of the shipment label."""

    package_identifier: str | None = Field(default=None, alias="packageIdentifier")
    tracking_number: str | None = Field(default=None, alias="trackingNumber")
    ship_method: str | None = Field(default=None, alias="shipMethod")
    ship_method_name: str | None = Field(default=None, alias="shipMethodName")
    content: str


class Package(SpecModel):
    """The package that is associated with the container."""

    package_tracking_number: str = Field(alias="packageTrackingNumber")


class PackedItem(SpecModel):
    """An item that has been packed into a container for shipping."""

    item_sequence_number: int = Field(alias="itemSequenceNumber")
    buyer_product_identifier: str | None = Field(default=None, alias="buyerProductIdentifier")
    piece_number: int | None = Field(default=None, alias="pieceNumber")
    vendor_product_identifier: str | None = Field(default=None, alias="vendorProductIdentifier")
    packed_quantity: ItemQuantity = Field(alias="packedQuantity")


class PackingSlip(SpecModel):
    """Packing slip information."""

    purchase_order_number: str = Field(alias="purchaseOrderNumber")
    content: str
    content_type: Literal["application/pdf"] | None = Field(default=None, alias="contentType")


class PackingSlipList(SpecModel):
    """A list of packing slips."""

    pagination: Pagination | None = None
    packing_slips: list[PackingSlip] | None = Field(default=None, alias="packingSlips")


class Pagination(SpecModel):
    """The pagination elements required to retrieve the remaining data."""

    next_token: str | None = Field(default=None, alias="nextToken")


class PartyIdentification(SpecModel):
    """The name, address, and tax details of a party."""

    party_id: str = Field(alias="partyId")
    address: Address | None = None
    tax_registration_details: list[TaxRegistrationDetails] | None = Field(default=None, alias="taxRegistrationDetails")


class ShipmentConfirmation(SpecModel):
    """Represents the confirmation details of a shipment, including the purchase order number and other shipment details."""

    purchase_order_number: str = Field(alias="purchaseOrderNumber")
    shipment_details: ShipmentDetails = Field(alias="shipmentDetails")
    selling_party: PartyIdentification = Field(alias="sellingParty")
    ship_from_party: PartyIdentification = Field(alias="shipFromParty")
    items: list[Item]
    containers: list[Container] | None = None


class ShipmentDetails(SpecModel):
    """Details about a shipment."""

    shipped_date: datetime.datetime = Field(alias="shippedDate")
    shipment_status: ShipmentDetailsShipmentStatus = Field(alias="shipmentStatus")
    is_priority_shipment: bool | None = Field(default=None, alias="isPriorityShipment")
    vendor_order_number: str | None = Field(default=None, alias="vendorOrderNumber")
    estimated_delivery_date: datetime.datetime | None = Field(default=None, alias="estimatedDeliveryDate")


class ShipmentSchedule(SpecModel):
    """Details about the estimated delivery window."""

    estimated_delivery_date_time: datetime.datetime | None = Field(default=None, alias="estimatedDeliveryDateTime")
    appt_window_start_date_time: datetime.datetime | None = Field(default=None, alias="apptWindowStartDateTime")
    appt_window_end_date_time: datetime.datetime | None = Field(default=None, alias="apptWindowEndDateTime")


class ShipmentStatusUpdate(SpecModel):
    """Represents an update to the status of a shipment."""

    purchase_order_number: str = Field(alias="purchaseOrderNumber")
    selling_party: PartyIdentification = Field(alias="sellingParty")
    ship_from_party: PartyIdentification = Field(alias="shipFromParty")
    status_update_details: StatusUpdateDetails = Field(alias="statusUpdateDetails")


class ShippingLabel(SpecModel):
    """Shipping label information for an order, including the purchase order number, selling party, ship from party, label format, and package details."""

    purchase_order_number: str = Field(alias="purchaseOrderNumber")
    selling_party: PartyIdentification = Field(alias="sellingParty")
    ship_from_party: PartyIdentification = Field(alias="shipFromParty")
    label_format: ShippingLabelLabelFormat = Field(alias="labelFormat")
    label_data: list[LabelData] = Field(alias="labelData")


class ShippingLabelList(SpecModel):
    """Response payload with the list of shipping labels."""

    pagination: Pagination | None = None
    shipping_labels: list[ShippingLabel] | None = Field(default=None, alias="shippingLabels")


class ShippingLabelRequest(SpecModel):
    """Represents the request payload for creating a shipping label, containing the purchase order number, selling party, ship from party, and a list of containers or packages in the shipment."""

    purchase_order_number: str = Field(alias="purchaseOrderNumber")
    selling_party: PartyIdentification = Field(alias="sellingParty")
    ship_from_party: PartyIdentification = Field(alias="shipFromParty")
    containers: list[Container] | None = None


class StatusUpdateDetails(SpecModel):
    """Details for the shipment status update given by the vendor for the specific package."""

    tracking_number: str = Field(alias="trackingNumber")
    status_code: str = Field(alias="statusCode")
    reason_code: str = Field(alias="reasonCode")
    status_date_time: datetime.datetime = Field(alias="statusDateTime")
    status_location_address: Address = Field(alias="statusLocationAddress")
    shipment_schedule: ShipmentSchedule | None = Field(default=None, alias="shipmentSchedule")


class SubmitShipmentConfirmationsRequest(SpecModel):
    """The request schema for the submitShipmentConfirmations operation."""

    shipment_confirmations: list[ShipmentConfirmation] | None = Field(default=None, alias="shipmentConfirmations")


class SubmitShipmentStatusUpdatesRequest(SpecModel):
    """The request schema for the `submitShipmentStatusUpdates` operation."""

    shipment_status_updates: list[ShipmentStatusUpdate] | None = Field(default=None, alias="shipmentStatusUpdates")


class SubmitShippingLabelsRequest(SpecModel):
    """The request schema for the `submitShippingLabelRequest` operation."""

    shipping_label_requests: list[ShippingLabelRequest] | None = Field(default=None, alias="shippingLabelRequests")


class TaxRegistrationDetails(SpecModel):
    """Tax registration details of the entity."""

    tax_registration_type: TaxRegistrationDetailsTaxRegistrationType | None = Field(default=None, alias="taxRegistrationType")
    tax_registration_number: str = Field(alias="taxRegistrationNumber")
    tax_registration_address: Address | None = Field(default=None, alias="taxRegistrationAddress")
    tax_registration_messages: str | None = Field(default=None, alias="taxRegistrationMessages")


class TransactionReference(SpecModel):
    """Response containing the transaction ID."""

    transaction_id: str | None = Field(default=None, alias="transactionId")


class Weight(SpecModel):
    """The weight."""

    unit_of_measure: WeightUnitOfMeasure = Field(alias="unitOfMeasure")
    value: str


__all__ = [
    "Address",
    "CarrierId",
    "Container",
    "ContainerLabel",
    "ContainerLabelFormat",
    "ContainerType",
    "CreateContainerLabelRequest",
    "CreateContainerLabelResponse",
    "CreateShippingLabelsRequest",
    "CustomerInvoice",
    "CustomerInvoiceList",
    "CustomerInvoicesSortOrder",
    "Dimensions",
    "DimensionsUnitOfMeasure",
    "Error",
    "ErrorList",
    "Item",
    "ItemQuantity",
    "LabelData",
    "Package",
    "PackedItem",
    "PackingSlip",
    "PackingSlipList",
    "Pagination",
    "PartyIdentification",
    "ShipmentConfirmation",
    "ShipmentDetails",
    "ShipmentDetailsShipmentStatus",
    "ShipmentSchedule",
    "ShipmentStatusUpdate",
    "ShippingLabel",
    "ShippingLabelLabelFormat",
    "ShippingLabelList",
    "ShippingLabelRequest",
    "StatusUpdateDetails",
    "SubmitShipmentConfirmationsRequest",
    "SubmitShipmentStatusUpdatesRequest",
    "SubmitShippingLabelsRequest",
    "TaxRegistrationDetails",
    "TaxRegistrationDetailsTaxRegistrationType",
    "TransactionReference",
    "VendorShippingLabelsSortOrder",
    "VendorShippingSortOrder",
    "Weight",
    "WeightUnitOfMeasure",
]
