# Auto-generated by oagen. Do not edit.

"""Enums of finances_invoices_v2026_06_25.

Auto-generated by oagen from the OpenAPI spec; do not edit by hand.
"""

from __future__ import annotations

from enum import Enum


class InvoiceHeaderInvoiceStatus(str, Enum):
    IN_PROGRESS = "IN_PROGRESS"
    REJECTED = "REJECTED"
    PARTIALLY_PAID = "PARTIALLY_PAID"
    PARTIALLY_DEDUCTED = "PARTIALLY_DEDUCTED"
    PAID = "PAID"
    DEDUCTED = "DEDUCTED"


class InvoiceHeaderInvoiceType(str, Enum):
    AP_INVENTORY = "AP_INVENTORY"
    OTHER = "OTHER"


class ItemIdentifierItemIdentifierName(str, Enum):
    ASIN = "ASIN"
    EXTERNAL_ID = "EXTERNAL_ID"
    SKU = "SKU"
    UPC = "UPC"
    EAN = "EAN"
    ISBN = "ISBN"


class LineItemContextLineItemType(str, Enum):
    GOODS = "GOODS"
    SERVICES = "SERVICES"
    OTHERS = "OTHERS"


class LineItemContextServiceChargeType(str, Enum):
    DAMAGE_ALLOWANCE = "DAMAGE_ALLOWANCE"
    PRICE_PROTECTION = "PRICE_PROTECTION"
    FBA_INVENTORY_STORAGE_FEE = "FBA_INVENTORY_STORAGE_FEE"
    OTHER = "OTHER"


class PartnerMetadataPartnerType(str, Enum):
    SELLER = "SELLER"
    VENDOR = "VENDOR"
    AMAZON = "AMAZON"


class RelatedIdentifierRelatedIdentifierName(str, Enum):
    PAYEE_CODE = "PAYEE_CODE"
    PURCHASE_ORDER_IDS = "PURCHASE_ORDER_IDS"
    SHORTAGE_INVOICE_IDS = "SHORTAGE_INVOICE_IDS"
    ASN_IDS = "ASN_IDS"
    RETURN_IDS = "RETURN_IDS"
    AGREEMENT_IDS = "AGREEMENT_IDS"
    PRODUCT_LINE = "PRODUCT_LINE"
    VENDOR_CODE = "VENDOR_CODE"
    UNIQUE_PAYMENT_IDS = "UNIQUE_PAYMENT_IDS"
    WAREHOUSE_ID = "WAREHOUSE_ID"


class VarianceReasonVarianceType(str, Enum):
    PQV = "PQV"
    PPV = "PPV"
    OTHER = "OTHER"


__all__ = [
    "InvoiceHeaderInvoiceStatus",
    "InvoiceHeaderInvoiceType",
    "ItemIdentifierItemIdentifierName",
    "LineItemContextLineItemType",
    "LineItemContextServiceChargeType",
    "PartnerMetadataPartnerType",
    "RelatedIdentifierRelatedIdentifierName",
    "VarianceReasonVarianceType",
]
