# Generated by `python -m amzn_selling_partner.stubgen`; do not edit.
from __future__ import annotations
from typing import Any, Literal, overload
from amzn_selling_partner.compile.resources import AsyncResource, SyncResource
from amzn_selling_partner.models.merchant_fulfillment import v0 as models
from amzn_selling_partner.runtime import NOT_GIVEN, NotGiven, Pagination, RequestOptions

class MerchantFulfillment(SyncResource):
    models: Any
    @overload
    def get_eligible_shipment_services(self, *, body: models.GetEligibleShipmentServicesRequest | models.GetEligibleShipmentServicesRequestDict, raw: Literal[False] = ..., paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.GetEligibleShipmentServicesResponse: ...
    @overload
    def get_eligible_shipment_services(self, *, body: models.GetEligibleShipmentServicesRequest | models.GetEligibleShipmentServicesRequestDict, raw: Literal[True], paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.GetEligibleShipmentServicesResponseDict: ...
    def get_eligible_shipment_services(self, *, body: models.GetEligibleShipmentServicesRequest | models.GetEligibleShipmentServicesRequestDict, raw: bool = False, paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.GetEligibleShipmentServicesResponse:
        """Returns a list of shipping service offers that satisfy the specified shipment request details."""
    @overload
    def get_shipment(self, *, shipment_id: str, raw: Literal[False] = ..., paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.GetShipmentResponse: ...
    @overload
    def get_shipment(self, *, shipment_id: str, raw: Literal[True], paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.GetShipmentResponseDict: ...
    def get_shipment(self, *, shipment_id: str, raw: bool = False, paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.GetShipmentResponse:
        """Returns the shipment information for an existing shipment."""
    @overload
    def cancel_shipment(self, *, shipment_id: str, raw: Literal[False] = ..., paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.CancelShipmentResponse: ...
    @overload
    def cancel_shipment(self, *, shipment_id: str, raw: Literal[True], paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.CancelShipmentResponseDict: ...
    def cancel_shipment(self, *, shipment_id: str, raw: bool = False, paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.CancelShipmentResponse:
        """Cancel the shipment indicated by the specified shipment identifier."""
    @overload
    def create_shipment(self, *, body: models.CreateShipmentRequest | models.CreateShipmentRequestDict, raw: Literal[False] = ..., paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.CreateShipmentResponse: ...
    @overload
    def create_shipment(self, *, body: models.CreateShipmentRequest | models.CreateShipmentRequestDict, raw: Literal[True], paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.CreateShipmentResponseDict: ...
    def create_shipment(self, *, body: models.CreateShipmentRequest | models.CreateShipmentRequestDict, raw: bool = False, paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.CreateShipmentResponse:
        """Create a shipment with the information provided."""
    @overload
    def get_additional_seller_inputs(self, *, body: models.GetAdditionalSellerInputsRequest | models.GetAdditionalSellerInputsRequestDict, raw: Literal[False] = ..., paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.GetAdditionalSellerInputsResponse: ...
    @overload
    def get_additional_seller_inputs(self, *, body: models.GetAdditionalSellerInputsRequest | models.GetAdditionalSellerInputsRequestDict, raw: Literal[True], paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.GetAdditionalSellerInputsResponseDict: ...
    def get_additional_seller_inputs(self, *, body: models.GetAdditionalSellerInputsRequest | models.GetAdditionalSellerInputsRequestDict, raw: bool = False, paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.GetAdditionalSellerInputsResponse:
        """Gets a list of additional seller inputs required for a ship method. This is generally used for international shipping."""

class AsyncMerchantFulfillment(AsyncResource):
    models: Any
    @overload
    async def get_eligible_shipment_services(self, *, body: models.GetEligibleShipmentServicesRequest | models.GetEligibleShipmentServicesRequestDict, raw: Literal[False] = ..., paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.GetEligibleShipmentServicesResponse: ...
    @overload
    async def get_eligible_shipment_services(self, *, body: models.GetEligibleShipmentServicesRequest | models.GetEligibleShipmentServicesRequestDict, raw: Literal[True], paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.GetEligibleShipmentServicesResponseDict: ...
    async def get_eligible_shipment_services(self, *, body: models.GetEligibleShipmentServicesRequest | models.GetEligibleShipmentServicesRequestDict, raw: bool = False, paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.GetEligibleShipmentServicesResponse:
        """Returns a list of shipping service offers that satisfy the specified shipment request details."""
    @overload
    async def get_shipment(self, *, shipment_id: str, raw: Literal[False] = ..., paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.GetShipmentResponse: ...
    @overload
    async def get_shipment(self, *, shipment_id: str, raw: Literal[True], paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.GetShipmentResponseDict: ...
    async def get_shipment(self, *, shipment_id: str, raw: bool = False, paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.GetShipmentResponse:
        """Returns the shipment information for an existing shipment."""
    @overload
    async def cancel_shipment(self, *, shipment_id: str, raw: Literal[False] = ..., paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.CancelShipmentResponse: ...
    @overload
    async def cancel_shipment(self, *, shipment_id: str, raw: Literal[True], paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.CancelShipmentResponseDict: ...
    async def cancel_shipment(self, *, shipment_id: str, raw: bool = False, paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.CancelShipmentResponse:
        """Cancel the shipment indicated by the specified shipment identifier."""
    @overload
    async def create_shipment(self, *, body: models.CreateShipmentRequest | models.CreateShipmentRequestDict, raw: Literal[False] = ..., paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.CreateShipmentResponse: ...
    @overload
    async def create_shipment(self, *, body: models.CreateShipmentRequest | models.CreateShipmentRequestDict, raw: Literal[True], paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.CreateShipmentResponseDict: ...
    async def create_shipment(self, *, body: models.CreateShipmentRequest | models.CreateShipmentRequestDict, raw: bool = False, paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.CreateShipmentResponse:
        """Create a shipment with the information provided."""
    @overload
    async def get_additional_seller_inputs(self, *, body: models.GetAdditionalSellerInputsRequest | models.GetAdditionalSellerInputsRequestDict, raw: Literal[False] = ..., paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.GetAdditionalSellerInputsResponse: ...
    @overload
    async def get_additional_seller_inputs(self, *, body: models.GetAdditionalSellerInputsRequest | models.GetAdditionalSellerInputsRequestDict, raw: Literal[True], paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.GetAdditionalSellerInputsResponseDict: ...
    async def get_additional_seller_inputs(self, *, body: models.GetAdditionalSellerInputsRequest | models.GetAdditionalSellerInputsRequestDict, raw: bool = False, paginate: Pagination | None | NotGiven = NOT_GIVEN, request_options: RequestOptions | None = None) -> models.GetAdditionalSellerInputsResponse:
        """Gets a list of additional seller inputs required for a ship method. This is generally used for international shipping."""
