"""Models for tokens v2021_03_01 (Selling Partner API for Tokens ).

Generated by codegen/ (oagen) from the pinned spec; do not edit by hand.
"""

from __future__ import annotations

from typing import Literal, TypeAlias

from pydantic import Field

from amzn_selling_partner.runtime._models import SpecModel

RestrictedResourceMethod: TypeAlias = Literal["GET", "PUT", "POST", "DELETE"]


class CreateRestrictedDataTokenRequest(SpecModel):
    """The request schema for the createRestrictedDataToken operation."""

    target_application: str | None = Field(default=None, alias="targetApplication")
    restricted_resources: list[RestrictedResource] = Field(alias="restrictedResources")


class CreateRestrictedDataTokenResponse(SpecModel):
    """The response schema for the createRestrictedDataToken operation."""

    restricted_data_token: str | None = Field(default=None, alias="restrictedDataToken")
    expires_in: int | None = Field(default=None, alias="expiresIn")


class Error(SpecModel):
    """An error response returned when the request is unsuccessful."""

    code: str
    message: str
    details: str | None = None


class ErrorList(SpecModel):
    """A list of error responses returned when a request is unsuccessful."""

    errors: list[Error] | None = None


class RestrictedResource(SpecModel):
    """Model of a restricted resource."""

    method: RestrictedResourceMethod
    path: str
    data_elements: list[str] | None = Field(default=None, alias="dataElements")


__all__ = [
    "CreateRestrictedDataTokenRequest",
    "CreateRestrictedDataTokenResponse",
    "Error",
    "ErrorList",
    "RestrictedResource",
    "RestrictedResourceMethod",
]
