# Auto-generated by oagen. Do not edit.

"""Models of notifications.B2bAnyOfferChangedNotification.

Auto-generated by oagen from the OpenAPI spec; do not edit by hand.
"""

from __future__ import annotations

from typing import Any

from pydantic import Field

from ..._base import SpecModel
from .enums import QuantityDiscountType


class B2bAnyOfferChangedNotification(SpecModel):
    """The notification response schema that comprises the entire JSON document for B2B_ANY_OFFER_CHANGED notification"""


class B2BAnyOfferChangedNotification(SpecModel):
    seller_id: str = Field(alias="SellerId")
    offer_change_trigger: OfferChangeTrigger = Field(alias="OfferChangeTrigger")
    summary: Summary = Field(alias="Summary")
    offers: list[Any] = Field(alias="Offers")


class BuyBoxPrice(SpecModel):
    condition: str = Field(alias="Condition")
    offer_type: str = Field(alias="OfferType")
    quantity_tier: int = Field(alias="QuantityTier")
    listing_price: ListingPrice = Field(alias="ListingPrice")
    discount_type: str | None = Field(default=None, alias="DiscountType")
    landed_price: LandedPrice | None = Field(default=None, alias="LandedPrice")
    shipping: Shipping | None = Field(default=None, alias="Shipping")
    points: Points | None = Field(default=None, alias="Points")
    seller_id: str | None = Field(default=None, alias="SellerId")


class LandedPrice(SpecModel):
    """ListingPrice + Shipping"""


class ListingPrice(SpecModel):
    """The price of the item"""


class LowestPrice(SpecModel):
    condition: str = Field(alias="Condition")
    fulfillment_channel: str = Field(alias="FulfillmentChannel")
    offer_type: str = Field(alias="OfferType")
    quantity_tier: int = Field(alias="QuantityTier")
    listing_price: ListingPrice = Field(alias="ListingPrice")
    discount_type: str | None = Field(default=None, alias="DiscountType")
    landed_price: LandedPrice | None = Field(default=None, alias="LandedPrice")
    shipping: Shipping | None = Field(default=None, alias="Shipping")
    points: Points | None = Field(default=None, alias="Points")


class MoneyType(SpecModel):
    amount: float = Field(alias="Amount")
    currency_code: str = Field(alias="CurrencyCode")


class NotificationMetadata(SpecModel):
    application_id: str = Field(alias="ApplicationId")
    subscription_id: str = Field(alias="SubscriptionId")
    publish_time: str = Field(alias="PublishTime")
    notification_id: str = Field(alias="NotificationId")


class NotificationResponse(SpecModel):
    notification_version: str = Field(alias="NotificationVersion")
    notification_type: str = Field(alias="NotificationType")
    payload_version: str = Field(alias="PayloadVersion")
    event_time: str = Field(alias="EventTime")
    notification_metadata: NotificationMetadata = Field(alias="NotificationMetadata")
    payload: Payload = Field(alias="Payload")


class Offer(SpecModel):
    seller_id: str = Field(alias="SellerId")
    sub_condition: str = Field(alias="SubCondition")
    shipping_time: ShippingTime = Field(alias="ShippingTime")
    listing_price: ListingPrice = Field(alias="ListingPrice")
    shipping: Shipping = Field(alias="Shipping")
    is_fulfilled_by_amazon: bool = Field(alias="IsFulfilledByAmazon")
    seller_feedback_rating: SellerFeedbackRating | None = Field(default=None, alias="SellerFeedbackRating")
    points: Points | None = Field(default=None, alias="Points")
    quantity_discount_price: list[QuantityDiscountPriceType] | None = Field(default=None, alias="QuantityDiscountPrice")
    ships_from: ShipsFrom | None = Field(default=None, alias="ShipsFrom")
    is_buy_box_winner: bool | None = Field(default=None, alias="IsBuyBoxWinner")
    condition_notes: str | None = Field(default=None, alias="ConditionNotes")
    prime_information: PrimeInformation | None = Field(default=None, alias="PrimeInformation")
    is_featured_merchant: bool | None = Field(default=None, alias="IsFeaturedMerchant")


class OfferChangeTrigger(SpecModel):
    """The event that caused the notification to be sent"""

    marketplace_id: str = Field(alias="MarketplaceId")
    asin: str = Field(alias="ASIN")
    item_condition: str = Field(alias="ItemCondition")
    time_of_offer_change: str = Field(alias="TimeOfOfferChange")


class OfferCount(SpecModel):
    condition: str = Field(alias="Condition")
    fulfillment_channel: str = Field(alias="FulfillmentChannel")
    offer_count: int = Field(alias="OfferCount")


class Payload(SpecModel):
    b2_b_any_offer_changed_notification: B2BAnyOfferChangedNotification = Field(alias="B2BAnyOfferChangedNotification")


class Points(SpecModel):
    points_number: int = Field(alias="PointsNumber")


class PrimeInformation(SpecModel):
    is_prime: bool = Field(alias="IsPrime")
    is_national_prime: bool = Field(alias="IsNationalPrime")


class QuantityDiscountPriceType(SpecModel):
    """Contains pricing information that includes special pricing when buying in bulk."""

    quantity_tier: int = Field(alias="QuantityTier")
    quantity_discount_type: QuantityDiscountType = Field(alias="QuantityDiscountType")
    listing_price: MoneyType = Field(alias="ListingPrice")


class SellerFeedbackRating(SpecModel):
    feedback_count: int = Field(alias="FeedbackCount")
    seller_positive_feedback_rating: float = Field(alias="SellerPositiveFeedbackRating")


class Shipping(SpecModel):
    """The shipping cost"""


class ShippingTime(SpecModel):
    minimum_hours: int | None = Field(default=None, alias="MinimumHours")
    maximum_hours: int | None = Field(default=None, alias="MaximumHours")
    availability_type: str | None = Field(default=None, alias="AvailabilityType")
    available_date: str | None = Field(default=None, alias="AvailableDate")


class ShipsFrom(SpecModel):
    country: str = Field(alias="Country")
    state: str | None = Field(default=None, alias="State")


class Summary(SpecModel):
    number_of_offers: list[Any] = Field(alias="NumberOfOffers")
    buy_box_eligible_offers: list[Any] = Field(alias="BuyBoxEligibleOffers")
    lowest_prices: list[Any] = Field(alias="LowestPrices")
    buy_box_prices: list[Any] = Field(alias="BuyBoxPrices")


__all__ = [
    "B2BAnyOfferChangedNotification",
    "B2bAnyOfferChangedNotification",
    "BuyBoxPrice",
    "LandedPrice",
    "ListingPrice",
    "LowestPrice",
    "MoneyType",
    "NotificationMetadata",
    "NotificationResponse",
    "Offer",
    "OfferChangeTrigger",
    "OfferCount",
    "Payload",
    "Points",
    "PrimeInformation",
    "QuantityDiscountPriceType",
    "QuantityDiscountType",
    "SellerFeedbackRating",
    "Shipping",
    "ShippingTime",
    "ShipsFrom",
    "Summary",
]
