# Auto-generated by oagen. Do not edit.

"""Enums of petstore_v2.

Auto-generated by oagen from the OpenAPI spec; do not edit by hand.
"""

from __future__ import annotations

from enum import Enum


class PetStatus(str, Enum):
    AVAILABLE = "available"
    PENDING = "pending"
    SOLD = "sold"


__all__ = [
    "PetStatus",
]
