# Auto-generated by oagen. Do not edit.

"""Enums of promotions_v2025_12_01.

Auto-generated by oagen from the OpenAPI spec; do not edit by hand.
"""

from __future__ import annotations

from enum import Enum


class BudgetType(str, Enum):
    AMOUNT = "AMOUNT"
    UNITS = "UNITS"

    __str__ = str.__str__


class ClaimCodeType(str, Enum):
    GROUP = "GROUP"
    INDIVIDUAL = "INDIVIDUAL"

    __str__ = str.__str__


class CouponType(str, Enum):
    STANDARD = "STANDARD"
    SUBSCRIBE_AND_SAVE = "SUBSCRIBE_AND_SAVE"
    REORDER_REWARDS = "REORDER_REWARDS"

    __str__ = str.__str__


class CustomerSegmentType(str, Enum):
    BRAND = "BRAND"
    PROGRAM = "PROGRAM"

    __str__ = str.__str__


class DiscountType(str, Enum):
    PERCENTAGE_OFF = "PERCENTAGE_OFF"
    AMOUNT_OFF = "AMOUNT_OFF"
    FREE_ITEM = "FREE_ITEM"

    __str__ = str.__str__


class FeeFrequency(str, Enum):
    ONE_TIME = "ONE_TIME"
    DAILY = "DAILY"

    __str__ = str.__str__


class GetPromotionResponseStatus(str, Enum):
    PROCESSING = "PROCESSING"
    UPCOMING = "UPCOMING"
    RUNNING = "RUNNING"
    EXPIRED = "EXPIRED"
    FAILED = "FAILED"
    CANCELLING = "CANCELLING"
    CANCELLED = "CANCELLED"

    __str__ = str.__str__


class IssueSeverity(str, Enum):
    ERROR = "ERROR"
    WARNING = "WARNING"

    __str__ = str.__str__


class ItemBenefitType(str, Enum):
    FIXED_PRICE = "FIXED_PRICE"
    DISCOUNTED_PRICE = "DISCOUNTED_PRICE"

    __str__ = str.__str__


class ItemIssueSeverity(str, Enum):
    ERROR = "ERROR"
    WARNING = "WARNING"

    __str__ = str.__str__


class LatestRevisionRevisionStatus(str, Enum):
    PROCESSING = "PROCESSING"
    FAILED = "FAILED"

    __str__ = str.__str__


class MerchandisingDisplayOnWebsite(str, Enum):
    ALLOWED = "ALLOWED"
    NOT_ALLOWED = "NOT_ALLOWED"

    __str__ = str.__str__


class PromotionBenefitStacking(str, Enum):
    ALLOWED = "ALLOWED"
    NOT_ALLOWED = "NOT_ALLOWED"

    __str__ = str.__str__


class PromotionIssueSeverity(str, Enum):
    ERROR = "ERROR"
    WARNING = "WARNING"

    __str__ = str.__str__


class PromotionSummaryStatus(str, Enum):
    PROCESSING = "PROCESSING"
    UPCOMING = "UPCOMING"
    RUNNING = "RUNNING"
    EXPIRED = "EXPIRED"
    FAILED = "FAILED"
    CANCELLING = "CANCELLING"
    CANCELLED = "CANCELLED"

    __str__ = str.__str__


class PromotionsV20251201IncludedData(str, Enum):
    ISSUES = "ISSUES"
    CUSTOMER_SEGMENTS = "CUSTOMER_SEGMENTS"

    __str__ = str.__str__


class PromotionsV20251201PromotionTypes(str, Enum):
    BASKET_BUILDING = "BASKET_BUILDING"
    DEAL = "DEAL"
    PRICE_DISCOUNT = "PRICE_DISCOUNT"
    COUPON = "COUPON"

    __str__ = str.__str__


class PromotionsV20251201Revision(str, Enum):
    LATEST = "LATEST"
    PUBLISHED = "PUBLISHED"
    ANY = "ANY"

    __str__ = str.__str__


class PromotionsV20251201Statuses(str, Enum):
    PROCESSING = "PROCESSING"
    UPCOMING = "UPCOMING"
    RUNNING = "RUNNING"
    EXPIRED = "EXPIRED"
    FAILED = "FAILED"
    CANCELLING = "CANCELLING"
    CANCELLED = "CANCELLED"

    __str__ = str.__str__


class PromotionType(str, Enum):
    BASKET_BUILDING = "BASKET_BUILDING"
    DEAL = "DEAL"
    PRICE_DISCOUNT = "PRICE_DISCOUNT"
    COUPON = "COUPON"

    __str__ = str.__str__


class QuantityThresholdType(str, Enum):
    AT_LEAST = "AT_LEAST"
    FOR_EACH = "FOR_EACH"

    __str__ = str.__str__


class SelectionType(str, Enum):
    CATALOG = "CATALOG"
    ITEMS = "ITEMS"

    __str__ = str.__str__


__all__ = [
    "BudgetType",
    "ClaimCodeType",
    "CouponType",
    "CustomerSegmentType",
    "DiscountType",
    "FeeFrequency",
    "GetPromotionResponseStatus",
    "IssueSeverity",
    "ItemBenefitType",
    "ItemIssueSeverity",
    "LatestRevisionRevisionStatus",
    "MerchandisingDisplayOnWebsite",
    "PromotionBenefitStacking",
    "PromotionIssueSeverity",
    "PromotionSummaryStatus",
    "PromotionType",
    "PromotionsV20251201IncludedData",
    "PromotionsV20251201PromotionTypes",
    "PromotionsV20251201Revision",
    "PromotionsV20251201Statuses",
    "QuantityThresholdType",
    "SelectionType",
]
