# Generated by `python -m spapi.stubgen`; do not edit.
from __future__ import annotations
import datetime
from typing import Any, Literal, TypedDict

from pydantic import BaseModel, Field

class Error(BaseModel):
    """Error response returned when the request is unsuccessful."""
    code: str
    message: str
    details: str | None = Field(default=None)
    def __init__(self, **data: Any) -> None: ...

class ErrorList(BaseModel):
    """A list of error responses returned when a request is unsuccessful."""
    errors: list[Error]
    def __init__(self, **data: Any) -> None: ...

class Report(BaseModel):
    """Detailed information about the report."""
    marketplace_ids: list[str] | None = Field(default=None, alias="marketplaceIds")
    report_id: str = Field(alias="reportId")
    report_type: str = Field(alias="reportType")
    data_start_time: datetime.datetime | None = Field(default=None, alias="dataStartTime")
    data_end_time: datetime.datetime | None = Field(default=None, alias="dataEndTime")
    report_schedule_id: str | None = Field(default=None, alias="reportScheduleId")
    created_time: datetime.datetime = Field(alias="createdTime")
    processing_status: Literal['CANCELLED', 'DONE', 'FATAL', 'IN_PROGRESS', 'IN_QUEUE'] = Field(alias="processingStatus")
    processing_start_time: datetime.datetime | None = Field(default=None, alias="processingStartTime")
    processing_end_time: datetime.datetime | None = Field(default=None, alias="processingEndTime")
    report_document_id: str | None = Field(default=None, alias="reportDocumentId")
    def __init__(self, **data: Any) -> None: ...

class CreateReportScheduleSpecification(BaseModel):
    """Information required to create the report schedule."""
    report_type: str = Field(alias="reportType")
    marketplace_ids: list[str] = Field(alias="marketplaceIds")
    report_options: ReportOptions | None = Field(default=None, alias="reportOptions")
    period: Literal['PT5M', 'PT15M', 'PT30M', 'PT1H', 'PT2H', 'PT4H', 'PT8H', 'PT12H', 'P1D', 'P2D', 'P3D', 'PT84H', 'P7D', 'P14D', 'P15D', 'P18D', 'P30D', 'P1M']
    next_report_creation_time: datetime.datetime | None = Field(default=None, alias="nextReportCreationTime")
    def __init__(self, **data: Any) -> None: ...

class CreateReportSpecification(BaseModel):
    """Information required to create the report."""
    report_options: ReportOptions | None = Field(default=None, alias="reportOptions")
    report_type: str = Field(alias="reportType")
    data_start_time: datetime.datetime | None = Field(default=None, alias="dataStartTime")
    data_end_time: datetime.datetime | None = Field(default=None, alias="dataEndTime")
    marketplace_ids: list[str] = Field(alias="marketplaceIds")
    def __init__(self, **data: Any) -> None: ...

class ReportSchedule(BaseModel):
    """Detailed information about a report schedule."""
    report_schedule_id: str = Field(alias="reportScheduleId")
    report_type: str = Field(alias="reportType")
    marketplace_ids: list[str] | None = Field(default=None, alias="marketplaceIds")
    report_options: ReportOptions | None = Field(default=None, alias="reportOptions")
    period: str
    next_report_creation_time: datetime.datetime | None = Field(default=None, alias="nextReportCreationTime")
    def __init__(self, **data: Any) -> None: ...

class ReportScheduleList(BaseModel):
    """A list of report schedules."""
    report_schedules: list[ReportSchedule] = Field(alias="reportSchedules")
    def __init__(self, **data: Any) -> None: ...

class CreateReportResponse(BaseModel):
    """The response schema."""
    report_id: str = Field(alias="reportId")
    def __init__(self, **data: Any) -> None: ...

class GetReportsResponse(BaseModel):
    """The response for the `getReports` operation."""
    reports: ReportList
    next_token: str | None = Field(default=None, alias="nextToken")
    def __init__(self, **data: Any) -> None: ...

class CreateReportScheduleResponse(BaseModel):
    """Response schema."""
    report_schedule_id: str = Field(alias="reportScheduleId")
    def __init__(self, **data: Any) -> None: ...

class ReportDocument(BaseModel):
    """Information required for the report document."""
    report_document_id: str = Field(alias="reportDocumentId")
    url: str
    compression_algorithm: Literal['GZIP'] | None = Field(default=None, alias="compressionAlgorithm")
    def __init__(self, **data: Any) -> None: ...

# raw-mode shapes (``raw=True``)

class ErrorDict(TypedDict, total=False):
    code: str
    message: str
    details: str

class ErrorListDict(TypedDict, total=False):
    errors: list[ErrorDict]

class ReportDict(TypedDict, total=False):
    marketplaceIds: list[str]
    reportId: str
    reportType: str
    dataStartTime: datetime.datetime
    dataEndTime: datetime.datetime
    reportScheduleId: str
    createdTime: datetime.datetime
    processingStatus: Literal['CANCELLED', 'DONE', 'FATAL', 'IN_PROGRESS', 'IN_QUEUE']
    processingStartTime: datetime.datetime
    processingEndTime: datetime.datetime
    reportDocumentId: str

class CreateReportScheduleSpecificationDict(TypedDict, total=False):
    reportType: str
    marketplaceIds: list[str]
    reportOptions: ReportOptions
    period: Literal['PT5M', 'PT15M', 'PT30M', 'PT1H', 'PT2H', 'PT4H', 'PT8H', 'PT12H', 'P1D', 'P2D', 'P3D', 'PT84H', 'P7D', 'P14D', 'P15D', 'P18D', 'P30D', 'P1M']
    nextReportCreationTime: datetime.datetime

class CreateReportSpecificationDict(TypedDict, total=False):
    reportOptions: ReportOptions
    reportType: str
    dataStartTime: datetime.datetime
    dataEndTime: datetime.datetime
    marketplaceIds: list[str]

class ReportScheduleDict(TypedDict, total=False):
    reportScheduleId: str
    reportType: str
    marketplaceIds: list[str]
    reportOptions: ReportOptions
    period: str
    nextReportCreationTime: datetime.datetime

class ReportScheduleListDict(TypedDict, total=False):
    reportSchedules: list[ReportScheduleDict]

class CreateReportResponseDict(TypedDict, total=False):
    reportId: str

class GetReportsResponseDict(TypedDict, total=False):
    reports: ReportList
    nextToken: str

class CreateReportScheduleResponseDict(TypedDict, total=False):
    reportScheduleId: str

class ReportDocumentDict(TypedDict, total=False):
    reportDocumentId: str
    url: str
    compressionAlgorithm: Literal['GZIP']

# type aliases
ReportList = list[Report]
ReportOptions = dict[str, str]
