# Auto-generated by oagen. Do not edit.

"""Models of product_pricing_v2022_05_01.

Auto-generated by oagen from the OpenAPI spec; do not edit by hand.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import Field

from .._base import SpecModel
from .enums import (
    CompetitiveSummaryIncludedData,
    Condition,
    FeaturedOfferSegmentCustomerMembership,
    FulfillmentType,
    HttpMethod,
    OfferSubCondition,
    PrimeDetailsEligibility,
    SegmentedFeaturedOfferSubCondition,
)


class AmountThreshold(SpecModel):
    """Amount-based purchase conditions for basket building promotions. Customers must spend a minimum dollar amount."""

    type_: str = Field(alias="type")
    currency: MoneyType


class BatchRequest(SpecModel):
    """The common properties for individual requests within a batch."""

    uri: str
    method: HttpMethod
    body: Any | None = None
    headers: dict[str, str] | None = None


class BatchResponse(SpecModel):
    """The common properties for responses to individual requests within a batch."""

    headers: dict[str, str]
    status: HttpStatusLine


class CompetitiveSummaryBatchRequest(SpecModel):
    """The `competitiveSummary` batch request data."""

    requests: list[CompetitiveSummaryRequest]


class CompetitiveSummaryBatchResponse(SpecModel):
    """The response schema for the `competitiveSummaryBatch` operation."""

    responses: list[CompetitiveSummaryResponse]


class CompetitiveSummaryRequest(SpecModel):
    """An individual `competitiveSummary` request for an ASIN and `marketplaceId`."""

    asin: str
    marketplace_id: str = Field(alias="marketplaceId")
    included_data: list[CompetitiveSummaryIncludedData] = Field(alias="includedData")
    method: HttpMethod
    uri: str
    lowest_priced_offers_inputs: list[LowestPricedOffersInput] | None = Field(default=None, alias="lowestPricedOffersInputs")


class CompetitiveSummaryResponse(SpecModel):
    """The response for the individual `competitiveSummary` request in the batch operation."""

    status: HttpStatusLine
    body: CompetitiveSummaryResponseBody


class CompetitiveSummaryResponseBody(SpecModel):
    """The `competitiveSummaryResponse` body for a requested ASIN and `marketplaceId`."""

    asin: str
    marketplace_id: str = Field(alias="marketplaceId")
    featured_buying_options: list[FeaturedBuyingOption] | None = Field(default=None, alias="featuredBuyingOptions")
    lowest_priced_offers: list[LowestPricedOffer] | None = Field(default=None, alias="lowestPricedOffers")
    reference_prices: list[ReferencePrice] | None = Field(default=None, alias="referencePrices")
    similar_items: list[SimilarItems] | None = Field(default=None, alias="similarItems")
    errors: list[Error] | None = None


class Error(SpecModel):
    """Error response returned when the request is unsuccessful."""

    code: str
    message: str
    details: str | None = None


class Errors(SpecModel):
    """A list of error responses returned when a request is unsuccessful."""

    errors: list[Error]


class FeaturedBuyingOption(SpecModel):
    """Describes a featured buying option, which includes a list of segmented featured offers for a particular item condition."""

    buying_option_type: Literal["New"] = Field(alias="buyingOptionType")
    segmented_featured_offers: list[SegmentedFeaturedOffer] = Field(alias="segmentedFeaturedOffers")


class FeaturedOffer(SpecModel):
    """Schema for `currentFeaturedOffer` or `competingFeaturedOffer`."""

    offer_identifier: OfferIdentifier = Field(alias="offerIdentifier")
    condition: Condition | None = None
    price: Price | None = None


class FeaturedOfferExpectedPrice(SpecModel):
    """The item price at or below which the target offer may be featured."""

    listing_price: MoneyType = Field(alias="listingPrice")
    points: Points | None = None


class FeaturedOfferExpectedPriceRequest(SpecModel):
    """An individual FOEP request for a particular SKU."""

    uri: str
    method: HttpMethod
    marketplace_id: str = Field(alias="marketplaceId")
    sku: str
    body: Any | None = None
    headers: dict[str, str] | None = None
    segment: Segment | None = None


class FeaturedOfferExpectedPriceRequestParams(SpecModel):
    """The parameters for an individual request."""

    marketplace_id: str = Field(alias="marketplaceId")
    sku: str
    segment: Segment | None = None


class FeaturedOfferExpectedPriceResponse(SpecModel):
    """Schema for an individual FOEP response."""

    headers: dict[str, str]
    status: HttpStatusLine
    request: FeaturedOfferExpectedPriceRequestParams
    body: FeaturedOfferExpectedPriceResponseBody | None = None


class FeaturedOfferExpectedPriceResponseBody(SpecModel):
    """The FOEP response data for a requested SKU."""

    offer_identifier: OfferIdentifier | None = Field(default=None, alias="offerIdentifier")
    featured_offer_expected_price_results: list[FeaturedOfferExpectedPriceResult] | None = Field(
        default=None, alias="featuredOfferExpectedPriceResults"
    )
    errors: list[Error] | None = None


class FeaturedOfferExpectedPriceResult(SpecModel):
    """The FOEP result data for the requested offer."""

    result_status: str = Field(alias="resultStatus")
    featured_offer_expected_price: FeaturedOfferExpectedPrice | None = Field(default=None, alias="featuredOfferExpectedPrice")
    competing_featured_offer: FeaturedOffer | None = Field(default=None, alias="competingFeaturedOffer")
    current_featured_offer: FeaturedOffer | None = Field(default=None, alias="currentFeaturedOffer")


class FeaturedOfferSegment(SpecModel):
    """Describes the segment in which the offer is featured."""

    customer_membership: FeaturedOfferSegmentCustomerMembership = Field(alias="customerMembership")
    segment_details: SegmentDetails = Field(alias="segmentDetails")


class GetFeaturedOfferExpectedPriceBatchRequest(SpecModel):
    """The request body for the `getFeaturedOfferExpectedPriceBatch` operation."""

    requests: list[FeaturedOfferExpectedPriceRequest] | None = None


class GetFeaturedOfferExpectedPriceBatchResponse(SpecModel):
    """The response schema for the `getFeaturedOfferExpectedPriceBatch` operation."""

    responses: list[FeaturedOfferExpectedPriceResponse] | None = None


class HttpStatusLine(SpecModel):
    """The HTTP status line associated with the response for an individual request within a batch. For more information, refer to [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html)."""

    status_code: int | None = Field(default=None, alias="statusCode")
    reason_phrase: str | None = Field(default=None, alias="reasonPhrase")


class Item(SpecModel):
    """A similar item for the specified ASIN `marketplaceId` combination."""

    asin: str


class LowestPricedOffer(SpecModel):
    """Describes the lowest priced offers for the specified item condition and offer type."""

    lowest_priced_offers_input: LowestPricedOffersInput = Field(alias="lowestPricedOffersInput")
    offers: list[Offer]


class LowestPricedOffersInput(SpecModel):
    """The input required for building `LowestPricedOffers` data in the response."""

    item_condition: Condition = Field(alias="itemCondition")
    offer_type: Literal["Consumer"] = Field(alias="offerType")


class MoneyType(SpecModel):
    """Currency type and monetary value schema to demonstrate pricing information."""

    currency_code: str | None = Field(default=None, alias="currencyCode")
    amount: float | None = None


class Offer(SpecModel):
    """The offer data of a product."""

    seller_id: str = Field(alias="sellerId")
    condition: Condition
    fulfillment_type: FulfillmentType = Field(alias="fulfillmentType")
    listing_price: MoneyType = Field(alias="listingPrice")
    sub_condition: OfferSubCondition | None = Field(default=None, alias="subCondition")
    shipping_options: list[ShippingOption] | None = Field(default=None, alias="shippingOptions")
    points: Points | None = None
    prime_details: PrimeDetails | None = Field(default=None, alias="primeDetails")
    promotions: list[Promotion] | None = None


class OfferIdentifier(SpecModel):
    """Identifies an offer from a particular seller for a specified ASIN."""

    marketplace_id: str = Field(alias="marketplaceId")
    asin: str
    seller_id: str | None = Field(default=None, alias="sellerId")
    sku: str | None = None
    fulfillment_type: FulfillmentType | None = Field(default=None, alias="fulfillmentType")


class Points(SpecModel):
    """The number of Amazon Points that are offered with the purchase of an item and the monetary value of these points."""

    points_number: int | None = Field(default=None, alias="pointsNumber")
    points_monetary_value: MoneyType | None = Field(default=None, alias="pointsMonetaryValue")


class PostalCode(SpecModel):
    """Postal code value with country code"""

    country_code: str | None = Field(default=None, alias="countryCode")
    value: str | None = None


class Price(SpecModel):
    """The schema for item's price information, including listing price, shipping price, and Amazon Points."""

    listing_price: MoneyType = Field(alias="listingPrice")
    shipping_price: MoneyType | None = Field(default=None, alias="shippingPrice")
    points: Points | None = None


class PrimeDetails(SpecModel):
    """Amazon Prime details."""

    eligibility: PrimeDetailsEligibility


class Promotion(SpecModel):
    """A promotion applicable to the offer."""

    promotion_type: str = Field(alias="promotionType")
    promotion_savings: PromotionSavings = Field(alias="promotionSavings")
    purchase_requirements: PurchaseRequirements | None = Field(default=None, alias="purchaseRequirements")


class PromotionDiscount(SpecModel):
    """Discount details applied by the promotion."""

    type_: str | None = Field(default=None, alias="type")
    amount_off: MoneyType | None = Field(default=None, alias="amountOff")
    percent_off: float | None = Field(default=None, alias="percentOff")


class PromotionSavings(SpecModel):
    """Details about the savings applied by the promotion."""

    discount: PromotionDiscount | None = None
    discounted_price: MoneyType | None = Field(default=None, alias="discountedPrice")


class PurchaseCondition(SpecModel):
    """Specifies minimum purchase requirements using quantity-based or amount-based conditions for basket building promotions. Used in purchase requirements to specify conditions within those configurations. Exactly one of quantityThreshold or amountThreshold must be specified."""

    quantity_threshold: QuantityThreshold | None = Field(default=None, alias="quantityThreshold")
    amount_threshold: AmountThreshold | None = Field(default=None, alias="amountThreshold")


class PurchaseRequirements(SpecModel):
    """Purchase requirements that customers must meet to qualify for basket building promotions. Contains the purchase condition (how much to buy). Represents the 'Buy X' portion of Buy X Get Y promotions."""

    condition: PurchaseCondition | None = None


class QuantityThreshold(SpecModel):
    """Quantity-based purchase conditions for basket building promotions."""

    type_: str = Field(alias="type")
    quantity: int


class ReferencePrice(SpecModel):
    """The reference price for the specified ASIN `marketplaceId` combination."""

    name: str
    price: MoneyType


class SampleLocation(SpecModel):
    """Information about a location. It uses a postal code to identify the location."""

    postal_code: PostalCode | None = Field(default=None, alias="postalCode")


class Segment(SpecModel):
    """Input segment for featured offer expected price. The segment contains the location information for which featured offer expected price is requested."""

    segment_details: SegmentDetails | None = Field(default=None, alias="segmentDetails")


class SegmentDetails(SpecModel):
    """The details about the segment. The FeaturedOfferExpectedPrice API uses only the sampleLocation portion as input."""

    glance_view_weight_percentage: float | None = Field(default=None, alias="glanceViewWeightPercentage")
    sample_location: SampleLocation | None = Field(default=None, alias="sampleLocation")


class SegmentedFeaturedOffer(SpecModel):
    """A product offer with segment information indicating where it's featured."""

    seller_id: str = Field(alias="sellerId")
    condition: Condition
    fulfillment_type: FulfillmentType = Field(alias="fulfillmentType")
    listing_price: MoneyType = Field(alias="listingPrice")
    featured_offer_segments: list[FeaturedOfferSegment] = Field(alias="featuredOfferSegments")
    sub_condition: SegmentedFeaturedOfferSubCondition | None = Field(default=None, alias="subCondition")
    shipping_options: list[ShippingOption] | None = Field(default=None, alias="shippingOptions")
    points: Points | None = None
    prime_details: PrimeDetails | None = Field(default=None, alias="primeDetails")
    promotions: list[Promotion] | None = None


class ShippingOption(SpecModel):
    """The shipping option available for the offer."""

    shipping_option_type: Literal["DEFAULT"] = Field(alias="shippingOptionType")
    price: MoneyType


class SimilarItems(SpecModel):
    """The summary of similar items for the specified ASIN `marketplaceId` combination."""

    items: list[Item] | None = None


__all__ = [
    "AmountThreshold",
    "BatchRequest",
    "BatchResponse",
    "CompetitiveSummaryBatchRequest",
    "CompetitiveSummaryBatchResponse",
    "CompetitiveSummaryRequest",
    "CompetitiveSummaryResponse",
    "CompetitiveSummaryResponseBody",
    "Error",
    "Errors",
    "FeaturedBuyingOption",
    "FeaturedOffer",
    "FeaturedOfferExpectedPrice",
    "FeaturedOfferExpectedPriceRequest",
    "FeaturedOfferExpectedPriceRequestParams",
    "FeaturedOfferExpectedPriceResponse",
    "FeaturedOfferExpectedPriceResponseBody",
    "FeaturedOfferExpectedPriceResult",
    "FeaturedOfferSegment",
    "GetFeaturedOfferExpectedPriceBatchRequest",
    "GetFeaturedOfferExpectedPriceBatchResponse",
    "HttpStatusLine",
    "Item",
    "LowestPricedOffer",
    "LowestPricedOffersInput",
    "MoneyType",
    "Offer",
    "OfferIdentifier",
    "Points",
    "PostalCode",
    "Price",
    "PrimeDetails",
    "Promotion",
    "PromotionDiscount",
    "PromotionSavings",
    "PurchaseCondition",
    "PurchaseRequirements",
    "QuantityThreshold",
    "ReferencePrice",
    "SampleLocation",
    "Segment",
    "SegmentDetails",
    "SegmentedFeaturedOffer",
    "ShippingOption",
    "SimilarItems",
]
