/** The Python emitter: an oagen `Emitter` bound to one API version. */
import type { ApiSpec, Emitter, EmitterContext, Enum, GeneratedFile, Model, Service } from '@workos/oagen';
import { generateModels } from './models.js';
import { generateResources } from './resources.js';
import type { EmitterOptions } from './options.js';
import { pascalCase } from './naming.js';

export const FILE_HEADER = '# Generated by codegen/ (oagen). Do not edit by hand.';

/** Class name of the resource for an API version: `orders` + `v0` -> `OrdersV0`. */
export function resourceClassName(api: string, version: string): string {
  return pascalCase(api) + pascalCase(version.replace(/^v/, 'V'));
}

/**
 * Per-spec settings travel through oagen's option bag: the driver passes them
 * to `generateFiles({ emitterOptions })`, `oagen.config.ts` declares them under
 * `emitterOptions.python`, and the CLI hands the active language's bag to the
 * emitter as `ctx.emitterOptions`.
 */
export function optionsOf(ctx: EmitterContext): EmitterOptions {
  const opts = ctx.emitterOptions as Partial<EmitterOptions> | undefined;
  for (const key of ['packageName', 'runtimePackage', 'api', 'version'] as const) {
    if (typeof opts?.[key] !== 'string') throw new Error(`python emitter: emitterOptions.${key} is required (see codegen/oagen.config.ts)`);
  }
  return { amazon: false, extras: {}, ...opts } as EmitterOptions;
}

/** The `python` target. */
export const pythonEmitter: Emitter = {
  language: 'python',
  generateModels(_models: Model[], ctx: EmitterContext): GeneratedFile[] {
    return generateModels(ctx.spec, ctx, optionsOf(ctx));
  },
  generateEnums(_enums: Enum[], _ctx: EmitterContext): GeneratedFile[] {
    return []; // enums live in the models module
  },
  generateResources(_services: Service[], ctx: EmitterContext): GeneratedFile[] {
    const opts = optionsOf(ctx);
    return generateResources(ctx.spec, ctx, opts, resourceClassName(opts.api, opts.version));
  },
  generateClient(_spec: ApiSpec, _ctx: EmitterContext): GeneratedFile[] {
    return []; // the driver writes apis.py once for every API version
  },
  generateErrors(_ctx: EmitterContext): GeneratedFile[] {
    return []; // hand-written in runtime/_errors.py
  },
  generateTests(_spec: ApiSpec, _ctx: EmitterContext): GeneratedFile[] {
    return [];
  },
  fileHeader(): string {
    return FILE_HEADER;
  },
};
