"""Operations of notifications v1 (Selling Partner API for Notifications).

Generated by codegen/ (oagen) from the pinned spec; do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from amzn_selling_partner.models.notifications import v1 as models
from amzn_selling_partner.runtime._op import Body, Op, json_decoder, path, query
from amzn_selling_partner.runtime._pagination import AsyncPage, Pagination, SyncPage
from amzn_selling_partner.runtime._resources import AsyncResource, SyncResource
from amzn_selling_partner.runtime._throttle import RateLimit
from amzn_selling_partner.runtime._types import NOT_GIVEN, NotGiven, RequestOptions

_op_get_subscriptions_d1 = json_decoder(lambda: models.GetSubscriptionsResponse)
_op_get_subscriptions = Op(
    key="notifications.v1.getSubscriptions",
    name="get_subscriptions",
    operation_id="getSubscriptions",
    api="notifications",
    version="v1",
    method="GET",
    path="/notifications/v1/subscriptions",
    url_template="/notifications/v1/subscriptions",
    path_params=(),
    query_params=(
        query("notification_types", "notificationTypes", required=True, kind="array", explode=False),
        query("payload_version", "payloadVersion"),
        query("page_size", "pageSize"),
        query("next_token", "nextToken"),
    ),
    header_params=(),
    default_decoder=_op_get_subscriptions_d1,
    error_decoders={
        400: _op_get_subscriptions_d1,
        403: _op_get_subscriptions_d1,
        404: _op_get_subscriptions_d1,
        413: _op_get_subscriptions_d1,
        415: _op_get_subscriptions_d1,
        429: _op_get_subscriptions_d1,
        500: _op_get_subscriptions_d1,
        503: _op_get_subscriptions_d1,
    },
    default_error=_op_get_subscriptions_d1,
    rate_limit=RateLimit(rate=1, burst=5),
    pagination=Pagination(
        items_path="payload.subscriptions",
        next_token_path="payload.nextToken",
        next_token_param="nextToken",
        drop_params_on_next=True,
        source="plugin",
    ),
    doc="Returns information about subscriptions of the specified notification type. You can use this API to retrieve all subscriptions when multiple subscriptions exist for a notification type (for example, when using filter expressions).\n\nThe operation returns all subscriptions for the caller's party.\n\n`payloadVersion` is an optional parameter. When you do not provide `payloadVersion`, the operation returns subscriptions across all payload versions.\n\n**Usage Plan:**\n\n| Rate (requests per second) | Burst |\n| ---- | ---- |\n| 1 | 5 |\n\nThe `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).\n\nGET /notifications/v1/subscriptions",
)

_op_get_subscription_d1 = json_decoder(lambda: models.GetSubscriptionResponse)
_op_get_subscription = Op(
    key="notifications.v1.getSubscription",
    name="get_subscription",
    operation_id="getSubscription",
    api="notifications",
    version="v1",
    method="GET",
    path="/notifications/v1/subscriptions/{notificationType}",
    url_template="/notifications/v1/subscriptions/{}",
    path_params=(path("notification_type", "notificationType"),),
    query_params=(query("payload_version", "payloadVersion"),),
    header_params=(),
    default_decoder=_op_get_subscription_d1,
    error_decoders={
        400: _op_get_subscription_d1,
        403: _op_get_subscription_d1,
        404: _op_get_subscription_d1,
        413: _op_get_subscription_d1,
        415: _op_get_subscription_d1,
        429: _op_get_subscription_d1,
        500: _op_get_subscription_d1,
        503: _op_get_subscription_d1,
    },
    default_error=_op_get_subscription_d1,
    rate_limit=RateLimit(rate=1, burst=5),
    doc="Returns information about subscription of the specified notification type and payload version. `payloadVersion` is an optional parameter. When you do not provide `payloadVersion`, the operation returns the latest payload version subscription's information. You can use this API to get subscription information when you do not have a subscription identifier.\n\n**Usage Plan:**\n\n| Rate (requests per second) | Burst |\n| ---- | ---- |\n| 1 | 5 |\n\nThe `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).\n\nGET /notifications/v1/subscriptions/{notificationType}",
)

_op_create_subscription_d1 = json_decoder(lambda: models.CreateSubscriptionResponse)
_op_create_subscription = Op(
    key="notifications.v1.createSubscription",
    name="create_subscription",
    operation_id="createSubscription",
    api="notifications",
    version="v1",
    method="POST",
    path="/notifications/v1/subscriptions/{notificationType}",
    url_template="/notifications/v1/subscriptions/{}",
    path_params=(path("notification_type", "notificationType"),),
    query_params=(),
    header_params=(),
    body=Body("json", "application/json", required=True),
    default_decoder=_op_create_subscription_d1,
    error_decoders={
        400: _op_create_subscription_d1,
        403: _op_create_subscription_d1,
        404: _op_create_subscription_d1,
        409: _op_create_subscription_d1,
        413: _op_create_subscription_d1,
        415: _op_create_subscription_d1,
        429: _op_create_subscription_d1,
        500: _op_create_subscription_d1,
        503: _op_create_subscription_d1,
    },
    default_error=_op_create_subscription_d1,
    rate_limit=RateLimit(rate=1, burst=5),
    doc="Creates a subscription for the specified notification type to be delivered to the specified destination. Before you can subscribe, you must first create the destination by calling the `createDestination` operation. If the notification type that you specify supports multiple payload versions, you can use this operation to subscribe to a different payload version if you already have an existing subscription for a different payload version.\n\n**Usage Plan:**\n\n| Rate (requests per second) | Burst |\n| ---- | ---- |\n| 1 | 5 |\n\nThe `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).\n\nPOST /notifications/v1/subscriptions/{notificationType}",
)

_op_get_subscription_by_id_d1 = json_decoder(lambda: models.GetSubscriptionByIdResponse)
_op_get_subscription_by_id_d2 = json_decoder(lambda: models.GetSubscriptionResponse)
_op_get_subscription_by_id = Op(
    key="notifications.v1.getSubscriptionById",
    name="get_subscription_by_id",
    operation_id="getSubscriptionById",
    api="notifications",
    version="v1",
    method="GET",
    path="/notifications/v1/subscriptions/{notificationType}/{subscriptionId}",
    url_template="/notifications/v1/subscriptions/{}/{}",
    path_params=(
        path("notification_type", "notificationType"),
        path("subscription_id", "subscriptionId"),
    ),
    query_params=(),
    header_params=(),
    default_decoder=_op_get_subscription_by_id_d1,
    error_decoders={
        400: _op_get_subscription_by_id_d1,
        403: _op_get_subscription_by_id_d1,
        404: _op_get_subscription_by_id_d2,
        409: _op_get_subscription_by_id_d1,
        413: _op_get_subscription_by_id_d1,
        415: _op_get_subscription_by_id_d1,
        429: _op_get_subscription_by_id_d1,
        500: _op_get_subscription_by_id_d1,
        503: _op_get_subscription_by_id_d1,
    },
    default_error=_op_get_subscription_by_id_d1,
    rate_limit=RateLimit(rate=1, burst=5),
    doc="Returns information about a subscription for the specified notification type. The `getSubscriptionById` operation is grantless. For more information, refer to [Grantless Operations](https://developer-docs.amazon.com/sp-api/docs/grantless-operations) in the Selling Partner API Developer Guide.\n\n**Usage Plan:**\n\n| Rate (requests per second) | Burst |\n| ---- | ---- |\n| 1 | 5 |\n\nThe `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).\n\nGET /notifications/v1/subscriptions/{notificationType}/{subscriptionId}",
)

_op_delete_subscription_by_id_d1 = json_decoder(lambda: models.DeleteSubscriptionByIdResponse)
_op_delete_subscription_by_id = Op(
    key="notifications.v1.deleteSubscriptionById",
    name="delete_subscription_by_id",
    operation_id="deleteSubscriptionById",
    api="notifications",
    version="v1",
    method="DELETE",
    path="/notifications/v1/subscriptions/{notificationType}/{subscriptionId}",
    url_template="/notifications/v1/subscriptions/{}/{}",
    path_params=(
        path("notification_type", "notificationType"),
        path("subscription_id", "subscriptionId"),
    ),
    query_params=(),
    header_params=(),
    default_decoder=_op_delete_subscription_by_id_d1,
    error_decoders={
        400: _op_delete_subscription_by_id_d1,
        403: _op_delete_subscription_by_id_d1,
        404: _op_delete_subscription_by_id_d1,
        409: _op_delete_subscription_by_id_d1,
        413: _op_delete_subscription_by_id_d1,
        415: _op_delete_subscription_by_id_d1,
        429: _op_delete_subscription_by_id_d1,
        500: _op_delete_subscription_by_id_d1,
        503: _op_delete_subscription_by_id_d1,
    },
    default_error=_op_delete_subscription_by_id_d1,
    rate_limit=RateLimit(rate=1, burst=5),
    doc="Deletes the subscription indicated by the subscription identifier and notification type that you specify. The subscription identifier can be for any subscription associated with your application. After you successfully call this operation, notifications will stop being sent for the associated subscription. The `deleteSubscriptionById` operation is grantless. For more information, refer to [Grantless Operations](https://developer-docs.amazon.com/sp-api/docs/grantless-operations) in the Selling Partner API Developer Guide.\n\n**Usage Plan:**\n\n| Rate (requests per second) | Burst |\n| ---- | ---- |\n| 1 | 5 |\n\nThe `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).\n\nDELETE /notifications/v1/subscriptions/{notificationType}/{subscriptionId}",
)

_op_send_test_notification_d1 = json_decoder(lambda: models.SendTestNotificationResponse)
_op_send_test_notification = Op(
    key="notifications.v1.sendTestNotification",
    name="send_test_notification",
    operation_id="sendTestNotification",
    api="notifications",
    version="v1",
    method="POST",
    path="/notifications/v1/subscriptions/{notificationType}/testNotification",
    url_template="/notifications/v1/subscriptions/{}/testNotification",
    path_params=(path("notification_type", "notificationType"),),
    query_params=(),
    header_params=(),
    body=Body("json", "application/json", required=True),
    default_decoder=_op_send_test_notification_d1,
    error_decoders={
        400: _op_send_test_notification_d1,
        403: _op_send_test_notification_d1,
        404: _op_send_test_notification_d1,
        409: _op_send_test_notification_d1,
        413: _op_send_test_notification_d1,
        415: _op_send_test_notification_d1,
        429: _op_send_test_notification_d1,
        500: _op_send_test_notification_d1,
        503: _op_send_test_notification_d1,
    },
    default_error=_op_send_test_notification_d1,
    rate_limit=RateLimit(rate=1, burst=5),
    doc='Sends a mock notification of the specified type to your SQS. The `sendTestNotification` API is grantless. For more information, see "Grantless operations" in the Selling Partner API Developer Guide.\n\n**Usage Plan:**\n\n| Rate (requests per second) | Burst |\n| ---- | ---- |\n| 1 | 5 |\n\nFor more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation. This is a sandbox-only operation and must be directed to a sandbox endpoint. Refer to [Selling Partner API sandbox](https://developer-docs.amazon.com/sp-api/docs/the-selling-partner-api-sandbox) for more information.\n\nPOST /notifications/v1/subscriptions/{notificationType}/testNotification',
)

_op_get_destinations_d1 = json_decoder(lambda: models.GetDestinationsResponse)
_op_get_destinations = Op(
    key="notifications.v1.getDestinations",
    name="get_destinations",
    operation_id="getDestinations",
    api="notifications",
    version="v1",
    method="GET",
    path="/notifications/v1/destinations",
    url_template="/notifications/v1/destinations",
    path_params=(),
    query_params=(),
    header_params=(),
    default_decoder=_op_get_destinations_d1,
    error_decoders={
        400: _op_get_destinations_d1,
        403: _op_get_destinations_d1,
        404: _op_get_destinations_d1,
        409: _op_get_destinations_d1,
        413: _op_get_destinations_d1,
        415: _op_get_destinations_d1,
        429: _op_get_destinations_d1,
        500: _op_get_destinations_d1,
        503: _op_get_destinations_d1,
    },
    default_error=_op_get_destinations_d1,
    rate_limit=RateLimit(rate=1, burst=5),
    doc="Returns information about all destinations. The `getDestinations` operation is grantless. For more information, refer to [Grantless Operations](https://developer-docs.amazon.com/sp-api/docs/grantless-operations) in the Selling Partner API Developer Guide.\n\n**Usage Plan:**\n\n| Rate (requests per second) | Burst |\n| ---- | ---- |\n| 1 | 5 |\n\nThe `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).\n\nGET /notifications/v1/destinations",
)

_op_create_destination_d1 = json_decoder(lambda: models.CreateDestinationResponse)
_op_create_destination = Op(
    key="notifications.v1.createDestination",
    name="create_destination",
    operation_id="createDestination",
    api="notifications",
    version="v1",
    method="POST",
    path="/notifications/v1/destinations",
    url_template="/notifications/v1/destinations",
    path_params=(),
    query_params=(),
    header_params=(),
    body=Body("json", "application/json", required=True),
    default_decoder=_op_create_destination_d1,
    error_decoders={
        400: _op_create_destination_d1,
        403: _op_create_destination_d1,
        404: _op_create_destination_d1,
        409: _op_create_destination_d1,
        413: _op_create_destination_d1,
        415: _op_create_destination_d1,
        429: _op_create_destination_d1,
        500: _op_create_destination_d1,
        503: _op_create_destination_d1,
    },
    default_error=_op_create_destination_d1,
    rate_limit=RateLimit(rate=1, burst=5),
    doc="Creates a destination resource to receive notifications. The `createDestination` operation is grantless. For more information, refer to [Grantless Operations](https://developer-docs.amazon.com/sp-api/docs/grantless-operations) in the Selling Partner API Developer Guide.\n\n**Usage Plan:**\n\n| Rate (requests per second) | Burst |\n| ---- | ---- |\n| 1 | 5 |\n\nThe `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).\n\nPOST /notifications/v1/destinations",
)

_op_get_destination_d1 = json_decoder(lambda: models.GetDestinationResponse)
_op_get_destination = Op(
    key="notifications.v1.getDestination",
    name="get_destination",
    operation_id="getDestination",
    api="notifications",
    version="v1",
    method="GET",
    path="/notifications/v1/destinations/{destinationId}",
    url_template="/notifications/v1/destinations/{}",
    path_params=(path("destination_id", "destinationId"),),
    query_params=(),
    header_params=(),
    default_decoder=_op_get_destination_d1,
    error_decoders={
        400: _op_get_destination_d1,
        403: _op_get_destination_d1,
        404: _op_get_destination_d1,
        409: _op_get_destination_d1,
        413: _op_get_destination_d1,
        415: _op_get_destination_d1,
        429: _op_get_destination_d1,
        500: _op_get_destination_d1,
        503: _op_get_destination_d1,
    },
    default_error=_op_get_destination_d1,
    rate_limit=RateLimit(rate=1, burst=5),
    doc="Returns information about the destination that you specify. The `getDestination` operation is grantless. For more information, refer to [Grantless Operations](https://developer-docs.amazon.com/sp-api/docs/grantless-operations) in the Selling Partner API Developer Guide.\n\n**Usage Plan:**\n\n| Rate (requests per second) | Burst |\n| ---- | ---- |\n| 1 | 5 |\n\nThe `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).\n\nGET /notifications/v1/destinations/{destinationId}",
)

_op_delete_destination_d1 = json_decoder(lambda: models.DeleteDestinationResponse)
_op_delete_destination = Op(
    key="notifications.v1.deleteDestination",
    name="delete_destination",
    operation_id="deleteDestination",
    api="notifications",
    version="v1",
    method="DELETE",
    path="/notifications/v1/destinations/{destinationId}",
    url_template="/notifications/v1/destinations/{}",
    path_params=(path("destination_id", "destinationId"),),
    query_params=(),
    header_params=(),
    default_decoder=_op_delete_destination_d1,
    error_decoders={
        400: _op_delete_destination_d1,
        403: _op_delete_destination_d1,
        404: _op_delete_destination_d1,
        409: _op_delete_destination_d1,
        413: _op_delete_destination_d1,
        415: _op_delete_destination_d1,
        429: _op_delete_destination_d1,
        500: _op_delete_destination_d1,
        503: _op_delete_destination_d1,
    },
    default_error=_op_delete_destination_d1,
    rate_limit=RateLimit(rate=1, burst=5),
    doc="Deletes the destination that you specify. The `deleteDestination` operation is grantless. For more information, refer to [Grantless Operations](https://developer-docs.amazon.com/sp-api/docs/grantless-operations) in the Selling Partner API Developer Guide.\n\n**Usage Plan:**\n\n| Rate (requests per second) | Burst |\n| ---- | ---- |\n| 1 | 5 |\n\nThe `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).\n\nDELETE /notifications/v1/destinations/{destinationId}",
)


class NotificationsV1(SyncResource):
    """Sync resource for notifications v1."""

    __slots__ = ()
    _resource_name = "notifications.v1"
    models = models
    _ops = {
        "get_subscriptions": _op_get_subscriptions,
        "get_subscription": _op_get_subscription,
        "create_subscription": _op_create_subscription,
        "get_subscription_by_id": _op_get_subscription_by_id,
        "delete_subscription_by_id": _op_delete_subscription_by_id,
        "send_test_notification": _op_send_test_notification,
        "get_destinations": _op_get_destinations,
        "create_destination": _op_create_destination,
        "get_destination": _op_get_destination,
        "delete_destination": _op_delete_destination,
    }

    def get_subscriptions(
        self,
        *,
        notification_types: list[str],
        payload_version: str | NotGiven = NOT_GIVEN,
        page_size: int | NotGiven = NOT_GIVEN,
        next_token: str | NotGiven = NOT_GIVEN,
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> SyncPage[models.Subscription]:
        """Returns information about subscriptions of the specified notification type. You can use this API to retrieve all subscriptions when multiple subscriptions exist for a notification type (for example, when using filter expressions).

        The operation returns all subscriptions for the caller's party.

        `payloadVersion` is an optional parameter. When you do not provide `payloadVersion`, the operation returns subscriptions across all payload versions.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        GET /notifications/v1/subscriptions
        """
        return self._client.call(
            _op_get_subscriptions,
            {
                "notification_types": notification_types,
                "payload_version": payload_version,
                "page_size": page_size,
                "next_token": next_token,
            },
            raw,
            paginate,
            request_options,
        )

    def get_subscription(
        self,
        *,
        notification_type: str,
        payload_version: str | NotGiven = NOT_GIVEN,
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.GetSubscriptionResponse:
        """Returns information about subscription of the specified notification type and payload version. `payloadVersion` is an optional parameter. When you do not provide `payloadVersion`, the operation returns the latest payload version subscription's information. You can use this API to get subscription information when you do not have a subscription identifier.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        GET /notifications/v1/subscriptions/{notificationType}
        """
        return self._client.call(
            _op_get_subscription,
            {"notification_type": notification_type, "payload_version": payload_version},
            raw,
            paginate,
            request_options,
        )

    def create_subscription(
        self,
        *,
        notification_type: str,
        body: models.CreateSubscriptionRequest | Mapping[str, Any],
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.CreateSubscriptionResponse:
        """Creates a subscription for the specified notification type to be delivered to the specified destination. Before you can subscribe, you must first create the destination by calling the `createDestination` operation. If the notification type that you specify supports multiple payload versions, you can use this operation to subscribe to a different payload version if you already have an existing subscription for a different payload version.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /notifications/v1/subscriptions/{notificationType}
        """
        return self._client.call(
            _op_create_subscription, {"notification_type": notification_type, "body": body}, raw, paginate, request_options
        )

    def get_subscription_by_id(
        self,
        *,
        notification_type: str,
        subscription_id: str,
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.GetSubscriptionByIdResponse:
        """Returns information about a subscription for the specified notification type. The `getSubscriptionById` operation is grantless. For more information, refer to [Grantless Operations](https://developer-docs.amazon.com/sp-api/docs/grantless-operations) in the Selling Partner API Developer Guide.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        GET /notifications/v1/subscriptions/{notificationType}/{subscriptionId}
        """
        return self._client.call(
            _op_get_subscription_by_id,
            {"notification_type": notification_type, "subscription_id": subscription_id},
            raw,
            paginate,
            request_options,
        )

    def delete_subscription_by_id(
        self,
        *,
        notification_type: str,
        subscription_id: str,
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.DeleteSubscriptionByIdResponse:
        """Deletes the subscription indicated by the subscription identifier and notification type that you specify. The subscription identifier can be for any subscription associated with your application. After you successfully call this operation, notifications will stop being sent for the associated subscription. The `deleteSubscriptionById` operation is grantless. For more information, refer to [Grantless Operations](https://developer-docs.amazon.com/sp-api/docs/grantless-operations) in the Selling Partner API Developer Guide.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        DELETE /notifications/v1/subscriptions/{notificationType}/{subscriptionId}
        """
        return self._client.call(
            _op_delete_subscription_by_id,
            {"notification_type": notification_type, "subscription_id": subscription_id},
            raw,
            paginate,
            request_options,
        )

    def send_test_notification(
        self,
        *,
        notification_type: str,
        body: models.SendTestNotificationRequest | Mapping[str, Any],
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.SendTestNotificationResponse:
        """Sends a mock notification of the specified type to your SQS. The `sendTestNotification` API is grantless. For more information, see "Grantless operations" in the Selling Partner API Developer Guide.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation. This is a sandbox-only operation and must be directed to a sandbox endpoint. Refer to [Selling Partner API sandbox](https://developer-docs.amazon.com/sp-api/docs/the-selling-partner-api-sandbox) for more information.

        POST /notifications/v1/subscriptions/{notificationType}/testNotification
        """
        return self._client.call(
            _op_send_test_notification, {"notification_type": notification_type, "body": body}, raw, paginate, request_options
        )

    def get_destinations(
        self,
        *,
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.GetDestinationsResponse:
        """Returns information about all destinations. The `getDestinations` operation is grantless. For more information, refer to [Grantless Operations](https://developer-docs.amazon.com/sp-api/docs/grantless-operations) in the Selling Partner API Developer Guide.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        GET /notifications/v1/destinations
        """
        return self._client.call(_op_get_destinations, {}, raw, paginate, request_options)

    def create_destination(
        self,
        *,
        body: models.CreateDestinationRequest | Mapping[str, Any],
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.CreateDestinationResponse:
        """Creates a destination resource to receive notifications. The `createDestination` operation is grantless. For more information, refer to [Grantless Operations](https://developer-docs.amazon.com/sp-api/docs/grantless-operations) in the Selling Partner API Developer Guide.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /notifications/v1/destinations
        """
        return self._client.call(_op_create_destination, {"body": body}, raw, paginate, request_options)

    def get_destination(
        self,
        *,
        destination_id: str,
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.GetDestinationResponse:
        """Returns information about the destination that you specify. The `getDestination` operation is grantless. For more information, refer to [Grantless Operations](https://developer-docs.amazon.com/sp-api/docs/grantless-operations) in the Selling Partner API Developer Guide.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        GET /notifications/v1/destinations/{destinationId}
        """
        return self._client.call(_op_get_destination, {"destination_id": destination_id}, raw, paginate, request_options)

    def delete_destination(
        self,
        *,
        destination_id: str,
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.DeleteDestinationResponse:
        """Deletes the destination that you specify. The `deleteDestination` operation is grantless. For more information, refer to [Grantless Operations](https://developer-docs.amazon.com/sp-api/docs/grantless-operations) in the Selling Partner API Developer Guide.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        DELETE /notifications/v1/destinations/{destinationId}
        """
        return self._client.call(_op_delete_destination, {"destination_id": destination_id}, raw, paginate, request_options)


class AsyncNotificationsV1(AsyncResource):
    """Async resource for notifications v1."""

    __slots__ = ()
    _resource_name = "notifications.v1"
    models = models
    _ops = {
        "get_subscriptions": _op_get_subscriptions,
        "get_subscription": _op_get_subscription,
        "create_subscription": _op_create_subscription,
        "get_subscription_by_id": _op_get_subscription_by_id,
        "delete_subscription_by_id": _op_delete_subscription_by_id,
        "send_test_notification": _op_send_test_notification,
        "get_destinations": _op_get_destinations,
        "create_destination": _op_create_destination,
        "get_destination": _op_get_destination,
        "delete_destination": _op_delete_destination,
    }

    async def get_subscriptions(
        self,
        *,
        notification_types: list[str],
        payload_version: str | NotGiven = NOT_GIVEN,
        page_size: int | NotGiven = NOT_GIVEN,
        next_token: str | NotGiven = NOT_GIVEN,
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> AsyncPage[models.Subscription]:
        """Returns information about subscriptions of the specified notification type. You can use this API to retrieve all subscriptions when multiple subscriptions exist for a notification type (for example, when using filter expressions).

        The operation returns all subscriptions for the caller's party.

        `payloadVersion` is an optional parameter. When you do not provide `payloadVersion`, the operation returns subscriptions across all payload versions.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        GET /notifications/v1/subscriptions
        """
        return await self._client.call(
            _op_get_subscriptions,
            {
                "notification_types": notification_types,
                "payload_version": payload_version,
                "page_size": page_size,
                "next_token": next_token,
            },
            raw,
            paginate,
            request_options,
        )

    async def get_subscription(
        self,
        *,
        notification_type: str,
        payload_version: str | NotGiven = NOT_GIVEN,
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.GetSubscriptionResponse:
        """Returns information about subscription of the specified notification type and payload version. `payloadVersion` is an optional parameter. When you do not provide `payloadVersion`, the operation returns the latest payload version subscription's information. You can use this API to get subscription information when you do not have a subscription identifier.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        GET /notifications/v1/subscriptions/{notificationType}
        """
        return await self._client.call(
            _op_get_subscription,
            {"notification_type": notification_type, "payload_version": payload_version},
            raw,
            paginate,
            request_options,
        )

    async def create_subscription(
        self,
        *,
        notification_type: str,
        body: models.CreateSubscriptionRequest | Mapping[str, Any],
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.CreateSubscriptionResponse:
        """Creates a subscription for the specified notification type to be delivered to the specified destination. Before you can subscribe, you must first create the destination by calling the `createDestination` operation. If the notification type that you specify supports multiple payload versions, you can use this operation to subscribe to a different payload version if you already have an existing subscription for a different payload version.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /notifications/v1/subscriptions/{notificationType}
        """
        return await self._client.call(
            _op_create_subscription, {"notification_type": notification_type, "body": body}, raw, paginate, request_options
        )

    async def get_subscription_by_id(
        self,
        *,
        notification_type: str,
        subscription_id: str,
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.GetSubscriptionByIdResponse:
        """Returns information about a subscription for the specified notification type. The `getSubscriptionById` operation is grantless. For more information, refer to [Grantless Operations](https://developer-docs.amazon.com/sp-api/docs/grantless-operations) in the Selling Partner API Developer Guide.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        GET /notifications/v1/subscriptions/{notificationType}/{subscriptionId}
        """
        return await self._client.call(
            _op_get_subscription_by_id,
            {"notification_type": notification_type, "subscription_id": subscription_id},
            raw,
            paginate,
            request_options,
        )

    async def delete_subscription_by_id(
        self,
        *,
        notification_type: str,
        subscription_id: str,
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.DeleteSubscriptionByIdResponse:
        """Deletes the subscription indicated by the subscription identifier and notification type that you specify. The subscription identifier can be for any subscription associated with your application. After you successfully call this operation, notifications will stop being sent for the associated subscription. The `deleteSubscriptionById` operation is grantless. For more information, refer to [Grantless Operations](https://developer-docs.amazon.com/sp-api/docs/grantless-operations) in the Selling Partner API Developer Guide.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        DELETE /notifications/v1/subscriptions/{notificationType}/{subscriptionId}
        """
        return await self._client.call(
            _op_delete_subscription_by_id,
            {"notification_type": notification_type, "subscription_id": subscription_id},
            raw,
            paginate,
            request_options,
        )

    async def send_test_notification(
        self,
        *,
        notification_type: str,
        body: models.SendTestNotificationRequest | Mapping[str, Any],
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.SendTestNotificationResponse:
        """Sends a mock notification of the specified type to your SQS. The `sendTestNotification` API is grantless. For more information, see "Grantless operations" in the Selling Partner API Developer Guide.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation. This is a sandbox-only operation and must be directed to a sandbox endpoint. Refer to [Selling Partner API sandbox](https://developer-docs.amazon.com/sp-api/docs/the-selling-partner-api-sandbox) for more information.

        POST /notifications/v1/subscriptions/{notificationType}/testNotification
        """
        return await self._client.call(
            _op_send_test_notification, {"notification_type": notification_type, "body": body}, raw, paginate, request_options
        )

    async def get_destinations(
        self,
        *,
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.GetDestinationsResponse:
        """Returns information about all destinations. The `getDestinations` operation is grantless. For more information, refer to [Grantless Operations](https://developer-docs.amazon.com/sp-api/docs/grantless-operations) in the Selling Partner API Developer Guide.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        GET /notifications/v1/destinations
        """
        return await self._client.call(_op_get_destinations, {}, raw, paginate, request_options)

    async def create_destination(
        self,
        *,
        body: models.CreateDestinationRequest | Mapping[str, Any],
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.CreateDestinationResponse:
        """Creates a destination resource to receive notifications. The `createDestination` operation is grantless. For more information, refer to [Grantless Operations](https://developer-docs.amazon.com/sp-api/docs/grantless-operations) in the Selling Partner API Developer Guide.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /notifications/v1/destinations
        """
        return await self._client.call(_op_create_destination, {"body": body}, raw, paginate, request_options)

    async def get_destination(
        self,
        *,
        destination_id: str,
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.GetDestinationResponse:
        """Returns information about the destination that you specify. The `getDestination` operation is grantless. For more information, refer to [Grantless Operations](https://developer-docs.amazon.com/sp-api/docs/grantless-operations) in the Selling Partner API Developer Guide.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        GET /notifications/v1/destinations/{destinationId}
        """
        return await self._client.call(_op_get_destination, {"destination_id": destination_id}, raw, paginate, request_options)

    async def delete_destination(
        self,
        *,
        destination_id: str,
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.DeleteDestinationResponse:
        """Deletes the destination that you specify. The `deleteDestination` operation is grantless. For more information, refer to [Grantless Operations](https://developer-docs.amazon.com/sp-api/docs/grantless-operations) in the Selling Partner API Developer Guide.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        DELETE /notifications/v1/destinations/{destinationId}
        """
        return await self._client.call(_op_delete_destination, {"destination_id": destination_id}, raw, paginate, request_options)


__all__ = ["AsyncNotificationsV1", "NotificationsV1"]
