"""Models for finances_invoices v2026_06_25 (The Selling Partner API for Invoices).

Generated by codegen/ (oagen) from the pinned spec; do not edit by hand.
"""

from __future__ import annotations

import datetime
from typing import Literal, TypeAlias

from pydantic import Field

from amzn_selling_partner.runtime._models import SpecModel

InvoiceHeaderInvoiceStatus: TypeAlias = Literal["IN_PROGRESS", "REJECTED", "PARTIALLY_PAID", "PARTIALLY_DEDUCTED", "PAID", "DEDUCTED"]
InvoiceHeaderInvoiceType: TypeAlias = Literal["AP_INVENTORY", "OTHER"]
ItemIdentifierName: TypeAlias = Literal["ASIN", "EXTERNAL_ID", "SKU", "UPC", "EAN", "ISBN"]
LineItemContextLineItemType: TypeAlias = Literal["GOODS", "SERVICES", "OTHERS"]
LineItemContextServiceChargeType: TypeAlias = Literal["DAMAGE_ALLOWANCE", "PRICE_PROTECTION", "FBA_INVENTORY_STORAGE_FEE", "OTHER"]
PartnerMetadataPartnerType: TypeAlias = Literal["SELLER", "VENDOR", "AMAZON"]
RelatedIdentifierName: TypeAlias = Literal[
    "PAYEE_CODE",
    "PURCHASE_ORDER_IDS",
    "SHORTAGE_INVOICE_IDS",
    "ASN_IDS",
    "RETURN_IDS",
    "AGREEMENT_IDS",
    "PRODUCT_LINE",
    "VENDOR_CODE",
    "UNIQUE_PAYMENT_IDS",
    "WAREHOUSE_ID",
]
VarianceReasonVarianceType: TypeAlias = Literal["PQV", "PPV", "OTHER"]


class BillingPeriod(SpecModel):
    """The billing period for an invoice."""

    start_date: datetime.datetime = Field(alias="startDate")
    end_date: datetime.datetime = Field(alias="endDate")


class Breakdown(SpecModel):
    """Details about the movement of money. Breakdowns are further categorized into breakdown types, breakdown amounts, and sub-breakdowns."""

    breakdown_type: str = Field(alias="breakdownType")
    breakdown_amount: Currency = Field(alias="breakdownAmount")
    breakdowns: list[Breakdown] | None = None


class Currency(SpecModel):
    """A monetary amount with a currency code."""

    currency_code: str = Field(alias="currencyCode")
    currency_amount: float = Field(alias="currencyAmount")


class Error(SpecModel):
    """Error response returned when the request is unsuccessful."""

    code: str
    message: str
    details: str | None = None


class ErrorList(SpecModel):
    """A list of error responses returned when a request is unsuccessful."""

    errors: list[Error]


class GetInvoiceResponse(SpecModel):
    """The response to the `getInvoice` operation."""

    invoice_header: InvoiceHeader | None = Field(default=None, alias="invoiceHeader")
    invoice_items: list[InvoiceItem] | None = Field(default=None, alias="invoiceItems")
    next_token_for_line_items: str | None = Field(default=None, alias="nextTokenForLineItems")


class GetInvoicesResponse(SpecModel):
    """The response to the `getInvoiceHeaders` operation."""

    invoices: list[InvoiceHeader] | None = None
    num_of_records: int | None = Field(default=None, alias="numOfRecords")
    next_token: str | None = Field(default=None, alias="nextToken")


class InvoiceHeader(SpecModel):
    """Represents the header-level information for an invoice, including parties involved (payer/payee), financial amounts, status, dates, and related business identifiers."""

    invoice_number: str = Field(alias="invoiceNumber")
    invoice_status: InvoiceHeaderInvoiceStatus = Field(alias="invoiceStatus")
    invoice_type: InvoiceHeaderInvoiceType = Field(alias="invoiceType")
    billing_period: BillingPeriod | None = Field(default=None, alias="billingPeriod")
    payer: PartnerMetadata
    payee: PartnerMetadata
    invoice_identifier: str = Field(alias="invoiceIdentifier")
    issue_date: datetime.datetime = Field(alias="issueDate")
    due_date: datetime.datetime | None = Field(default=None, alias="dueDate")
    payment_terms: str | None = Field(default=None, alias="paymentTerms")
    invoice_amount: Currency = Field(alias="invoiceAmount")
    invoice_amount_breakdowns: list[Breakdown] | None = Field(default=None, alias="invoiceAmountBreakdowns")
    invoice_settlement_breakdowns: list[Breakdown] | None = Field(default=None, alias="invoiceSettlementBreakdowns")
    related_identifiers: list[RelatedIdentifier] | None = Field(default=None, alias="relatedIdentifiers")
    creation_date: datetime.datetime = Field(alias="creationDate")
    last_updated_date: datetime.datetime = Field(alias="lastUpdatedDate")


class InvoiceItem(SpecModel):
    """A line item within an invoice, including unit costs, quantities, tax information, and contextual details about the goods or services being invoiced."""

    line_item_id: str = Field(alias="lineItemId")
    unit_cost: Currency | None = Field(default=None, alias="unitCost")
    quantity: int | None = None
    tax_rate_codes: list[str] | None = Field(default=None, alias="taxRateCodes")
    total_amount: Currency = Field(alias="totalAmount")
    total_amount_breakdown: list[Breakdown] | None = Field(default=None, alias="totalAmountBreakdown")
    line_item_context: LineItemContext = Field(alias="lineItemContext")
    related_item_identifiers: list[RelatedIdentifier] | None = Field(default=None, alias="relatedItemIdentifiers")


class ItemIdentifier(SpecModel):
    """Identifier for an item in the invoice line item."""

    item_identifier_name: ItemIdentifierName = Field(alias="itemIdentifierName")
    item_identifier_value: str = Field(alias="itemIdentifierValue")


class LineItemContext(SpecModel):
    """Contextual information about an invoice line item."""

    line_item_type: LineItemContextLineItemType = Field(alias="lineItemType")
    item_identifiers: list[ItemIdentifier] | None = Field(default=None, alias="itemIdentifiers")
    item_description: str | None = Field(default=None, alias="itemDescription")
    service_charge_type: LineItemContextServiceChargeType | None = Field(default=None, alias="serviceChargeType")
    service_charge_period: ServiceChargePeriod | None = Field(default=None, alias="serviceChargePeriod")
    matching_context: MatchingContext | None = Field(default=None, alias="matchingContext")


class MatchingContext(SpecModel):
    """How an invoice line item's quantity and price were matched against expected values, including any variances and their underlying reasons."""

    matched_quantity: int = Field(alias="matchedQuantity")
    matched_amount: Currency = Field(alias="matchedAmount")
    quantity_variance: int | None = Field(default=None, alias="quantityVariance")
    price_variance: Currency | None = Field(default=None, alias="priceVariance")
    paid_quantity: int | None = Field(default=None, alias="paidQuantity")
    paid_amount: Currency | None = Field(default=None, alias="paidAmount")
    variance_reasons: list[VarianceReason] | None = Field(default=None, alias="varianceReasons")


class PartnerMetadata(SpecModel):
    """Metadata about a partner (payer or payee) associated with the invoice."""

    partner_id: str = Field(alias="partnerId")
    partner_type: PartnerMetadataPartnerType = Field(alias="partnerType")
    partner_entities: list[str] | None = Field(default=None, alias="partnerEntities")
    partner_name: str | None = Field(default=None, alias="partnerName")
    partner_address: str | None = Field(default=None, alias="partnerAddress")
    tax_registration_number: str | None = Field(default=None, alias="taxRegistrationNumber")


class RelatedIdentifier(SpecModel):
    """Related business identifier of the transaction."""

    related_identifier_name: RelatedIdentifierName = Field(alias="relatedIdentifierName")
    related_identifier_value: list[str] = Field(alias="relatedIdentifierValue")


class ServiceChargePeriod(SpecModel):
    """The time period for a service charge."""

    start_date: datetime.datetime = Field(alias="startDate")
    end_date: datetime.datetime = Field(alias="endDate")


class VarianceReason(SpecModel):
    """The type and underlying defect classifications explaining discrepancies between expected and actual invoice values."""

    variance_type: VarianceReasonVarianceType = Field(alias="varianceType")
    defect_types: list[str] | None = Field(default=None, alias="defectTypes")


__all__ = [
    "BillingPeriod",
    "Breakdown",
    "Currency",
    "Error",
    "ErrorList",
    "GetInvoiceResponse",
    "GetInvoicesResponse",
    "InvoiceHeader",
    "InvoiceHeaderInvoiceStatus",
    "InvoiceHeaderInvoiceType",
    "InvoiceItem",
    "ItemIdentifier",
    "ItemIdentifierName",
    "LineItemContext",
    "LineItemContextLineItemType",
    "LineItemContextServiceChargeType",
    "MatchingContext",
    "PartnerMetadata",
    "PartnerMetadataPartnerType",
    "RelatedIdentifier",
    "RelatedIdentifierName",
    "ServiceChargePeriod",
    "VarianceReason",
    "VarianceReasonVarianceType",
]
