# Auto-generated by oagen. Do not edit.

"""Models of application_v2023_11_30.

Auto-generated by oagen from the OpenAPI spec; do not edit by hand.
"""

from __future__ import annotations

from .._base import SpecModel


class Error(SpecModel):
    """Error response returned when the request is unsuccessful."""

    code: str
    message: str
    details: str | None = None


class ErrorList(SpecModel):
    """A list of error responses returned when a request is unsuccessful."""

    errors: list[Error]


__all__ = [
    "Error",
    "ErrorList",
]
