# Auto-generated by oagen. Do not edit.

"""Models package ``application_v2023_11_30``.

Auto-generated by oagen from the OpenAPI spec; do not edit by hand.
"""

from __future__ import annotations

from .models import Error, ErrorList

__all__ = [
    "Error",
    "ErrorList",
]
