"""Models for sales v1 (Selling Partner API for Sales).

Generated by codegen/ (oagen) from the pinned spec; do not edit by hand.
"""

from __future__ import annotations

from typing import Literal, TypeAlias

from pydantic import Field

from amzn_selling_partner.runtime._models import SpecModel

SalesBuyerType: TypeAlias = Literal["B2B", "B2C", "All"]
SalesFirstDayOfWeek: TypeAlias = Literal["Monday", "Sunday"]
SalesGranularity: TypeAlias = Literal["Hour", "Day", "Week", "Month", "Year", "Total"]


class Error(SpecModel):
    """Error response returned when the request is unsuccessful."""

    code: str
    message: str
    details: str | None = None


class GetOrderMetricsResponse(SpecModel):
    """The response schema for the getOrderMetrics operation."""

    payload: list[OrderMetricsInterval] | None = None
    errors: list[Error] | None = None


class Money(SpecModel):
    """The currency type and the amount."""

    currency_code: str = Field(alias="currencyCode")
    amount: str


class OrderMetricsInterval(SpecModel):
    """Contains order metrics."""

    interval: str
    unit_count: int = Field(alias="unitCount")
    order_item_count: int = Field(alias="orderItemCount")
    order_count: int = Field(alias="orderCount")
    average_unit_price: Money = Field(alias="averageUnitPrice")
    total_sales: Money = Field(alias="totalSales")


__all__ = [
    "Error",
    "GetOrderMetricsResponse",
    "Money",
    "OrderMetricsInterval",
    "SalesBuyerType",
    "SalesFirstDayOfWeek",
    "SalesGranularity",
]
