# Auto-generated by oagen. Do not edit.

"""Models of notifications.TransactionUpdateNotification.

Auto-generated by oagen from the OpenAPI spec; do not edit by hand.
"""

from __future__ import annotations

from pydantic import Field

from ..._base import SpecModel


class TransactionUpdateNotification(SpecModel):
    """The notification response schema that comprises the entire JSON document for the notification."""

    notification_version: str = Field(alias="NotificationVersion")
    notification_type: str = Field(alias="NotificationType")
    payload_version: str = Field(alias="PayloadVersion")
    event_time: str = Field(alias="EventTime")
    payload: TransactionUpdateNotificationPayload = Field(alias="Payload")
    notification_metadata: TransactionUpdateNotificationNotificationMetadata = Field(alias="NotificationMetadata")


class TransactionUpdateNotificationNotificationMetadata(SpecModel):
    application_id: str = Field(alias="ApplicationId")
    subscription_id: str = Field(alias="SubscriptionId")
    publish_time: str = Field(alias="PublishTime")
    notification_id: str = Field(alias="NotificationId")


class TransactionUpdateNotificationPayload(SpecModel):
    transaction_update_notification: TransactionUpdateNotificationPayloadTransactionUpdateNotification = Field(
        alias="TransactionUpdateNotification"
    )


class TransactionUpdateNotificationPayloadTransactionUpdateNotification(SpecModel):
    selling_partner_metadata: TransactionUpdateNotificationPayloadTransactionUpdateNotificationSellingPartnerMetadata = Field(
        alias="SellingPartnerMetadata"
    )
    transaction_type: str = Field(alias="TransactionType")
    posted_date: str = Field(alias="PostedDate")
    total_amount: TransactionUpdateNotificationPayloadTransactionUpdateNotificationTotalAmount = Field(alias="TotalAmount")
    related_identifiers: list[TransactionUpdateNotificationPayloadTransactionUpdateNotificationRelatedIdentifiersItem] | None = Field(
        default=None, alias="RelatedIdentifiers"
    )


class TransactionUpdateNotificationPayloadTransactionUpdateNotificationRelatedIdentifiersItem(SpecModel):
    related_identifier_name: str = Field(alias="RelatedIdentifierName")
    related_identifier_value: str = Field(alias="RelatedIdentifierValue")


class TransactionUpdateNotificationPayloadTransactionUpdateNotificationSellingPartnerMetadata(SpecModel):
    selling_partner_id: str = Field(alias="SellingPartnerId")
    marketplace_id: str = Field(alias="MarketplaceId")
    account_type: str = Field(alias="AccountType")


class TransactionUpdateNotificationPayloadTransactionUpdateNotificationTotalAmount(SpecModel):
    currency_amount: float = Field(alias="CurrencyAmount")
    currency_code: str = Field(alias="CurrencyCode")


__all__ = [
    "TransactionUpdateNotification",
    "TransactionUpdateNotificationNotificationMetadata",
    "TransactionUpdateNotificationPayload",
    "TransactionUpdateNotificationPayloadTransactionUpdateNotification",
    "TransactionUpdateNotificationPayloadTransactionUpdateNotificationRelatedIdentifiersItem",
    "TransactionUpdateNotificationPayloadTransactionUpdateNotificationSellingPartnerMetadata",
    "TransactionUpdateNotificationPayloadTransactionUpdateNotificationTotalAmount",
]
