# Auto-generated by oagen. Do not edit.

"""Enums of vendor_direct_fulfillment_orders_v1.

Auto-generated by oagen from the OpenAPI spec; do not edit by hand.
"""

from __future__ import annotations

from enum import Enum


class OrderDetailsOrderStatus(str, Enum):
    NEW = "NEW"
    SHIPPED = "SHIPPED"
    ACCEPTED = "ACCEPTED"
    CANCELLED = "CANCELLED"

    __str__ = str.__str__


class TaxDetailsType(str, Enum):
    CONSUMPTION = "CONSUMPTION"
    GST = "GST"
    MW_ST = "MwSt."
    PST = "PST"
    TOTAL = "TOTAL"
    TVA = "TVA"
    VAT = "VAT"

    __str__ = str.__str__


class TaxRegistrationDetailsTaxRegistrationType(str, Enum):
    VAT = "VAT"
    GST = "GST"

    __str__ = str.__str__


class VendorDirectFulfillmentOrdersV1SortOrder(str, Enum):
    ASC = "ASC"
    DESC = "DESC"

    __str__ = str.__str__


class VendorDirectFulfillmentOrdersV1Status(str, Enum):
    NEW = "NEW"
    SHIPPED = "SHIPPED"
    ACCEPTED = "ACCEPTED"
    CANCELLED = "CANCELLED"

    __str__ = str.__str__


__all__ = [
    "OrderDetailsOrderStatus",
    "TaxDetailsType",
    "TaxRegistrationDetailsTaxRegistrationType",
    "VendorDirectFulfillmentOrdersV1SortOrder",
    "VendorDirectFulfillmentOrdersV1Status",
]
