# Auto-generated by oagen. Do not edit.

"""Models of product_fees_v0.

Auto-generated by oagen from the OpenAPI spec; do not edit by hand.
"""

from __future__ import annotations

import datetime
from typing import Any

from pydantic import Field

from .._base import SpecModel
from .enums import IdType, OptionalFulfillmentProgram


class Error(SpecModel):
    """An object representing an error that occurred during the API operation."""

    code: str
    message: str
    details: str | None = None


class FeeDetail(SpecModel):
    """The type of fee, fee amount, and other details."""

    fee_type: str = Field(alias="FeeType")
    fee_amount: MoneyType = Field(alias="FeeAmount")
    final_fee: MoneyType = Field(alias="FinalFee")
    fee_promotion: MoneyType | None = Field(default=None, alias="FeePromotion")
    tax_amount: MoneyType | None = Field(default=None, alias="TaxAmount")
    included_fee_detail_list: list[IncludedFeeDetail] | None = Field(default=None, alias="IncludedFeeDetailList")


class FeesEstimate(SpecModel):
    """The total estimated fees for an item and a list of details."""

    time_of_fees_estimation: datetime.datetime = Field(alias="TimeOfFeesEstimation")
    total_fees_estimate: MoneyType | None = Field(default=None, alias="TotalFeesEstimate")
    fee_detail_list: list[FeeDetail] | None = Field(default=None, alias="FeeDetailList")


class FeesEstimateByIdRequest(SpecModel):
    """A product, marketplace, and proposed price used to request estimated fees."""

    id_type: IdType = Field(alias="IdType")
    id_value: str = Field(alias="IdValue")
    fees_estimate_request: FeesEstimateRequest | None = Field(default=None, alias="FeesEstimateRequest")


class FeesEstimateError(SpecModel):
    """An unexpected error occurred during this operation."""

    type_: str = Field(alias="Type")
    code: str = Field(alias="Code")
    message: str = Field(alias="Message")
    detail: list[dict[str, Any]] = Field(alias="Detail")


class FeesEstimateIdentifier(SpecModel):
    """An item identifier, marketplace, time of request, and other details that identify an estimate."""

    marketplace_id: str | None = Field(default=None, alias="MarketplaceId")
    seller_id: str | None = Field(default=None, alias="SellerId")
    id_type: IdType | None = Field(default=None, alias="IdType")
    id_value: str | None = Field(default=None, alias="IdValue")
    is_amazon_fulfilled: bool | None = Field(default=None, alias="IsAmazonFulfilled")
    price_to_estimate_fees: PriceToEstimateFees | None = Field(default=None, alias="PriceToEstimateFees")
    seller_input_identifier: str | None = Field(default=None, alias="SellerInputIdentifier")
    optional_fulfillment_program: OptionalFulfillmentProgram | None = Field(default=None, alias="OptionalFulfillmentProgram")


class FeesEstimateRequest(SpecModel):
    """A product, marketplace, and proposed price used to request estimated fees."""

    marketplace_id: str = Field(alias="MarketplaceId")
    price_to_estimate_fees: PriceToEstimateFees = Field(alias="PriceToEstimateFees")
    identifier: str = Field(alias="Identifier")
    is_amazon_fulfilled: bool | None = Field(default=None, alias="IsAmazonFulfilled")
    optional_fulfillment_program: OptionalFulfillmentProgram | None = Field(default=None, alias="OptionalFulfillmentProgram")


class FeesEstimateResult(SpecModel):
    """An item identifier and the estimated fees for the item."""

    status: str | None = Field(default=None, alias="Status")
    fees_estimate_identifier: FeesEstimateIdentifier | None = Field(default=None, alias="FeesEstimateIdentifier")
    fees_estimate: FeesEstimate | None = Field(default=None, alias="FeesEstimate")
    error: FeesEstimateError | None = Field(default=None, alias="Error")


class GetMyFeesEstimateRequest(SpecModel):
    """Request schema."""

    fees_estimate_request: FeesEstimateRequest | None = Field(default=None, alias="FeesEstimateRequest")


class GetMyFeesEstimateResponse(SpecModel):
    """The response object for the GetMyFeesEstimate operation."""

    payload: GetMyFeesEstimateResult | None = None
    errors: list[Error] | None = None


class GetMyFeesEstimateResult(SpecModel):
    """Response schema."""

    fees_estimate_result: FeesEstimateResult | None = Field(default=None, alias="FeesEstimateResult")


class GetMyFeesEstimatesErrorList(SpecModel):
    """A list of error responses returned when a request is unsuccessful."""

    errors: list[Error]


class IncludedFeeDetail(SpecModel):
    """The type of fee, fee amount, and other details."""

    fee_type: str = Field(alias="FeeType")
    fee_amount: MoneyType = Field(alias="FeeAmount")
    final_fee: MoneyType = Field(alias="FinalFee")
    fee_promotion: MoneyType | None = Field(default=None, alias="FeePromotion")
    tax_amount: MoneyType | None = Field(default=None, alias="TaxAmount")


class MoneyType(SpecModel):
    """An object representing a monetary value with its currency information."""

    currency_code: str | None = Field(default=None, alias="CurrencyCode")
    amount: float | None = Field(default=None, alias="Amount")


class Points(SpecModel):
    """The number of Amazon Points offered with the purchase of an item.The Amazon Points program is only available in Japan."""

    points_number: int | None = Field(default=None, alias="PointsNumber")
    points_monetary_value: MoneyType | None = Field(default=None, alias="PointsMonetaryValue")


class PriceToEstimateFees(SpecModel):
    """Price information for an item, used to estimate fees."""

    listing_price: MoneyType = Field(alias="ListingPrice")
    shipping: MoneyType | None = Field(default=None, alias="Shipping")
    points: Points | None = Field(default=None, alias="Points")


__all__ = [
    "Error",
    "FeeDetail",
    "FeesEstimate",
    "FeesEstimateByIdRequest",
    "FeesEstimateError",
    "FeesEstimateIdentifier",
    "FeesEstimateRequest",
    "FeesEstimateResult",
    "GetMyFeesEstimateRequest",
    "GetMyFeesEstimateResponse",
    "GetMyFeesEstimateResult",
    "GetMyFeesEstimatesErrorList",
    "IdType",
    "IncludedFeeDetail",
    "MoneyType",
    "OptionalFulfillmentProgram",
    "Points",
    "PriceToEstimateFees",
]
