# Auto-generated by oagen. Do not edit.

"""Enums of shipping_v1.

Auto-generated by oagen from the OpenAPI spec; do not edit by hand.
"""

from __future__ import annotations

from enum import Enum


class DimensionsUnit(str, Enum):
    IN = "IN"
    CM = "CM"


class ServiceType(str, Enum):
    AMAZON_SHIPPING_GROUND = "Amazon Shipping Ground"
    AMAZON_SHIPPING_STANDARD = "Amazon Shipping Standard"
    AMAZON_SHIPPING_PREMIUM = "Amazon Shipping Premium"


class WeightUnit(str, Enum):
    G = "g"
    KG = "kg"
    OZ = "oz"
    LB = "lb"


__all__ = [
    "DimensionsUnit",
    "ServiceType",
    "WeightUnit",
]
