# Generated by `python -m amzn_selling_partner.stubgen`; do not edit.
from __future__ import annotations
import datetime
from typing import Any, Literal, TypedDict

from pydantic import BaseModel, Field

class TransportationDetailsForShipmentConfirmation(BaseModel):
    """Transportation details for this shipment."""
    carrier_scac: str | None = Field(default=None, alias="carrierScac")
    carrier_shipment_reference_number: str | None = Field(default=None, alias="carrierShipmentReferenceNumber")
    transportation_mode: Literal['Road', 'Air', 'Ocean'] | None = Field(default=None, alias="transportationMode")
    bill_of_lading_number: str | None = Field(default=None, alias="billOfLadingNumber")
    def __init__(self, **data: Any) -> None: ...

class Address(BaseModel):
    """Address of the party."""
    name: str
    address_line1: str = Field(alias="addressLine1")
    address_line2: str | None = Field(default=None, alias="addressLine2")
    address_line3: str | None = Field(default=None, alias="addressLine3")
    city: str | None = Field(default=None)
    county: str | None = Field(default=None)
    district: str | None = Field(default=None)
    state_or_region: str | None = Field(default=None, alias="stateOrRegion")
    postal_code: str | None = Field(default=None, alias="postalCode")
    country_code: str = Field(alias="countryCode")
    phone: str | None = Field(default=None)
    def __init__(self, **data: Any) -> None: ...

class TaxRegistrationDetails(BaseModel):
    """Tax registration details of the entity."""
    tax_registration_type: Literal['VAT', 'GST'] = Field(alias="taxRegistrationType")
    tax_registration_number: str = Field(alias="taxRegistrationNumber")
    def __init__(self, **data: Any) -> None: ...

class PartyIdentification(BaseModel):
    """Name/Address and tax details of the party."""
    address: Address | None = Field(default=None)
    party_id: str = Field(alias="partyId")
    tax_registration_details: list[TaxRegistrationDetails] | None = Field(default=None, alias="taxRegistrationDetails")
    def __init__(self, **data: Any) -> None: ...

class Weight(BaseModel):
    """The weight of the shipment."""
    unit_of_measure: Literal['G', 'Kg', 'Oz', 'Lb'] = Field(alias="unitOfMeasure")
    value: Decimal
    def __init__(self, **data: Any) -> None: ...

class Volume(BaseModel):
    """The volume of the shipment."""
    unit_of_measure: Literal['CuFt', 'CuIn', 'CuM', 'CuY'] = Field(alias="unitOfMeasure")
    value: Decimal
    def __init__(self, **data: Any) -> None: ...

class ShipmentMeasurements(BaseModel):
    """Shipment measurement details."""
    gross_shipment_weight: Weight | None = Field(default=None, alias="grossShipmentWeight")
    shipment_volume: Volume | None = Field(default=None, alias="shipmentVolume")
    carton_count: int | None = Field(default=None, alias="cartonCount")
    pallet_count: int | None = Field(default=None, alias="palletCount")
    def __init__(self, **data: Any) -> None: ...

class Location(BaseModel):
    """Location identifier."""
    type: str | None = Field(default=None)
    location_code: str | None = Field(default=None, alias="locationCode")
    country_code: str | None = Field(default=None, alias="countryCode")
    def __init__(self, **data: Any) -> None: ...

class Stop(BaseModel):
    """Contractual or operational port or point relevant to the movement of the cargo."""
    function_code: Literal['PortOfDischarge', 'FreightPayableAt', 'PortOfLoading'] = Field(alias="functionCode")
    location_identification: Location | None = Field(default=None, alias="locationIdentification")
    arrival_time: datetime.datetime | None = Field(default=None, alias="arrivalTime")
    departure_time: datetime.datetime | None = Field(default=None, alias="departureTime")
    def __init__(self, **data: Any) -> None: ...

class Route(BaseModel):
    """This is used only for direct import shipment confirmations."""
    stops: list[Stop]
    def __init__(self, **data: Any) -> None: ...

class ImportDetails(BaseModel):
    """Provide these fields only if this shipment is a direct import."""
    method_of_payment: Literal['PaidByBuyer', 'CollectOnDelivery', 'DefinedByBuyerAndSeller', 'FOBPortOfCall', 'PrepaidBySeller', 'PaidBySeller'] | None = Field(default=None, alias="methodOfPayment")
    seal_number: str | None = Field(default=None, alias="sealNumber")
    route: Route | None = Field(default=None)
    import_containers: str | None = Field(default=None, alias="importContainers")
    billable_weight: Weight | None = Field(default=None, alias="billableWeight")
    estimated_ship_by_date: datetime.datetime | None = Field(default=None, alias="estimatedShipByDate")
    handling_instructions: Literal['Oversized', 'Fragile', 'Food', 'HandleWithCare'] | None = Field(default=None, alias="handlingInstructions")
    def __init__(self, **data: Any) -> None: ...

class TotalWeight(BaseModel):
    """The total weight of units that are sold by weight in a shipment."""
    unit_of_measure: Literal['POUNDS', 'OUNCES', 'GRAMS', 'KILOGRAMS'] = Field(alias="unitOfMeasure")
    amount: Decimal
    def __init__(self, **data: Any) -> None: ...

class ItemQuantity(BaseModel):
    """Details of item quantity."""
    amount: int
    unit_of_measure: Literal['Cases', 'Eaches'] = Field(alias="unitOfMeasure")
    unit_size: int | None = Field(default=None, alias="unitSize")
    total_weight: TotalWeight | None = Field(default=None, alias="totalWeight")
    def __init__(self, **data: Any) -> None: ...

class RegulationReferences(BaseModel):
    """Regulatory requirements and compliance information for the item, including reference numbers, verification codes, and exemption codes. Use this field to specify applicable regulations such as EU Defor"""
    due_diligence_reference: str | None = Field(default=None, alias="dueDiligenceReference")
    due_diligence_verification: str | None = Field(default=None, alias="dueDiligenceVerification")
    due_diligence_information: str | None = Field(default=None, alias="dueDiligenceInformation")
    due_diligence_exemption_code: str | None = Field(default=None, alias="dueDiligenceExemptionCode")
    def __init__(self, **data: Any) -> None: ...

class Duration(BaseModel):
    """Duration after manufacturing date during which the product is valid for consumption."""
    duration_unit: Literal['Days', 'Months'] = Field(alias="durationUnit")
    duration_value: int = Field(alias="durationValue")
    def __init__(self, **data: Any) -> None: ...

class Expiry(BaseModel):
    """Expiry refers to the collection of dates required  for certain items. These could be either expiryDate or mfgDate and expiryAfterDuration. These are mandatory for perishable items."""
    manufacturer_date: datetime.datetime | None = Field(default=None, alias="manufacturerDate")
    expiry_date: datetime.datetime | None = Field(default=None, alias="expiryDate")
    expiry_after_duration: Duration | None = Field(default=None, alias="expiryAfterDuration")
    def __init__(self, **data: Any) -> None: ...

class Money(BaseModel):
    """An amount of money, including units in the form of currency."""
    currency_code: str = Field(alias="currencyCode")
    amount: Decimal
    def __init__(self, **data: Any) -> None: ...

class ItemDetails(BaseModel):
    """Item details for be provided for every item in shipment at either the item or carton or pallet level, whichever is appropriate."""
    purchase_order_number: str | None = Field(default=None, alias="purchaseOrderNumber")
    lot_number: str | None = Field(default=None, alias="lotNumber")
    lot_number_source_reference: str | None = Field(default=None, alias="lotNumberSourceReference")
    lot_number_source_type: Literal['GLN', 'FFRN', 'USDA_E', 'URL'] | None = Field(default=None, alias="lotNumberSourceType")
    country_of_origin: str | None = Field(default=None, alias="countryOfOrigin")
    regulation_references: RegulationReferences | None = Field(default=None, alias="regulationReferences")
    expiry: Expiry | None = Field(default=None)
    maximum_retail_price: Money | None = Field(default=None, alias="maximumRetailPrice")
    handling_code: Literal['Oversized', 'Fragile', 'Food', 'HandleWithCare'] | None = Field(default=None, alias="handlingCode")
    def __init__(self, **data: Any) -> None: ...

class Item(BaseModel):
    """Details of the item being shipped."""
    item_sequence_number: str = Field(alias="itemSequenceNumber")
    amazon_product_identifier: str | None = Field(default=None, alias="amazonProductIdentifier")
    vendor_product_identifier: str | None = Field(default=None, alias="vendorProductIdentifier")
    shipped_quantity: ItemQuantity = Field(alias="shippedQuantity")
    item_details: ItemDetails | None = Field(default=None, alias="itemDetails")
    def __init__(self, **data: Any) -> None: ...

class ContainerIdentification(BaseModel):
    """A list of carton identifiers."""
    container_identification_type: Literal['SSCC', 'AMZNCC', 'GTIN', 'BPS', 'CID'] = Field(alias="containerIdentificationType")
    container_identification_number: str = Field(alias="containerIdentificationNumber")
    def __init__(self, **data: Any) -> None: ...

class Dimensions(BaseModel):
    """Physical dimensional measurements of a container."""
    length: Decimal
    width: Decimal
    height: Decimal
    unit_of_measure: Literal['In', 'Ft', 'Meter', 'Yard'] = Field(alias="unitOfMeasure")
    def __init__(self, **data: Any) -> None: ...

class ContainerItem(BaseModel):
    """Carton/Pallet level details for the item."""
    item_reference: str = Field(alias="itemReference")
    shipped_quantity: ItemQuantity = Field(alias="shippedQuantity")
    item_details: ItemDetails | None = Field(default=None, alias="itemDetails")
    def __init__(self, **data: Any) -> None: ...

class Carton(BaseModel):
    """Details of the carton/package being shipped."""
    carton_identifiers: list[ContainerIdentification] | None = Field(default=None, alias="cartonIdentifiers")
    carton_sequence_number: str = Field(alias="cartonSequenceNumber")
    dimensions: Dimensions | None = Field(default=None)
    weight: Weight | None = Field(default=None)
    tracking_number: str | None = Field(default=None, alias="trackingNumber")
    items: list[ContainerItem]
    def __init__(self, **data: Any) -> None: ...

class CartonReferenceDetails(BaseModel):
    """Carton reference details."""
    carton_count: int | None = Field(default=None, alias="cartonCount")
    carton_reference_numbers: list[str] = Field(alias="cartonReferenceNumbers")
    def __init__(self, **data: Any) -> None: ...

class Pallet(BaseModel):
    """Details of the Pallet/Tare being shipped."""
    pallet_identifiers: list[ContainerIdentification] = Field(alias="palletIdentifiers")
    tier: int | None = Field(default=None)
    block: int | None = Field(default=None)
    dimensions: Dimensions | None = Field(default=None)
    weight: Weight | None = Field(default=None)
    carton_reference_details: CartonReferenceDetails | None = Field(default=None, alias="cartonReferenceDetails")
    items: list[ContainerItem] | None = Field(default=None)
    def __init__(self, **data: Any) -> None: ...

class ShipmentConfirmation(BaseModel):
    """A list of one or more shipment confirmations."""
    shipment_identifier: str = Field(alias="shipmentIdentifier")
    shipment_confirmation_type: Literal['Original', 'Replace'] = Field(alias="shipmentConfirmationType")
    shipment_type: Literal['TruckLoad', 'LessThanTruckLoad', 'SmallParcel'] | None = Field(default=None, alias="shipmentType")
    shipment_structure: Literal['PalletizedAssortmentCase', 'LooseAssortmentCase', 'PalletOfItems', 'PalletizedStandardCase', 'LooseStandardCase', 'MasterPallet', 'MasterCase'] | None = Field(default=None, alias="shipmentStructure")
    transportation_details: TransportationDetailsForShipmentConfirmation | None = Field(default=None, alias="transportationDetails")
    amazon_reference_number: str | None = Field(default=None, alias="amazonReferenceNumber")
    shipment_confirmation_date: datetime.datetime = Field(alias="shipmentConfirmationDate")
    shipped_date: datetime.datetime | None = Field(default=None, alias="shippedDate")
    estimated_delivery_date: datetime.datetime | None = Field(default=None, alias="estimatedDeliveryDate")
    selling_party: PartyIdentification = Field(alias="sellingParty")
    ship_from_party: PartyIdentification = Field(alias="shipFromParty")
    ship_to_party: PartyIdentification = Field(alias="shipToParty")
    shipment_measurements: ShipmentMeasurements | None = Field(default=None, alias="shipmentMeasurements")
    import_details: ImportDetails | None = Field(default=None, alias="importDetails")
    shipped_items: list[Item] = Field(alias="shippedItems")
    cartons: list[Carton] | None = Field(default=None)
    pallets: list[Pallet] | None = Field(default=None)
    def __init__(self, **data: Any) -> None: ...

class SubmitShipmentConfirmationsRequest(BaseModel):
    """The request schema for the SubmitShipmentConfirmations operation."""
    shipment_confirmations: list[ShipmentConfirmation] | None = Field(default=None, alias="shipmentConfirmations")
    def __init__(self, **data: Any) -> None: ...

class ShipmentStatusDetails(BaseModel):
    """Shipment Status details."""
    shipment_status: Literal['Created', 'TransportationRequested', 'CarrierAssigned', 'Shipped'] | None = Field(default=None, alias="shipmentStatus")
    shipment_status_date: datetime.datetime | None = Field(default=None, alias="shipmentStatusDate")
    def __init__(self, **data: Any) -> None: ...

class TransportShipmentMeasurements(BaseModel):
    """Shipment measurement details."""
    total_carton_count: int | None = Field(default=None, alias="totalCartonCount")
    total_pallet_stackable: int | None = Field(default=None, alias="totalPalletStackable")
    total_pallet_non_stackable: int | None = Field(default=None, alias="totalPalletNonStackable")
    shipment_weight: Weight | None = Field(default=None, alias="shipmentWeight")
    shipment_volume: Volume | None = Field(default=None, alias="shipmentVolume")
    def __init__(self, **data: Any) -> None: ...

class CollectFreightPickupDetails(BaseModel):
    """Transport Request pickup date from Vendor Warehouse by Buyer"""
    requested_pick_up: datetime.datetime | None = Field(default=None, alias="requestedPickUp")
    scheduled_pick_up: datetime.datetime | None = Field(default=None, alias="scheduledPickUp")
    carrier_assignment_date: datetime.datetime | None = Field(default=None, alias="carrierAssignmentDate")
    def __init__(self, **data: Any) -> None: ...

class PurchaseOrderItems(BaseModel):
    """Details of the item being shipped."""
    item_sequence_number: str = Field(alias="itemSequenceNumber")
    buyer_product_identifier: str | None = Field(default=None, alias="buyerProductIdentifier")
    vendor_product_identifier: str | None = Field(default=None, alias="vendorProductIdentifier")
    shipped_quantity: ItemQuantity = Field(alias="shippedQuantity")
    maximum_retail_price: Money | None = Field(default=None, alias="maximumRetailPrice")
    def __init__(self, **data: Any) -> None: ...

class PurchaseOrders(BaseModel):
    """Transport Request pickup date"""
    purchase_order_number: str | None = Field(default=None, alias="purchaseOrderNumber")
    purchase_order_date: datetime.datetime | None = Field(default=None, alias="purchaseOrderDate")
    ship_window: str | None = Field(default=None, alias="shipWindow")
    items: list[PurchaseOrderItems] | None = Field(default=None)
    def __init__(self, **data: Any) -> None: ...

class ContainerSequenceNumbers(BaseModel):
    """Container sequence numbers that are involved in this shipment."""
    container_sequence_number: str | None = Field(default=None, alias="containerSequenceNumber")
    def __init__(self, **data: Any) -> None: ...

class InnerContainersDetails(BaseModel):
    """Details of the innerContainersDetails."""
    container_count: int | None = Field(default=None, alias="containerCount")
    container_sequence_numbers: list[ContainerSequenceNumbers] | None = Field(default=None, alias="containerSequenceNumbers")
    def __init__(self, **data: Any) -> None: ...

class PackageItemDetails(BaseModel):
    """Item details for be provided for every item in shipment at either the item or carton or pallet level, whichever is appropriate."""
    purchase_order_number: str | None = Field(default=None, alias="purchaseOrderNumber")
    lot_number: str | None = Field(default=None, alias="lotNumber")
    expiry: Expiry | None = Field(default=None)
    def __init__(self, **data: Any) -> None: ...

class PackedItems(BaseModel):
    """Details of the item being shipped."""
    item_sequence_number: str | None = Field(default=None, alias="itemSequenceNumber")
    buyer_product_identifier: str | None = Field(default=None, alias="buyerProductIdentifier")
    vendor_product_identifier: str | None = Field(default=None, alias="vendorProductIdentifier")
    packed_quantity: ItemQuantity | None = Field(default=None, alias="packedQuantity")
    item_details: PackageItemDetails | None = Field(default=None, alias="itemDetails")
    def __init__(self, **data: Any) -> None: ...

class Containers(BaseModel):
    """A list of the items in this transportation and their associated inner container details. If any of the item detail fields are common at a carton or a pallet level, provide them at the corresponding ca"""
    container_type: Literal['carton', 'pallet'] = Field(alias="containerType")
    container_sequence_number: str | None = Field(default=None, alias="containerSequenceNumber")
    container_identifiers: list[ContainerIdentification] = Field(alias="containerIdentifiers")
    tracking_number: str | None = Field(default=None, alias="trackingNumber")
    dimensions: Dimensions | None = Field(default=None)
    weight: Weight | None = Field(default=None)
    tier: int | None = Field(default=None)
    block: int | None = Field(default=None)
    inner_containers_details: InnerContainersDetails | None = Field(default=None, alias="innerContainersDetails")
    packed_items: list[PackedItems] | None = Field(default=None, alias="packedItems")
    def __init__(self, **data: Any) -> None: ...

class CarrierDetails(BaseModel):
    """Indicates the carrier details and their contact informations"""
    name: str | None = Field(default=None)
    code: str | None = Field(default=None)
    phone: str | None = Field(default=None)
    email: str | None = Field(default=None)
    shipment_reference_number: str | None = Field(default=None, alias="shipmentReferenceNumber")
    def __init__(self, **data: Any) -> None: ...

class TransportationDetails(BaseModel):
    """Transportation details for this shipment."""
    ship_mode: Literal['TruckLoad', 'LessThanTruckLoad', 'SmallParcel'] | None = Field(default=None, alias="shipMode")
    transportation_mode: Literal['Road', 'Air', 'Ocean'] | None = Field(default=None, alias="transportationMode")
    shipped_date: datetime.datetime | None = Field(default=None, alias="shippedDate")
    estimated_delivery_date: datetime.datetime | None = Field(default=None, alias="estimatedDeliveryDate")
    shipment_delivery_date: datetime.datetime | None = Field(default=None, alias="shipmentDeliveryDate")
    carrier_details: CarrierDetails | None = Field(default=None, alias="carrierDetails")
    bill_of_lading_number: str | None = Field(default=None, alias="billOfLadingNumber")
    def __init__(self, **data: Any) -> None: ...

class Shipment(BaseModel):
    """A list of one or more shipments with respective details."""
    vendor_shipment_identifier: str = Field(alias="vendorShipmentIdentifier")
    transaction_type: Literal['New', 'Cancel'] = Field(alias="transactionType")
    buyer_reference_number: str | None = Field(default=None, alias="buyerReferenceNumber")
    transaction_date: datetime.datetime = Field(alias="transactionDate")
    current_shipment_status: Literal['Created', 'TransportationRequested', 'CarrierAssigned', 'Shipped'] | None = Field(default=None, alias="currentShipmentStatus")
    currentshipment_status_date: datetime.datetime | None = Field(default=None, alias="currentshipmentStatusDate")
    shipment_status_details: list[ShipmentStatusDetails] | None = Field(default=None, alias="shipmentStatusDetails")
    shipment_create_date: datetime.datetime | None = Field(default=None, alias="shipmentCreateDate")
    shipment_confirm_date: datetime.datetime | None = Field(default=None, alias="shipmentConfirmDate")
    package_label_create_date: datetime.datetime | None = Field(default=None, alias="packageLabelCreateDate")
    shipment_freight_term: Literal['Collect', 'Prepaid'] | None = Field(default=None, alias="shipmentFreightTerm")
    selling_party: PartyIdentification = Field(alias="sellingParty")
    ship_from_party: PartyIdentification = Field(alias="shipFromParty")
    ship_to_party: PartyIdentification = Field(alias="shipToParty")
    shipment_measurements: TransportShipmentMeasurements | None = Field(default=None, alias="shipmentMeasurements")
    collect_freight_pickup_details: CollectFreightPickupDetails | None = Field(default=None, alias="collectFreightPickupDetails")
    purchase_orders: list[PurchaseOrders] | None = Field(default=None, alias="purchaseOrders")
    import_details: ImportDetails | None = Field(default=None, alias="importDetails")
    containers: list[Containers] | None = Field(default=None)
    transportation_details: TransportationDetails | None = Field(default=None, alias="transportationDetails")
    def __init__(self, **data: Any) -> None: ...

class SubmitShipments(BaseModel):
    """The request schema for the SubmitShipments operation."""
    shipments: list[Shipment] | None = Field(default=None)
    def __init__(self, **data: Any) -> None: ...

class Pagination(BaseModel):
    """The pagination elements required to retrieve the remaining data."""
    next_token: str | None = Field(default=None, alias="nextToken")
    def __init__(self, **data: Any) -> None: ...

class ShipmentDetails(BaseModel):
    """The request schema for the GetShipmentDetails operation."""
    pagination: Pagination | None = Field(default=None)
    shipments: list[Shipment] | None = Field(default=None)
    def __init__(self, **data: Any) -> None: ...

class Error(BaseModel):
    """Error response returned when the request is unsuccessful."""
    code: str
    message: str
    details: str | None = Field(default=None)
    def __init__(self, **data: Any) -> None: ...

class GetShipmentDetailsResponse(BaseModel):
    """The response schema for the GetShipmentDetails operation."""
    payload: ShipmentDetails | None = Field(default=None)
    errors: ErrorList | None = Field(default=None)
    def __init__(self, **data: Any) -> None: ...

class VendorDetails(BaseModel):
    """Vendor Details as part of Label response."""
    selling_party: PartyIdentification | None = Field(default=None, alias="sellingParty")
    vendor_shipment_identifier: str | None = Field(default=None, alias="vendorShipmentIdentifier")
    def __init__(self, **data: Any) -> None: ...

class ShipmentInformation(BaseModel):
    """Shipment Information details for Label request."""
    vendor_details: VendorDetails | None = Field(default=None, alias="vendorDetails")
    buyer_reference_number: str | None = Field(default=None, alias="buyerReferenceNumber")
    ship_to_party: PartyIdentification | None = Field(default=None, alias="shipToParty")
    ship_from_party: PartyIdentification | None = Field(default=None, alias="shipFromParty")
    warehouse_id: str | None = Field(default=None, alias="warehouseId")
    master_tracking_id: str | None = Field(default=None, alias="masterTrackingId")
    total_label_count: int | None = Field(default=None, alias="totalLabelCount")
    ship_mode: Literal['SmallParcel', 'LTL'] | None = Field(default=None, alias="shipMode")
    def __init__(self, **data: Any) -> None: ...

class LabelData(BaseModel):
    """Label details as part of the transport label response"""
    label_sequence_number: int | None = Field(default=None, alias="labelSequenceNumber")
    label_format: Literal['PDF'] | None = Field(default=None, alias="labelFormat")
    carrier_code: str | None = Field(default=None, alias="carrierCode")
    tracking_id: str | None = Field(default=None, alias="trackingId")
    label: str | None = Field(default=None)
    def __init__(self, **data: Any) -> None: ...

class TransportLabel(BaseModel):
    """A list of one or more ShipmentLabels."""
    label_create_date_time: datetime.datetime | None = Field(default=None, alias="labelCreateDateTime")
    shipment_information: ShipmentInformation | None = Field(default=None, alias="shipmentInformation")
    label_data: list[LabelData] | None = Field(default=None, alias="labelData")
    def __init__(self, **data: Any) -> None: ...

class TransportationLabels(BaseModel):
    """The request schema for the GetShipmentLabels operation."""
    pagination: Pagination | None = Field(default=None)
    transport_labels: list[TransportLabel] | None = Field(default=None, alias="transportLabels")
    def __init__(self, **data: Any) -> None: ...

class GetShipmentLabels(BaseModel):
    """The response schema for the GetShipmentLabels operation."""
    payload: TransportationLabels | None = Field(default=None)
    errors: ErrorList | None = Field(default=None)
    def __init__(self, **data: Any) -> None: ...

class TransactionReference(BaseModel):
    """The response payload for the SubmitShipmentConfirmations operation."""
    transaction_id: str | None = Field(default=None, alias="transactionId")
    def __init__(self, **data: Any) -> None: ...

class SubmitShipmentConfirmationsResponse(BaseModel):
    """The response schema for the SubmitShipmentConfirmations operation."""
    payload: TransactionReference | None = Field(default=None)
    errors: ErrorList | None = Field(default=None)
    def __init__(self, **data: Any) -> None: ...

# raw-mode shapes (``raw=True``)

class TransportationDetailsForShipmentConfirmationDict(TypedDict, total=False):
    carrierScac: str
    carrierShipmentReferenceNumber: str
    transportationMode: Literal['Road', 'Air', 'Ocean']
    billOfLadingNumber: str

class AddressDict(TypedDict, total=False):
    name: str
    addressLine1: str
    addressLine2: str
    addressLine3: str
    city: str
    county: str
    district: str
    stateOrRegion: str
    postalCode: str
    countryCode: str
    phone: str

class TaxRegistrationDetailsDict(TypedDict, total=False):
    taxRegistrationType: Literal['VAT', 'GST']
    taxRegistrationNumber: str

class PartyIdentificationDict(TypedDict, total=False):
    address: AddressDict
    partyId: str
    taxRegistrationDetails: list[TaxRegistrationDetailsDict]

class WeightDict(TypedDict, total=False):
    unitOfMeasure: Literal['G', 'Kg', 'Oz', 'Lb']
    value: Decimal

class VolumeDict(TypedDict, total=False):
    unitOfMeasure: Literal['CuFt', 'CuIn', 'CuM', 'CuY']
    value: Decimal

class ShipmentMeasurementsDict(TypedDict, total=False):
    grossShipmentWeight: WeightDict
    shipmentVolume: VolumeDict
    cartonCount: int
    palletCount: int

class LocationDict(TypedDict, total=False):
    type: str
    locationCode: str
    countryCode: str

class StopDict(TypedDict, total=False):
    functionCode: Literal['PortOfDischarge', 'FreightPayableAt', 'PortOfLoading']
    locationIdentification: LocationDict
    arrivalTime: datetime.datetime
    departureTime: datetime.datetime

class RouteDict(TypedDict, total=False):
    stops: list[StopDict]

class ImportDetailsDict(TypedDict, total=False):
    methodOfPayment: Literal['PaidByBuyer', 'CollectOnDelivery', 'DefinedByBuyerAndSeller', 'FOBPortOfCall', 'PrepaidBySeller', 'PaidBySeller']
    sealNumber: str
    route: RouteDict
    importContainers: str
    billableWeight: WeightDict
    estimatedShipByDate: datetime.datetime
    handlingInstructions: Literal['Oversized', 'Fragile', 'Food', 'HandleWithCare']

class TotalWeightDict(TypedDict, total=False):
    unitOfMeasure: Literal['POUNDS', 'OUNCES', 'GRAMS', 'KILOGRAMS']
    amount: Decimal

class ItemQuantityDict(TypedDict, total=False):
    amount: int
    unitOfMeasure: Literal['Cases', 'Eaches']
    unitSize: int
    totalWeight: TotalWeightDict

class RegulationReferencesDict(TypedDict, total=False):
    dueDiligenceReference: str
    dueDiligenceVerification: str
    dueDiligenceInformation: str
    dueDiligenceExemptionCode: str

class DurationDict(TypedDict, total=False):
    durationUnit: Literal['Days', 'Months']
    durationValue: int

class ExpiryDict(TypedDict, total=False):
    manufacturerDate: datetime.datetime
    expiryDate: datetime.datetime
    expiryAfterDuration: DurationDict

class MoneyDict(TypedDict, total=False):
    currencyCode: str
    amount: Decimal

class ItemDetailsDict(TypedDict, total=False):
    purchaseOrderNumber: str
    lotNumber: str
    lotNumberSourceReference: str
    lotNumberSourceType: Literal['GLN', 'FFRN', 'USDA_E', 'URL']
    countryOfOrigin: str
    regulationReferences: RegulationReferencesDict
    expiry: ExpiryDict
    maximumRetailPrice: MoneyDict
    handlingCode: Literal['Oversized', 'Fragile', 'Food', 'HandleWithCare']

class ItemDict(TypedDict, total=False):
    itemSequenceNumber: str
    amazonProductIdentifier: str
    vendorProductIdentifier: str
    shippedQuantity: ItemQuantityDict
    itemDetails: ItemDetailsDict

class ContainerIdentificationDict(TypedDict, total=False):
    containerIdentificationType: Literal['SSCC', 'AMZNCC', 'GTIN', 'BPS', 'CID']
    containerIdentificationNumber: str

class DimensionsDict(TypedDict, total=False):
    length: Decimal
    width: Decimal
    height: Decimal
    unitOfMeasure: Literal['In', 'Ft', 'Meter', 'Yard']

class ContainerItemDict(TypedDict, total=False):
    itemReference: str
    shippedQuantity: ItemQuantityDict
    itemDetails: ItemDetailsDict

class CartonDict(TypedDict, total=False):
    cartonIdentifiers: list[ContainerIdentificationDict]
    cartonSequenceNumber: str
    dimensions: DimensionsDict
    weight: WeightDict
    trackingNumber: str
    items: list[ContainerItemDict]

class CartonReferenceDetailsDict(TypedDict, total=False):
    cartonCount: int
    cartonReferenceNumbers: list[str]

class PalletDict(TypedDict, total=False):
    palletIdentifiers: list[ContainerIdentificationDict]
    tier: int
    block: int
    dimensions: DimensionsDict
    weight: WeightDict
    cartonReferenceDetails: CartonReferenceDetailsDict
    items: list[ContainerItemDict]

class ShipmentConfirmationDict(TypedDict, total=False):
    shipmentIdentifier: str
    shipmentConfirmationType: Literal['Original', 'Replace']
    shipmentType: Literal['TruckLoad', 'LessThanTruckLoad', 'SmallParcel']
    shipmentStructure: Literal['PalletizedAssortmentCase', 'LooseAssortmentCase', 'PalletOfItems', 'PalletizedStandardCase', 'LooseStandardCase', 'MasterPallet', 'MasterCase']
    transportationDetails: TransportationDetailsForShipmentConfirmationDict
    amazonReferenceNumber: str
    shipmentConfirmationDate: datetime.datetime
    shippedDate: datetime.datetime
    estimatedDeliveryDate: datetime.datetime
    sellingParty: PartyIdentificationDict
    shipFromParty: PartyIdentificationDict
    shipToParty: PartyIdentificationDict
    shipmentMeasurements: ShipmentMeasurementsDict
    importDetails: ImportDetailsDict
    shippedItems: list[ItemDict]
    cartons: list[CartonDict]
    pallets: list[PalletDict]

class SubmitShipmentConfirmationsRequestDict(TypedDict, total=False):
    shipmentConfirmations: list[ShipmentConfirmationDict]

class ShipmentStatusDetailsDict(TypedDict, total=False):
    shipmentStatus: Literal['Created', 'TransportationRequested', 'CarrierAssigned', 'Shipped']
    shipmentStatusDate: datetime.datetime

class TransportShipmentMeasurementsDict(TypedDict, total=False):
    totalCartonCount: int
    totalPalletStackable: int
    totalPalletNonStackable: int
    shipmentWeight: WeightDict
    shipmentVolume: VolumeDict

class CollectFreightPickupDetailsDict(TypedDict, total=False):
    requestedPickUp: datetime.datetime
    scheduledPickUp: datetime.datetime
    carrierAssignmentDate: datetime.datetime

class PurchaseOrderItemsDict(TypedDict, total=False):
    itemSequenceNumber: str
    buyerProductIdentifier: str
    vendorProductIdentifier: str
    shippedQuantity: ItemQuantityDict
    maximumRetailPrice: MoneyDict

class PurchaseOrdersDict(TypedDict, total=False):
    purchaseOrderNumber: str
    purchaseOrderDate: datetime.datetime
    shipWindow: str
    items: list[PurchaseOrderItemsDict]

class ContainerSequenceNumbersDict(TypedDict, total=False):
    containerSequenceNumber: str

class InnerContainersDetailsDict(TypedDict, total=False):
    containerCount: int
    containerSequenceNumbers: list[ContainerSequenceNumbersDict]

class PackageItemDetailsDict(TypedDict, total=False):
    purchaseOrderNumber: str
    lotNumber: str
    expiry: ExpiryDict

class PackedItemsDict(TypedDict, total=False):
    itemSequenceNumber: str
    buyerProductIdentifier: str
    vendorProductIdentifier: str
    packedQuantity: ItemQuantityDict
    itemDetails: PackageItemDetailsDict

class ContainersDict(TypedDict, total=False):
    containerType: Literal['carton', 'pallet']
    containerSequenceNumber: str
    containerIdentifiers: list[ContainerIdentificationDict]
    trackingNumber: str
    dimensions: DimensionsDict
    weight: WeightDict
    tier: int
    block: int
    innerContainersDetails: InnerContainersDetailsDict
    packedItems: list[PackedItemsDict]

class CarrierDetailsDict(TypedDict, total=False):
    name: str
    code: str
    phone: str
    email: str
    shipmentReferenceNumber: str

class TransportationDetailsDict(TypedDict, total=False):
    shipMode: Literal['TruckLoad', 'LessThanTruckLoad', 'SmallParcel']
    transportationMode: Literal['Road', 'Air', 'Ocean']
    shippedDate: datetime.datetime
    estimatedDeliveryDate: datetime.datetime
    shipmentDeliveryDate: datetime.datetime
    carrierDetails: CarrierDetailsDict
    billOfLadingNumber: str

class ShipmentDict(TypedDict, total=False):
    vendorShipmentIdentifier: str
    transactionType: Literal['New', 'Cancel']
    buyerReferenceNumber: str
    transactionDate: datetime.datetime
    currentShipmentStatus: Literal['Created', 'TransportationRequested', 'CarrierAssigned', 'Shipped']
    currentshipmentStatusDate: datetime.datetime
    shipmentStatusDetails: list[ShipmentStatusDetailsDict]
    shipmentCreateDate: datetime.datetime
    shipmentConfirmDate: datetime.datetime
    packageLabelCreateDate: datetime.datetime
    shipmentFreightTerm: Literal['Collect', 'Prepaid']
    sellingParty: PartyIdentificationDict
    shipFromParty: PartyIdentificationDict
    shipToParty: PartyIdentificationDict
    shipmentMeasurements: TransportShipmentMeasurementsDict
    collectFreightPickupDetails: CollectFreightPickupDetailsDict
    purchaseOrders: list[PurchaseOrdersDict]
    importDetails: ImportDetailsDict
    containers: list[ContainersDict]
    transportationDetails: TransportationDetailsDict

class SubmitShipmentsDict(TypedDict, total=False):
    shipments: list[ShipmentDict]

class PaginationDict(TypedDict, total=False):
    nextToken: str

class ShipmentDetailsDict(TypedDict, total=False):
    pagination: PaginationDict
    shipments: list[ShipmentDict]

class ErrorDict(TypedDict, total=False):
    code: str
    message: str
    details: str

class GetShipmentDetailsResponseDict(TypedDict, total=False):
    payload: ShipmentDetailsDict
    errors: ErrorList

class VendorDetailsDict(TypedDict, total=False):
    sellingParty: PartyIdentificationDict
    vendorShipmentIdentifier: str

class ShipmentInformationDict(TypedDict, total=False):
    vendorDetails: VendorDetailsDict
    buyerReferenceNumber: str
    shipToParty: PartyIdentificationDict
    shipFromParty: PartyIdentificationDict
    warehouseId: str
    masterTrackingId: str
    totalLabelCount: int
    shipMode: Literal['SmallParcel', 'LTL']

class LabelDataDict(TypedDict, total=False):
    labelSequenceNumber: int
    labelFormat: Literal['PDF']
    carrierCode: str
    trackingId: str
    label: str

class TransportLabelDict(TypedDict, total=False):
    labelCreateDateTime: datetime.datetime
    shipmentInformation: ShipmentInformationDict
    labelData: list[LabelDataDict]

class TransportationLabelsDict(TypedDict, total=False):
    pagination: PaginationDict
    transportLabels: list[TransportLabelDict]

class GetShipmentLabelsDict(TypedDict, total=False):
    payload: TransportationLabelsDict
    errors: ErrorList

class TransactionReferenceDict(TypedDict, total=False):
    transactionId: str

class SubmitShipmentConfirmationsResponseDict(TypedDict, total=False):
    payload: TransactionReferenceDict
    errors: ErrorList

# type aliases
Decimal = str
ErrorList = list[Error]
