"""Operations of tracking v2026_01_30 (The Selling Partner API for tracking services provided by Amazon.).

Generated by codegen/ (oagen) from the pinned spec; do not edit by hand.
"""

from __future__ import annotations

from amzn_selling_partner.models.tracking import v2026_01_30 as models
from amzn_selling_partner.runtime._op import Op, header, json_decoder, query
from amzn_selling_partner.runtime._pagination import Pagination
from amzn_selling_partner.runtime._resources import AsyncResource, SyncResource
from amzn_selling_partner.runtime._types import NOT_GIVEN, NotGiven, RequestOptions

_op_get_shipment_tracking_d1 = json_decoder(lambda: models.GetShipmentTrackingResponse)
_op_get_shipment_tracking_d2 = json_decoder(lambda: models.ErrorList)
_op_get_shipment_tracking = Op(
    key="tracking.v2026_01_30.getShipmentTracking",
    name="get_shipment_tracking",
    operation_id="getShipmentTracking",
    api="tracking",
    version="v2026_01_30",
    method="GET",
    path="/tracking/2026-01-30/shipments/track",
    url_template="/tracking/2026-01-30/shipments/track",
    path_params=(),
    query_params=(
        query("id", "id"),
        query("acsin", "acsin"),
        query("aftn", "aftn"),
        query("container_number", "containerNumber"),
        query("house_bill_of_lading_number", "houseBillOfLadingNumber"),
        query("carrier_tracking_tracking_number", "carrierTracking.trackingNumber"),
        query("carrier_tracking_carrier_code", "carrierTracking.carrierCode"),
    ),
    header_params=(header("accept_language", "Accept-Language"),),
    default_decoder=_op_get_shipment_tracking_d1,
    error_decoders={
        400: _op_get_shipment_tracking_d2,
        401: _op_get_shipment_tracking_d2,
        403: _op_get_shipment_tracking_d2,
        404: _op_get_shipment_tracking_d2,
        413: _op_get_shipment_tracking_d2,
        415: _op_get_shipment_tracking_d2,
        429: _op_get_shipment_tracking_d2,
        500: _op_get_shipment_tracking_d2,
        503: _op_get_shipment_tracking_d2,
    },
    default_error=_op_get_shipment_tracking_d2,
    doc="Get tracking information for the shipment.\n\nReturns tracking information for a shipment.\n\nGET /tracking/2026-01-30/shipments/track",
)


class TrackingV20260130(SyncResource):
    """Sync resource for tracking v2026_01_30."""

    __slots__ = ()
    _resource_name = "tracking.v2026_01_30"
    models = models
    _ops = {"get_shipment_tracking": _op_get_shipment_tracking}

    def get_shipment_tracking(
        self,
        *,
        id: str | NotGiven = NOT_GIVEN,
        acsin: str | NotGiven = NOT_GIVEN,
        aftn: str | NotGiven = NOT_GIVEN,
        container_number: str | NotGiven = NOT_GIVEN,
        house_bill_of_lading_number: str | NotGiven = NOT_GIVEN,
        carrier_tracking_tracking_number: str | NotGiven = NOT_GIVEN,
        carrier_tracking_carrier_code: str | NotGiven = NOT_GIVEN,
        accept_language: str | NotGiven = NOT_GIVEN,
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.GetShipmentTrackingResponse:
        """Get tracking information for the shipment.

        Returns tracking information for a shipment.

        GET /tracking/2026-01-30/shipments/track
        """
        return self._client.call(
            _op_get_shipment_tracking,
            {
                "id": id,
                "acsin": acsin,
                "aftn": aftn,
                "container_number": container_number,
                "house_bill_of_lading_number": house_bill_of_lading_number,
                "carrier_tracking_tracking_number": carrier_tracking_tracking_number,
                "carrier_tracking_carrier_code": carrier_tracking_carrier_code,
                "accept_language": accept_language,
            },
            raw,
            paginate,
            request_options,
        )


class AsyncTrackingV20260130(AsyncResource):
    """Async resource for tracking v2026_01_30."""

    __slots__ = ()
    _resource_name = "tracking.v2026_01_30"
    models = models
    _ops = {"get_shipment_tracking": _op_get_shipment_tracking}

    async def get_shipment_tracking(
        self,
        *,
        id: str | NotGiven = NOT_GIVEN,
        acsin: str | NotGiven = NOT_GIVEN,
        aftn: str | NotGiven = NOT_GIVEN,
        container_number: str | NotGiven = NOT_GIVEN,
        house_bill_of_lading_number: str | NotGiven = NOT_GIVEN,
        carrier_tracking_tracking_number: str | NotGiven = NOT_GIVEN,
        carrier_tracking_carrier_code: str | NotGiven = NOT_GIVEN,
        accept_language: str | NotGiven = NOT_GIVEN,
        raw: bool = False,
        paginate: Pagination | None | NotGiven = NOT_GIVEN,
        request_options: RequestOptions | None = None,
    ) -> models.GetShipmentTrackingResponse:
        """Get tracking information for the shipment.

        Returns tracking information for a shipment.

        GET /tracking/2026-01-30/shipments/track
        """
        return await self._client.call(
            _op_get_shipment_tracking,
            {
                "id": id,
                "acsin": acsin,
                "aftn": aftn,
                "container_number": container_number,
                "house_bill_of_lading_number": house_bill_of_lading_number,
                "carrier_tracking_tracking_number": carrier_tracking_tracking_number,
                "carrier_tracking_carrier_code": carrier_tracking_carrier_code,
                "accept_language": accept_language,
            },
            raw,
            paginate,
            request_options,
        )


__all__ = ["AsyncTrackingV20260130", "TrackingV20260130"]
