"""Models for listings_items v2020_09_01 (Selling Partner API for Listings Items).

Generated by codegen/ (oagen) from the pinned spec; do not edit by hand.
"""

from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import Field

from amzn_selling_partner.runtime._models import SpecModel

IssueSeverity: TypeAlias = Literal["ERROR", "WARNING", "INFO"]
ListingsItemPutRequestRequirements: TypeAlias = Literal["LISTING", "LISTING_PRODUCT_ONLY", "LISTING_OFFER_ONLY"]
ListingsItemSubmissionResponseStatus: TypeAlias = Literal["ACCEPTED", "INVALID"]
PatchOperationOp: TypeAlias = Literal["add", "replace", "delete"]


class Error(SpecModel):
    """Error response returned when the request is unsuccessful."""

    code: str
    message: str
    details: str | None = None


class ErrorList(SpecModel):
    """A list of error responses returned when a request is unsuccessful."""

    errors: list[Error]


class Issue(SpecModel):
    """An issue with a listings item."""

    code: str
    message: str
    severity: IssueSeverity
    attribute_name: str | None = Field(default=None, alias="attributeName")


class ListingsItemPatchRequest(SpecModel):
    """The request body schema for the patchListingsItem operation."""

    product_type: str = Field(alias="productType")
    patches: list[PatchOperation]


class ListingsItemPutRequest(SpecModel):
    """The request body schema for the putListingsItem operation."""

    product_type: str = Field(alias="productType")
    requirements: ListingsItemPutRequestRequirements | None = None
    attributes: dict[str, Any]


class ListingsItemSubmissionResponse(SpecModel):
    """Response containing the results of a submission to the Selling Partner API for Listings Items."""

    sku: str
    status: ListingsItemSubmissionResponseStatus
    submission_id: str = Field(alias="submissionId")
    issues: list[Issue] | None = None


class PatchOperation(SpecModel):
    """Individual JSON Patch operation for an HTTP PATCH request."""

    op: PatchOperationOp
    path: str
    value: list[dict[str, Any]] | None = None


__all__ = [
    "Error",
    "ErrorList",
    "Issue",
    "IssueSeverity",
    "ListingsItemPatchRequest",
    "ListingsItemPutRequest",
    "ListingsItemPutRequestRequirements",
    "ListingsItemSubmissionResponse",
    "ListingsItemSubmissionResponseStatus",
    "PatchOperation",
    "PatchOperationOp",
]
