# Auto-generated by oagen. Do not edit.

"""Models of tracking_v2026_01_30.

Auto-generated by oagen from the OpenAPI spec; do not edit by hand.
"""

from __future__ import annotations

from pydantic import Field

from .._base import SpecModel
from .enums import TrackingMilestoneStatusCode, TrackingMilestoneStatusSubCode


class BoundedInterval(SpecModel):
    """A time interval defined by a start time and end time."""

    start_time: str = Field(alias="startTime")
    end_time: str = Field(alias="endTime")


class CarrierTracking(SpecModel):
    """The carrier information."""

    tracking_number: str = Field(alias="trackingNumber")
    carrier_code: str | None = Field(default=None, alias="carrierCode")


class Error(SpecModel):
    """Error response returned when the request is unsuccessful."""

    code: str
    message: str
    details: str | None = None


class ErrorList(SpecModel):
    """A list of errors for an unsuccessful request."""

    errors: list[Error]


class GetShipmentTrackingResponse(SpecModel):
    """Contains tracking details for a requested shipment."""

    tracking_detail: TrackingDetail = Field(alias="trackingDetail")


class TrackingDetail(SpecModel):
    """Tracking information for the shipment identifier."""

    identifier: TrackingIdentifier
    milestone_history: list[TrackingMilestone] = Field(alias="milestoneHistory")
    tracking_url: str | None = Field(default=None, alias="trackingUrl")
    tracking_estimates: list[TrackingEstimate] | None = Field(default=None, alias="trackingEstimates")
    latest_milestone: TrackingMilestone | None = Field(default=None, alias="latestMilestone")


class TrackingEstimate(SpecModel):
    """A time-based estimate for the shipment, such as estimated delivery date."""

    type_: str = Field(alias="type")
    estimated_interval: BoundedInterval = Field(alias="estimatedInterval")
    last_updated_time: str = Field(alias="lastUpdatedTime")


class TrackingIdentifier(SpecModel):
    """The identifier to track a shipment."""

    id: str | None = None
    carrier_tracking: CarrierTracking | None = Field(default=None, alias="carrierTracking")
    acsin: str | None = None
    aftn: str | None = None
    container_number: str | None = Field(default=None, alias="containerNumber")
    house_bill_of_lading_number: str | None = Field(default=None, alias="houseBillOfLadingNumber")


class TrackingMilestone(SpecModel):
    """A single milestone event in a shipment's journey."""

    status: TrackingMilestoneStatus
    occurred_at: str = Field(alias="occurredAt")
    location: TrackingMilestoneLocation | None = None


class TrackingMilestoneAddress(SpecModel):
    """The physical address of the location."""

    city: str | None = None
    region: str | None = None
    country_code: str | None = Field(default=None, alias="countryCode")


class TrackingMilestoneLocation(SpecModel):
    """The location where a tracking milestone occurred."""

    address: TrackingMilestoneAddress | None = None


class TrackingMilestoneStatus(SpecModel):
    """The status codes and description of the milestone event."""

    code: TrackingMilestoneStatusCode
    description: str
    sub_code: TrackingMilestoneStatusSubCode | None = Field(default=None, alias="subCode")


__all__ = [
    "BoundedInterval",
    "CarrierTracking",
    "Error",
    "ErrorList",
    "GetShipmentTrackingResponse",
    "TrackingDetail",
    "TrackingEstimate",
    "TrackingIdentifier",
    "TrackingMilestone",
    "TrackingMilestoneAddress",
    "TrackingMilestoneLocation",
    "TrackingMilestoneStatus",
    "TrackingMilestoneStatusCode",
    "TrackingMilestoneStatusSubCode",
]
