# Generated by `python -m spapi.stubgen`; do not edit.
from __future__ import annotations
import datetime
from typing import Any, Literal, TypedDict

from pydantic import BaseModel, Field

class Address(BaseModel):
    """Shipping address that represents the origin or destination location."""
    address_line1: str = Field(alias="addressLine1")
    address_line2: str | None = Field(default=None, alias="addressLine2")
    address_line3: str | None = Field(default=None, alias="addressLine3")
    city: str | None = Field(default=None)
    country_code: str = Field(alias="countryCode")
    county: str | None = Field(default=None)
    district: str | None = Field(default=None)
    name: str
    phone_number: str | None = Field(default=None, alias="phoneNumber")
    postal_code: str | None = Field(default=None, alias="postalCode")
    state_or_region: str = Field(alias="stateOrRegion")
    def __init__(self, **data: Any) -> None: ...

class CarrierCode(BaseModel):
    """Identifies the carrier that will deliver the shipment."""
    carrier_code_type: CarrierCodeType | None = Field(default=None, alias="carrierCodeType")
    carrier_code_value: str | None = Field(default=None, alias="carrierCodeValue")
    def __init__(self, **data: Any) -> None: ...

class DestinationDetails(BaseModel):
    """Destination details of an inbound order based on the assigned region and DC for the order."""
    destination_address: Address | None = Field(default=None, alias="destinationAddress")
    destination_region: str | None = Field(default=None, alias="destinationRegion")
    shipment_id: str | None = Field(default=None, alias="shipmentId")
    def __init__(self, **data: Any) -> None: ...

class DistributionIneligibleReason(BaseModel):
    """Execution errors associated with the replenishment order. This field will be populated if the order failed validation."""
    failure_code: str = Field(alias="failureCode")
    failure_reasons: list[str] = Field(alias="failureReasons")
    sku: str | None = Field(default=None)
    def __init__(self, **data: Any) -> None: ...

class DistributionPackageQuantity(BaseModel):
    """Represents a distribution package with its respective quantity."""
    count: int
    distribution_package: DistributionPackage = Field(alias="distributionPackage")
    def __init__(self, **data: Any) -> None: ...

class ProductAttribute(BaseModel):
    """Product instance attribute that is not described at the SKU level in the catalog."""
    name: str | None = Field(default=None)
    value: str | None = Field(default=None)
    def __init__(self, **data: Any) -> None: ...

class PrepInstruction(BaseModel):
    """Information pertaining to the preparation of inbound products."""
    prep_owner: PrepOwner | None = Field(default=None, alias="prepOwner")
    prep_type: str | None = Field(default=None, alias="prepType")
    def __init__(self, **data: Any) -> None: ...

class PrepDetails(BaseModel):
    """The preparation details for a product. This contains the prep category, prep owner, and label owner."""
    label_owner: LabelOwner | None = Field(default=None, alias="labelOwner")
    prep_category: PrepCategory | None = Field(default=None, alias="prepCategory")
    prep_instructions: list[PrepInstruction] | None = Field(default=None, alias="prepInstructions")
    prep_owner: PrepOwner | None = Field(default=None, alias="prepOwner")
    def __init__(self, **data: Any) -> None: ...

class ProductQuantity(BaseModel):
    """Represents a product with the SKU details and the corresponding quantity."""
    attributes: list[ProductAttribute] | None = Field(default=None)
    quantity: int
    sku: str
    expiration: datetime.datetime | None = Field(default=None)
    prep_details: PrepDetails | None = Field(default=None, alias="prepDetails")
    def __init__(self, **data: Any) -> None: ...

class DistributionPackageContents(BaseModel):
    """Represents the contents inside a package, which can be products or a nested package."""
    packages: list[DistributionPackageQuantity] | None = Field(default=None)
    products: list[ProductQuantity] | None = Field(default=None)
    def __init__(self, **data: Any) -> None: ...

class PackageDimensions(BaseModel):
    """Dimensions of the package."""
    height: float
    length: float
    unit_of_measurement: DimensionUnitOfMeasurement = Field(alias="unitOfMeasurement")
    width: float
    def __init__(self, **data: Any) -> None: ...

class PackageVolume(BaseModel):
    """Represents the volume of the package with a unit of measurement."""
    unit_of_measurement: VolumeUnitOfMeasurement = Field(alias="unitOfMeasurement")
    volume: float
    def __init__(self, **data: Any) -> None: ...

class PackageWeight(BaseModel):
    """Represents the weight of the package with a unit of measurement."""
    unit_of_measurement: WeightUnitOfMeasurement = Field(alias="unitOfMeasurement")
    weight: float
    def __init__(self, **data: Any) -> None: ...

class MeasurementData(BaseModel):
    """Package weight and dimension."""
    dimensions: PackageDimensions | None = Field(default=None)
    volume: PackageVolume | None = Field(default=None)
    weight: PackageWeight
    def __init__(self, **data: Any) -> None: ...

class DistributionPackage(BaseModel):
    """Represents an AWD distribution package."""
    contents: DistributionPackageContents
    measurements: MeasurementData
    type: DistributionPackageType
    def __init__(self, **data: Any) -> None: ...

class DistributionProduct(BaseModel):
    """Represents a product with sku details and corresponding quantity"""
    attributes: list[ProductAttribute] | None = Field(default=None)
    quantity: int
    sku: str
    def __init__(self, **data: Any) -> None: ...

class Error(BaseModel):
    """Error response returned when the request is unsuccessful."""
    code: str
    details: str | None = Field(default=None)
    message: str
    def __init__(self, **data: Any) -> None: ...

class ErrorList(BaseModel):
    """This exception is thrown when client inputs are invalid."""
    errors: list[Error]
    def __init__(self, **data: Any) -> None: ...

class OrderIneligibilityReason(BaseModel):
    """Represents one ineligibility reason for the order (there can be multiple reasons)."""
    code: str
    description: str
    def __init__(self, **data: Any) -> None: ...

class SkuIneligibilityReason(BaseModel):
    """Represents the ineligibility reason for one SKU."""
    code: str
    description: str
    def __init__(self, **data: Any) -> None: ...

class SkuEligibility(BaseModel):
    """Represents eligibility of one SKU."""
    ineligibility_reasons: list[SkuIneligibilityReason] | None = Field(default=None, alias="ineligibilityReasons")
    package_quantity: DistributionPackageQuantity = Field(alias="packageQuantity")
    status: InboundEligibilityStatus
    def __init__(self, **data: Any) -> None: ...

class InboundEligibility(BaseModel):
    """Represents the eligibility status of the inbound packages."""
    ineligibility_reasons: list[OrderIneligibilityReason] | None = Field(default=None, alias="ineligibilityReasons")
    packages_to_inbound: list[SkuEligibility] = Field(alias="packagesToInbound")
    previewed_at: datetime.datetime = Field(alias="previewedAt")
    status: InboundEligibilityStatus
    def __init__(self, **data: Any) -> None: ...

class InboundPreferences(BaseModel):
    """Preferences that can be passed in context of an inbound order"""
    destination_region: str | None = Field(default=None, alias="destinationRegion")
    def __init__(self, **data: Any) -> None: ...

class InboundOrder(BaseModel):
    """Represents an AWD inbound order."""
    created_at: datetime.datetime = Field(alias="createdAt")
    destination_details: DestinationDetails | None = Field(default=None, alias="destinationDetails")
    external_reference_id: str | None = Field(default=None, alias="externalReferenceId")
    order_id: str = Field(alias="orderId")
    order_status: InboundStatus = Field(alias="orderStatus")
    origin_address: Address = Field(alias="originAddress")
    packages_to_inbound: list[DistributionPackageQuantity] = Field(alias="packagesToInbound")
    preferences: InboundPreferences | None = Field(default=None)
    updated_at: datetime.datetime | None = Field(default=None, alias="updatedAt")
    def __init__(self, **data: Any) -> None: ...

class InboundOrderCreationData(BaseModel):
    """Payload for creating an inbound order."""
    external_reference_id: str | None = Field(default=None, alias="externalReferenceId")
    origin_address: Address = Field(alias="originAddress")
    packages_to_inbound: list[DistributionPackageQuantity] = Field(alias="packagesToInbound")
    preferences: InboundPreferences | None = Field(default=None)
    def __init__(self, **data: Any) -> None: ...

class InboundOrderReference(BaseModel):
    """A response that contains the reference identifiers for the newly created or updated inbound order. Consists of an order ID and version."""
    order_id: str = Field(alias="orderId")
    def __init__(self, **data: Any) -> None: ...

class InboundPackages(BaseModel):
    """Represents the packages to inbound."""
    packages_to_inbound: list[DistributionPackageQuantity] = Field(alias="packagesToInbound")
    def __init__(self, **data: Any) -> None: ...

class InventoryQuantity(BaseModel):
    """Quantity of inventory with an associated measurement unit context."""
    quantity: float
    unit_of_measurement: InventoryUnitOfMeasurement = Field(alias="unitOfMeasurement")
    def __init__(self, **data: Any) -> None: ...

class SkuQuantity(BaseModel):
    """Quantity details for a SKU as part of a shipment"""
    expected_quantity: InventoryQuantity = Field(alias="expectedQuantity")
    received_quantity: InventoryQuantity | None = Field(default=None, alias="receivedQuantity")
    sku: str
    def __init__(self, **data: Any) -> None: ...

class InboundShipment(BaseModel):
    """Represents an AWD inbound shipment."""
    carrier_code: CarrierCode | None = Field(default=None, alias="carrierCode")
    created_at: datetime.datetime | None = Field(default=None, alias="createdAt")
    destination_address: Address = Field(alias="destinationAddress")
    external_reference_id: str | None = Field(default=None, alias="externalReferenceId")
    order_id: str = Field(alias="orderId")
    origin_address: Address = Field(alias="originAddress")
    received_quantity: list[InventoryQuantity] | None = Field(default=None, alias="receivedQuantity")
    ship_by: datetime.datetime | None = Field(default=None, alias="shipBy")
    shipment_container_quantities: list[DistributionPackageQuantity] = Field(alias="shipmentContainerQuantities")
    shipment_id: str = Field(alias="shipmentId")
    shipment_sku_quantities: list[SkuQuantity] | None = Field(default=None, alias="shipmentSkuQuantities")
    destination_region: str | None = Field(default=None, alias="destinationRegion")
    shipment_status: InboundShipmentStatus = Field(alias="shipmentStatus")
    tracking_id: str | None = Field(default=None, alias="trackingId")
    updated_at: datetime.datetime | None = Field(default=None, alias="updatedAt")
    warehouse_reference_id: str | None = Field(default=None, alias="warehouseReferenceId")
    def __init__(self, **data: Any) -> None: ...

class InboundShipmentSummary(BaseModel):
    """Summary for an AWD inbound shipment containing the shipment ID, which can be used to retrieve the actual shipment."""
    created_at: datetime.datetime | None = Field(default=None, alias="createdAt")
    external_reference_id: str | None = Field(default=None, alias="externalReferenceId")
    order_id: str = Field(alias="orderId")
    shipment_id: str = Field(alias="shipmentId")
    shipment_status: InboundShipmentStatus = Field(alias="shipmentStatus")
    updated_at: datetime.datetime | None = Field(default=None, alias="updatedAt")
    def __init__(self, **data: Any) -> None: ...

class ExpirationDetails(BaseModel):
    """The expiration details of the inventory. This object will only appear if the details parameter in the request is set to `SHOW`."""
    expiration: datetime.datetime | None = Field(default=None)
    onhand_quantity: int | None = Field(default=None, alias="onhandQuantity")
    def __init__(self, **data: Any) -> None: ...

class InventoryDetails(BaseModel):
    """Additional inventory details. This object is only displayed if the details parameter in the request is set to `SHOW`."""
    available_distributable_quantity: int | None = Field(default=None, alias="availableDistributableQuantity")
    replenishment_quantity: int | None = Field(default=None, alias="replenishmentQuantity")
    reserved_distributable_quantity: int | None = Field(default=None, alias="reservedDistributableQuantity")
    def __init__(self, **data: Any) -> None: ...

class InventorySummary(BaseModel):
    """Summary of inventory per SKU."""
    expiration_details: list[ExpirationDetails] | None = Field(default=None, alias="expirationDetails")
    inventory_details: InventoryDetails | None = Field(default=None, alias="inventoryDetails")
    sku: str
    total_inbound_quantity: int | None = Field(default=None, alias="totalInboundQuantity")
    total_onhand_quantity: int | None = Field(default=None, alias="totalOnhandQuantity")
    def __init__(self, **data: Any) -> None: ...

class InventoryListing(BaseModel):
    """AWD inventory payload."""
    inventory: list[InventorySummary]
    next_token: str | None = Field(default=None, alias="nextToken")
    def __init__(self, **data: Any) -> None: ...

class OrderAttribute(BaseModel):
    """Consists of the order preference and corresponding preference value."""
    order_preference: OrderPreference = Field(alias="orderPreference")
    order_preference_value: OrderPreferenceValue = Field(alias="orderPreferenceValue")
    def __init__(self, **data: Any) -> None: ...

class OutboundExecutionError(BaseModel):
    """Execution errors associated with the outbound order. This field will be populated if the order failed validation."""
    failure_code: str = Field(alias="failureCode")
    failure_reasons: list[str] = Field(alias="failureReasons")
    sku: str | None = Field(default=None)
    def __init__(self, **data: Any) -> None: ...

class OutboundShipment(BaseModel):
    """Represents an AWD outbound shipment."""
    created_at: datetime.datetime | None = Field(default=None, alias="createdAt")
    destination_address: Address = Field(alias="destinationAddress")
    order_id: str = Field(alias="orderId")
    origin_address: Address = Field(alias="originAddress")
    shipment_package_quantities: list[DistributionPackageQuantity] | None = Field(default=None, alias="shipmentPackageQuantities")
    shipment_id: str = Field(alias="shipmentId")
    shipment_product_quantities: list[ProductQuantity] | None = Field(default=None, alias="shipmentProductQuantities")
    shipment_status: OutboundShipmentStatus = Field(alias="shipmentStatus")
    updated_at: datetime.datetime | None = Field(default=None, alias="updatedAt")
    def __init__(self, **data: Any) -> None: ...

class OutboundOrder(BaseModel):
    """Represents an AWD outbound order."""
    confirmed_on: datetime.datetime | None = Field(default=None, alias="confirmedOn")
    created_at: datetime.datetime | None = Field(default=None, alias="createdAt")
    eligible_packages_to_outbound: list[DistributionPackageQuantity] | None = Field(default=None, alias="eligiblePackagesToOutbound")
    eligible_products_to_outbound: list[ProductQuantity] | None = Field(default=None, alias="eligibleProductsToOutbound")
    execution_errors: list[OutboundExecutionError] | None = Field(default=None, alias="executionErrors")
    order_id: str = Field(alias="orderId")
    order_preferences: list[OrderAttribute] | None = Field(default=None, alias="orderPreferences")
    order_status: OutboundStatus = Field(alias="orderStatus")
    outbound_shipments: list[OutboundShipment] = Field(alias="outboundShipments")
    packages_to_outbound: list[DistributionPackageQuantity] | None = Field(default=None, alias="packagesToOutbound")
    products_to_outbound: list[ProductQuantity] | None = Field(default=None, alias="productsToOutbound")
    shipped_outbound_packages: list[DistributionPackageQuantity] | None = Field(default=None, alias="shippedOutboundPackages")
    shipped_outbound_products: list[ProductQuantity] | None = Field(default=None, alias="shippedOutboundProducts")
    updated_at: datetime.datetime | None = Field(default=None, alias="updatedAt")
    def __init__(self, **data: Any) -> None: ...

class OutboundListing(BaseModel):
    """A list of paginated outbound orders filtered by the attributes passed in the request."""
    next_token: str | None = Field(default=None, alias="nextToken")
    outbound_orders: list[OutboundOrder] | None = Field(default=None, alias="outboundOrders")
    def __init__(self, **data: Any) -> None: ...

class OutboundOrderCreationData(BaseModel):
    """Payload for creating an outbound order."""
    order_preferences: list[OrderAttribute] | None = Field(default=None, alias="orderPreferences")
    packages_to_outbound: list[DistributionPackageQuantity] | None = Field(default=None, alias="packagesToOutbound")
    products_to_outbound: list[ProductQuantity] | None = Field(default=None, alias="productsToOutbound")
    def __init__(self, **data: Any) -> None: ...

class OutboundOrderReference(BaseModel):
    """A response that contains the reference identifier for the newly created or updated outbound order. This includes an order ID."""
    order_id: str = Field(alias="orderId")
    def __init__(self, **data: Any) -> None: ...

class OutboundShipmentSummary(BaseModel):
    """Summary of an AWD inbound shipment containing the shipment ID which can be used to"""
    created_at: datetime.datetime | None = Field(default=None, alias="createdAt")
    order_id: str = Field(alias="orderId")
    shipment_id: str = Field(alias="shipmentId")
    shipment_status: OutboundShipmentStatus = Field(alias="shipmentStatus")
    updated_at: datetime.datetime | None = Field(default=None, alias="updatedAt")
    def __init__(self, **data: Any) -> None: ...

class ReplenishmentOrder(BaseModel):
    """Represents an AWD replenishment order."""
    confirmed_on: datetime.datetime | None = Field(default=None, alias="confirmedOn")
    created_at: datetime.datetime | None = Field(default=None, alias="createdAt")
    distribution_ineligible_reasons: list[DistributionIneligibleReason] | None = Field(default=None, alias="distributionIneligibleReasons")
    eligible_products: list[DistributionProduct] | None = Field(default=None, alias="eligibleProducts")
    order_id: str = Field(alias="orderId")
    status: ReplenishmentOrderStatus
    outbound_shipments: list[OutboundShipmentSummary] = Field(alias="outboundShipments")
    products: list[DistributionProduct] | None = Field(default=None)
    shipped_products: list[DistributionProduct] | None = Field(default=None, alias="shippedProducts")
    updated_at: datetime.datetime | None = Field(default=None, alias="updatedAt")
    def __init__(self, **data: Any) -> None: ...

class ReplenishmentPreferences(BaseModel):
    """Preferences that can be passed in context of a replenishment order"""
    confirmation: ConfirmationMode | None = Field(default=None)
    def __init__(self, **data: Any) -> None: ...

class ReplenishmentOrderCreationData(BaseModel):
    """This structure represents the payload for creating an AFN Replenishment Order."""
    preferences: ReplenishmentPreferences | None = Field(default=None)
    products: list[DistributionProduct] | None = Field(default=None)
    def __init__(self, **data: Any) -> None: ...

class ReplenishmentOrderListing(BaseModel):
    """A list of paginated replenishment orders filtered by the attributes passed in the request."""
    next_token: str | None = Field(default=None, alias="nextToken")
    orders: list[ReplenishmentOrder] | None = Field(default=None)
    def __init__(self, **data: Any) -> None: ...

class ReplenishmentOrderReference(BaseModel):
    """Response containing the reference identifier for the newly created/updated replenishment order consisting of the order ID."""
    order_id: str = Field(alias="orderId")
    def __init__(self, **data: Any) -> None: ...

class ShipmentLabelPageTypes(BaseModel):
    """Shipment label page types."""
    label_status: LabelStatus = Field(alias="labelStatus")
    page_types: list[PageType] | None = Field(default=None, alias="pageTypes")
    def __init__(self, **data: Any) -> None: ...

class ShipmentLabels(BaseModel):
    """Shipment labels."""
    label_download_url: str | None = Field(default=None, alias="labelDownloadURL")
    label_status: LabelStatus = Field(alias="labelStatus")
    def __init__(self, **data: Any) -> None: ...

class ShipmentListing(BaseModel):
    """A list of inbound shipment summaries filtered by the attributes specified in the request."""
    next_token: str | None = Field(default=None, alias="nextToken")
    shipments: list[InboundShipmentSummary] | None = Field(default=None)
    def __init__(self, **data: Any) -> None: ...

class TrackingDetails(BaseModel):
    """Tracking details for the shipment. If using SPD transportation, this can be for each case. If not using SPD transportation, this is a single tracking entry for the entire shipment."""
    carrier_code: CarrierCode | None = Field(default=None, alias="carrierCode")
    booking_id: str = Field(alias="bookingId")
    def __init__(self, **data: Any) -> None: ...

class TransportationDetails(BaseModel):
    """Transportation details for the shipment."""
    tracking_details: list[TrackingDetails] = Field(alias="trackingDetails")
    def __init__(self, **data: Any) -> None: ...

# raw-mode shapes (``raw=True``)

class AddressDict(TypedDict, total=False):
    addressLine1: str
    addressLine2: str
    addressLine3: str
    city: str
    countryCode: str
    county: str
    district: str
    name: str
    phoneNumber: str
    postalCode: str
    stateOrRegion: str

class CarrierCodeDict(TypedDict, total=False):
    carrierCodeType: CarrierCodeType
    carrierCodeValue: str

class DestinationDetailsDict(TypedDict, total=False):
    destinationAddress: AddressDict
    destinationRegion: str
    shipmentId: str

class DistributionIneligibleReasonDict(TypedDict, total=False):
    failureCode: str
    failureReasons: list[str]
    sku: str

class DistributionPackageQuantityDict(TypedDict, total=False):
    count: int
    distributionPackage: DistributionPackageDict

class ProductAttributeDict(TypedDict, total=False):
    name: str
    value: str

class PrepInstructionDict(TypedDict, total=False):
    prepOwner: PrepOwner
    prepType: str

class PrepDetailsDict(TypedDict, total=False):
    labelOwner: LabelOwner
    prepCategory: PrepCategory
    prepInstructions: list[PrepInstructionDict]
    prepOwner: PrepOwner

class ProductQuantityDict(TypedDict, total=False):
    attributes: list[ProductAttributeDict]
    quantity: int
    sku: str
    expiration: datetime.datetime
    prepDetails: PrepDetailsDict

class DistributionPackageContentsDict(TypedDict, total=False):
    packages: list[DistributionPackageQuantityDict]
    products: list[ProductQuantityDict]

class PackageDimensionsDict(TypedDict, total=False):
    height: float
    length: float
    unitOfMeasurement: DimensionUnitOfMeasurement
    width: float

class PackageVolumeDict(TypedDict, total=False):
    unitOfMeasurement: VolumeUnitOfMeasurement
    volume: float

class PackageWeightDict(TypedDict, total=False):
    unitOfMeasurement: WeightUnitOfMeasurement
    weight: float

class MeasurementDataDict(TypedDict, total=False):
    dimensions: PackageDimensionsDict
    volume: PackageVolumeDict
    weight: PackageWeightDict

class DistributionPackageDict(TypedDict, total=False):
    contents: DistributionPackageContentsDict
    measurements: MeasurementDataDict
    type: DistributionPackageType

class DistributionProductDict(TypedDict, total=False):
    attributes: list[ProductAttributeDict]
    quantity: int
    sku: str

class ErrorDict(TypedDict, total=False):
    code: str
    details: str
    message: str

class ErrorListDict(TypedDict, total=False):
    errors: list[ErrorDict]

class OrderIneligibilityReasonDict(TypedDict, total=False):
    code: str
    description: str

class SkuIneligibilityReasonDict(TypedDict, total=False):
    code: str
    description: str

class SkuEligibilityDict(TypedDict, total=False):
    ineligibilityReasons: list[SkuIneligibilityReasonDict]
    packageQuantity: DistributionPackageQuantityDict
    status: InboundEligibilityStatus

class InboundEligibilityDict(TypedDict, total=False):
    ineligibilityReasons: list[OrderIneligibilityReasonDict]
    packagesToInbound: list[SkuEligibilityDict]
    previewedAt: datetime.datetime
    status: InboundEligibilityStatus

class InboundPreferencesDict(TypedDict, total=False):
    destinationRegion: str

class InboundOrderDict(TypedDict, total=False):
    createdAt: datetime.datetime
    destinationDetails: DestinationDetailsDict
    externalReferenceId: str
    orderId: str
    orderStatus: InboundStatus
    originAddress: AddressDict
    packagesToInbound: list[DistributionPackageQuantityDict]
    preferences: InboundPreferencesDict
    updatedAt: datetime.datetime

class InboundOrderCreationDataDict(TypedDict, total=False):
    externalReferenceId: str
    originAddress: AddressDict
    packagesToInbound: list[DistributionPackageQuantityDict]
    preferences: InboundPreferencesDict

class InboundOrderReferenceDict(TypedDict, total=False):
    orderId: str

class InboundPackagesDict(TypedDict, total=False):
    packagesToInbound: list[DistributionPackageQuantityDict]

class InventoryQuantityDict(TypedDict, total=False):
    quantity: float
    unitOfMeasurement: InventoryUnitOfMeasurement

class SkuQuantityDict(TypedDict, total=False):
    expectedQuantity: InventoryQuantityDict
    receivedQuantity: InventoryQuantityDict
    sku: str

class InboundShipmentDict(TypedDict, total=False):
    carrierCode: CarrierCodeDict
    createdAt: datetime.datetime
    destinationAddress: AddressDict
    externalReferenceId: str
    orderId: str
    originAddress: AddressDict
    receivedQuantity: list[InventoryQuantityDict]
    shipBy: datetime.datetime
    shipmentContainerQuantities: list[DistributionPackageQuantityDict]
    shipmentId: str
    shipmentSkuQuantities: list[SkuQuantityDict]
    destinationRegion: str
    shipmentStatus: InboundShipmentStatus
    trackingId: str
    updatedAt: datetime.datetime
    warehouseReferenceId: str

class InboundShipmentSummaryDict(TypedDict, total=False):
    createdAt: datetime.datetime
    externalReferenceId: str
    orderId: str
    shipmentId: str
    shipmentStatus: InboundShipmentStatus
    updatedAt: datetime.datetime

class ExpirationDetailsDict(TypedDict, total=False):
    expiration: datetime.datetime
    onhandQuantity: int

class InventoryDetailsDict(TypedDict, total=False):
    availableDistributableQuantity: int
    replenishmentQuantity: int
    reservedDistributableQuantity: int

class InventorySummaryDict(TypedDict, total=False):
    expirationDetails: list[ExpirationDetailsDict]
    inventoryDetails: InventoryDetailsDict
    sku: str
    totalInboundQuantity: int
    totalOnhandQuantity: int

class InventoryListingDict(TypedDict, total=False):
    inventory: list[InventorySummaryDict]
    nextToken: str

class OrderAttributeDict(TypedDict, total=False):
    orderPreference: OrderPreference
    orderPreferenceValue: OrderPreferenceValue

class OutboundExecutionErrorDict(TypedDict, total=False):
    failureCode: str
    failureReasons: list[str]
    sku: str

class OutboundShipmentDict(TypedDict, total=False):
    createdAt: datetime.datetime
    destinationAddress: AddressDict
    orderId: str
    originAddress: AddressDict
    shipmentPackageQuantities: list[DistributionPackageQuantityDict]
    shipmentId: str
    shipmentProductQuantities: list[ProductQuantityDict]
    shipmentStatus: OutboundShipmentStatus
    updatedAt: datetime.datetime

class OutboundOrderDict(TypedDict, total=False):
    confirmedOn: datetime.datetime
    createdAt: datetime.datetime
    eligiblePackagesToOutbound: list[DistributionPackageQuantityDict]
    eligibleProductsToOutbound: list[ProductQuantityDict]
    executionErrors: list[OutboundExecutionErrorDict]
    orderId: str
    orderPreferences: list[OrderAttributeDict]
    orderStatus: OutboundStatus
    outboundShipments: list[OutboundShipmentDict]
    packagesToOutbound: list[DistributionPackageQuantityDict]
    productsToOutbound: list[ProductQuantityDict]
    shippedOutboundPackages: list[DistributionPackageQuantityDict]
    shippedOutboundProducts: list[ProductQuantityDict]
    updatedAt: datetime.datetime

class OutboundListingDict(TypedDict, total=False):
    nextToken: str
    outboundOrders: list[OutboundOrderDict]

class OutboundOrderCreationDataDict(TypedDict, total=False):
    orderPreferences: list[OrderAttributeDict]
    packagesToOutbound: list[DistributionPackageQuantityDict]
    productsToOutbound: list[ProductQuantityDict]

class OutboundOrderReferenceDict(TypedDict, total=False):
    orderId: str

class OutboundShipmentSummaryDict(TypedDict, total=False):
    createdAt: datetime.datetime
    orderId: str
    shipmentId: str
    shipmentStatus: OutboundShipmentStatus
    updatedAt: datetime.datetime

class ReplenishmentOrderDict(TypedDict, total=False):
    confirmedOn: datetime.datetime
    createdAt: datetime.datetime
    distributionIneligibleReasons: list[DistributionIneligibleReasonDict]
    eligibleProducts: list[DistributionProductDict]
    orderId: str
    status: ReplenishmentOrderStatus
    outboundShipments: list[OutboundShipmentSummaryDict]
    products: list[DistributionProductDict]
    shippedProducts: list[DistributionProductDict]
    updatedAt: datetime.datetime

class ReplenishmentPreferencesDict(TypedDict, total=False):
    confirmation: ConfirmationMode

class ReplenishmentOrderCreationDataDict(TypedDict, total=False):
    preferences: ReplenishmentPreferencesDict
    products: list[DistributionProductDict]

class ReplenishmentOrderListingDict(TypedDict, total=False):
    nextToken: str
    orders: list[ReplenishmentOrderDict]

class ReplenishmentOrderReferenceDict(TypedDict, total=False):
    orderId: str

class ShipmentLabelPageTypesDict(TypedDict, total=False):
    labelStatus: LabelStatus
    pageTypes: list[PageType]

class ShipmentLabelsDict(TypedDict, total=False):
    labelDownloadURL: str
    labelStatus: LabelStatus

class ShipmentListingDict(TypedDict, total=False):
    nextToken: str
    shipments: list[InboundShipmentSummaryDict]

class TrackingDetailsDict(TypedDict, total=False):
    carrierCode: CarrierCodeDict
    bookingId: str

class TransportationDetailsDict(TypedDict, total=False):
    trackingDetails: list[TrackingDetailsDict]

# type aliases
CarrierCodeType = Literal['SCAC']
ConfirmationMode = Literal['AUTO', 'MANUAL']
DimensionUnitOfMeasurement = Literal['INCHES', 'CENTIMETERS']
LabelOwner = Literal['AMAZON', 'SELF']
PrepCategory = Literal['ADULT', 'BABY', 'FC_PROVIDED', 'FRAGILE', 'GRANULAR', 'HANGER', 'LIQUID', 'PERFORATED', 'SET', 'SHARP', 'SMALL', 'TEXTILE', 'NO_PREP', 'UNKNOWN']
PrepOwner = Literal['AMAZON', 'SELF']
VolumeUnitOfMeasurement = Literal['CU_IN', 'CBM', 'CC']
WeightUnitOfMeasurement = Literal['POUNDS', 'KILOGRAMS']
DistributionPackageType = Literal['CASE', 'PALLET']
FormatType = Literal['PDF']
InboundEligibilityStatus = Literal['ELIGIBLE', 'INELIGIBLE']
InboundStatus = Literal['DRAFT', 'VALIDATING', 'CONFIRMED', 'CLOSED', 'EXPIRED', 'CANCELLED']
InventoryUnitOfMeasurement = Literal['PRODUCT_UNITS', 'CASES', 'PALLETS']
InboundShipmentStatus = Literal['CREATED', 'SHIPPED', 'IN_TRANSIT', 'RECEIVING', 'DELIVERED', 'CLOSED', 'CANCELLED']
InventoryDetailsVisibility = Literal['SHOW', 'HIDE']
LabelStatus = Literal['GENERATING', 'GENERATED', 'GENERATION_FAILED', 'NOT_READY']
OrderPreference = Literal['PARTIAL_ORDER']
OrderPreferenceValue = Literal['SET', 'UNSET']
OutboundStatus = Literal['CONFIRMED', 'DRAFT', 'ELIGIBLE', 'EXECUTING', 'FAILURE', 'INELIGIBLE', 'INVENTORY_OUTBOUND', 'SUCCESS', 'VALIDATING']
OutboundShipmentStatus = Literal['CREATED', 'IN_TRANSIT', 'DELIVERED', 'RECEIVING', 'RECEIVED', 'CLOSED', 'CANCELLED', 'FAILED']
PageType = Literal['PLAIN_PAPER', 'LETTER_PCP_FULFILLMENTLABEL', 'LETTER_2_HORIZONTAL', 'LETTER_2', 'THERMAL_NO_CARRIER_ROTATION', 'THERMAL', 'A4_PAPER', 'A4_2_HORIZONTAL', 'THERMAL_SQUARE_10CM']
ReplenishmentOrderStatus = Literal['CONFIRMED', 'CREATED', 'ELIGIBLE', 'EXECUTING', 'FAILURE', 'INELIGIBLE', 'INVENTORY_OUTBOUND', 'SUCCESS', 'VALIDATING']
ShipmentSortableField = Literal['UPDATED_AT', 'CREATED_AT']
SkuQuantitiesVisibility = Literal['SHOW', 'HIDE']
SortOrder = Literal['ASCENDING', 'DESCENDING']
