# Auto-generated by oagen. Do not edit.

"""``FulfillmentInboundV0`` resource of Selling Partner API.

Auto-generated by oagen from the OpenAPI spec; do not edit by hand.
"""

from __future__ import annotations

import datetime
from collections.abc import AsyncIterator, Iterator
from typing import Any

from .._http import AsyncHttpClient, HttpClient, RateLimit, RequestOptions, apaginate, joined, paginate, path_segment
from ..models import fulfillment_inbound_v0

SERVICE = "fulfillment_inbound_v0"


class FulfillmentInboundV0Resource:
    """Synchronous ``FulfillmentInboundV0`` resource."""

    __slots__ = ("_http",)

    def __init__(self, http: HttpClient) -> None:
        self._http = http

    def list_prep_instructions(
        self,
        ship_to_country_code: str,
        *,
        seller_sku_list: list[str] | None = None,
        asin_list: list[str] | None = None,
        request_options: RequestOptions | None = None,
    ) -> fulfillment_inbound_v0.GetPrepInstructionsResponse:
        """Returns labeling requirements and item preparation instructions to help prepare items for shipment to Amazon's fulfillment network.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 2 | 30 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        GET /fba/inbound/v0/prepInstructions
        """
        params: dict[str, Any] = {
            "ShipToCountryCode": ship_to_country_code,
            "SellerSKUList": joined(seller_sku_list, ","),
            "ASINList": joined(asin_list, ","),
        }
        return self._http.request(
            "GET",
            "/fba/inbound/v0/prepInstructions",
            operation="getPrepInstructions",
            service=SERVICE,
            params=params,
            response=fulfillment_inbound_v0.GetPrepInstructionsResponse,
            error=fulfillment_inbound_v0.GetPrepInstructionsResponse,
            rate_limit=RateLimit(2, 30),
            options=request_options,
        )

    def list_shipment_labels(
        self,
        shipment_id: str,
        page_type: fulfillment_inbound_v0.FulfillmentInboundV0PageType | str,
        label_type: fulfillment_inbound_v0.FulfillmentInboundV0LabelType | str,
        *,
        number_of_packages: int | None = None,
        package_labels_to_print: list[str] | None = None,
        number_of_pallets: int | None = None,
        page_size: int | None = None,
        page_start_index: int | None = None,
        request_options: RequestOptions | None = None,
    ) -> fulfillment_inbound_v0.GetLabelsResponse:
        """Returns package/pallet labels for faster and more accurate shipment processing at the Amazon fulfillment center.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 2 | 30 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        GET /fba/inbound/v0/shipments/{shipmentId}/labels
        """
        params: dict[str, Any] = {
            "PageType": page_type,
            "LabelType": label_type,
            "NumberOfPackages": number_of_packages,
            "PackageLabelsToPrint": joined(package_labels_to_print, ","),
            "NumberOfPallets": number_of_pallets,
            "PageSize": page_size,
            "PageStartIndex": page_start_index,
        }
        return self._http.request(
            "GET",
            f"/fba/inbound/v0/shipments/{path_segment(shipment_id)}/labels",
            operation="getLabels",
            service=SERVICE,
            params=params,
            response=fulfillment_inbound_v0.GetLabelsResponse,
            error=fulfillment_inbound_v0.GetLabelsResponse,
            rate_limit=RateLimit(2, 30),
            options=request_options,
        )

    def list_shipment_bill_of_lading(
        self,
        shipment_id: str,
        *,
        request_options: RequestOptions | None = None,
    ) -> fulfillment_inbound_v0.GetBillOfLadingResponse:
        """Returns a bill of lading for a Less Than Truckload/Full Truckload (LTL/FTL) shipment. The getBillOfLading operation returns PDF document data for printing a bill of lading for an Amazon-partnered Less Than Truckload/Full Truckload (LTL/FTL) inbound shipment.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 2 | 30 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        GET /fba/inbound/v0/shipments/{shipmentId}/billOfLading
        """
        return self._http.request(
            "GET",
            f"/fba/inbound/v0/shipments/{path_segment(shipment_id)}/billOfLading",
            operation="getBillOfLading",
            service=SERVICE,
            response=fulfillment_inbound_v0.GetBillOfLadingResponse,
            error=fulfillment_inbound_v0.GetBillOfLadingResponse,
            rate_limit=RateLimit(2, 30),
            options=request_options,
        )

    def list_shipments(
        self,
        query_type: fulfillment_inbound_v0.FulfillmentInboundV0QueryType | str,
        marketplace_id: str,
        *,
        shipment_status_list: list[fulfillment_inbound_v0.FulfillmentInboundV0ShipmentStatusList] | None = None,
        shipment_id_list: list[str] | None = None,
        last_updated_after: datetime.datetime | None = None,
        last_updated_before: datetime.datetime | None = None,
        next_token: str | None = None,
        request_options: RequestOptions | None = None,
    ) -> fulfillment_inbound_v0.GetShipmentsResponse:
        """Returns a list of inbound shipments based on criteria that you specify.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 2 | 30 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        GET /fba/inbound/v0/shipments
        """
        params: dict[str, Any] = {
            "ShipmentStatusList": joined(shipment_status_list, ","),
            "ShipmentIdList": joined(shipment_id_list, ","),
            "LastUpdatedAfter": last_updated_after,
            "LastUpdatedBefore": last_updated_before,
            "QueryType": query_type,
            "NextToken": next_token,
            "MarketplaceId": marketplace_id,
        }
        return self._http.request(
            "GET",
            "/fba/inbound/v0/shipments",
            operation="getShipments",
            service=SERVICE,
            params=params,
            response=fulfillment_inbound_v0.GetShipmentsResponse,
            error=fulfillment_inbound_v0.GetShipmentsResponse,
            rate_limit=RateLimit(2, 30),
            options=request_options,
        )

    def iter_list_shipments(
        self,
        query_type: fulfillment_inbound_v0.FulfillmentInboundV0QueryType | str,
        marketplace_id: str,
        *,
        shipment_status_list: list[fulfillment_inbound_v0.FulfillmentInboundV0ShipmentStatusList] | None = None,
        shipment_id_list: list[str] | None = None,
        last_updated_after: datetime.datetime | None = None,
        last_updated_before: datetime.datetime | None = None,
        next_token: str | None = None,
        request_options: RequestOptions | None = None,
    ) -> Iterator[fulfillment_inbound_v0.InboundShipmentInfo]:
        """every item of ``payload.ShipmentData`` across pages of ``list_shipments``, following ``payload.NextToken`` -> ``next_token``."""
        return paginate(
            self.list_shipments,
            {
                "shipment_status_list": shipment_status_list,
                "shipment_id_list": shipment_id_list,
                "last_updated_after": last_updated_after,
                "last_updated_before": last_updated_before,
                "query_type": query_type,
                "next_token": next_token,
                "marketplace_id": marketplace_id,
                "request_options": request_options,
            },
            items=("payload", "shipment_data"),
            token=("payload", "next_token"),
            token_param="next_token",
            wire_items=("payload", "ShipmentData"),
            wire_token=("payload", "NextToken"),
        )

    def get_shipment_items_by_shipment_id(
        self,
        shipment_id: str,
        *,
        marketplace_id: str | None = None,
        request_options: RequestOptions | None = None,
    ) -> fulfillment_inbound_v0.GetShipmentItemsResponse:
        """Returns a list of items in a specified inbound shipment.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 2 | 30 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        GET /fba/inbound/v0/shipments/{shipmentId}/items
        """
        params: dict[str, Any] = {"MarketplaceId": marketplace_id}
        return self._http.request(
            "GET",
            f"/fba/inbound/v0/shipments/{path_segment(shipment_id)}/items",
            operation="getShipmentItemsByShipmentId",
            service=SERVICE,
            params=params,
            response=fulfillment_inbound_v0.GetShipmentItemsResponse,
            error=fulfillment_inbound_v0.GetShipmentItemsResponse,
            rate_limit=RateLimit(2, 30),
            options=request_options,
        )

    def get_shipment_items(
        self,
        query_type: fulfillment_inbound_v0.FulfillmentInboundV0QueryType | str,
        marketplace_id: str,
        *,
        last_updated_after: datetime.datetime | None = None,
        last_updated_before: datetime.datetime | None = None,
        next_token: str | None = None,
        request_options: RequestOptions | None = None,
    ) -> fulfillment_inbound_v0.GetShipmentItemsResponse:
        """Returns a list of items in a specified inbound shipment, or a list of items that were updated within a specified time frame.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 2 | 30 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        GET /fba/inbound/v0/shipmentItems
        """
        params: dict[str, Any] = {
            "LastUpdatedAfter": last_updated_after,
            "LastUpdatedBefore": last_updated_before,
            "QueryType": query_type,
            "NextToken": next_token,
            "MarketplaceId": marketplace_id,
        }
        return self._http.request(
            "GET",
            "/fba/inbound/v0/shipmentItems",
            operation="getShipmentItems",
            service=SERVICE,
            params=params,
            response=fulfillment_inbound_v0.GetShipmentItemsResponse,
            error=fulfillment_inbound_v0.GetShipmentItemsResponse,
            rate_limit=RateLimit(2, 30),
            options=request_options,
        )

    def iter_get_shipment_items(
        self,
        query_type: fulfillment_inbound_v0.FulfillmentInboundV0QueryType | str,
        marketplace_id: str,
        *,
        last_updated_after: datetime.datetime | None = None,
        last_updated_before: datetime.datetime | None = None,
        next_token: str | None = None,
        request_options: RequestOptions | None = None,
    ) -> Iterator[fulfillment_inbound_v0.InboundShipmentItem]:
        """every item of ``payload.ItemData`` across pages of ``get_shipment_items``, following ``payload.NextToken`` -> ``next_token``."""
        return paginate(
            self.get_shipment_items,
            {
                "last_updated_after": last_updated_after,
                "last_updated_before": last_updated_before,
                "query_type": query_type,
                "next_token": next_token,
                "marketplace_id": marketplace_id,
                "request_options": request_options,
            },
            items=("payload", "item_data"),
            token=("payload", "next_token"),
            token_param="next_token",
            wire_items=("payload", "ItemData"),
            wire_token=("payload", "NextToken"),
        )


class AsyncFulfillmentInboundV0Resource:
    """Asynchronous ``FulfillmentInboundV0`` resource."""

    __slots__ = ("_http",)

    def __init__(self, http: AsyncHttpClient) -> None:
        self._http = http

    async def list_prep_instructions(
        self,
        ship_to_country_code: str,
        *,
        seller_sku_list: list[str] | None = None,
        asin_list: list[str] | None = None,
        request_options: RequestOptions | None = None,
    ) -> fulfillment_inbound_v0.GetPrepInstructionsResponse:
        """Returns labeling requirements and item preparation instructions to help prepare items for shipment to Amazon's fulfillment network.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 2 | 30 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        GET /fba/inbound/v0/prepInstructions
        """
        params: dict[str, Any] = {
            "ShipToCountryCode": ship_to_country_code,
            "SellerSKUList": joined(seller_sku_list, ","),
            "ASINList": joined(asin_list, ","),
        }
        return await self._http.request(
            "GET",
            "/fba/inbound/v0/prepInstructions",
            operation="getPrepInstructions",
            service=SERVICE,
            params=params,
            response=fulfillment_inbound_v0.GetPrepInstructionsResponse,
            error=fulfillment_inbound_v0.GetPrepInstructionsResponse,
            rate_limit=RateLimit(2, 30),
            options=request_options,
        )

    async def list_shipment_labels(
        self,
        shipment_id: str,
        page_type: fulfillment_inbound_v0.FulfillmentInboundV0PageType | str,
        label_type: fulfillment_inbound_v0.FulfillmentInboundV0LabelType | str,
        *,
        number_of_packages: int | None = None,
        package_labels_to_print: list[str] | None = None,
        number_of_pallets: int | None = None,
        page_size: int | None = None,
        page_start_index: int | None = None,
        request_options: RequestOptions | None = None,
    ) -> fulfillment_inbound_v0.GetLabelsResponse:
        """Returns package/pallet labels for faster and more accurate shipment processing at the Amazon fulfillment center.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 2 | 30 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        GET /fba/inbound/v0/shipments/{shipmentId}/labels
        """
        params: dict[str, Any] = {
            "PageType": page_type,
            "LabelType": label_type,
            "NumberOfPackages": number_of_packages,
            "PackageLabelsToPrint": joined(package_labels_to_print, ","),
            "NumberOfPallets": number_of_pallets,
            "PageSize": page_size,
            "PageStartIndex": page_start_index,
        }
        return await self._http.request(
            "GET",
            f"/fba/inbound/v0/shipments/{path_segment(shipment_id)}/labels",
            operation="getLabels",
            service=SERVICE,
            params=params,
            response=fulfillment_inbound_v0.GetLabelsResponse,
            error=fulfillment_inbound_v0.GetLabelsResponse,
            rate_limit=RateLimit(2, 30),
            options=request_options,
        )

    async def list_shipment_bill_of_lading(
        self,
        shipment_id: str,
        *,
        request_options: RequestOptions | None = None,
    ) -> fulfillment_inbound_v0.GetBillOfLadingResponse:
        """Returns a bill of lading for a Less Than Truckload/Full Truckload (LTL/FTL) shipment. The getBillOfLading operation returns PDF document data for printing a bill of lading for an Amazon-partnered Less Than Truckload/Full Truckload (LTL/FTL) inbound shipment.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 2 | 30 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        GET /fba/inbound/v0/shipments/{shipmentId}/billOfLading
        """
        return await self._http.request(
            "GET",
            f"/fba/inbound/v0/shipments/{path_segment(shipment_id)}/billOfLading",
            operation="getBillOfLading",
            service=SERVICE,
            response=fulfillment_inbound_v0.GetBillOfLadingResponse,
            error=fulfillment_inbound_v0.GetBillOfLadingResponse,
            rate_limit=RateLimit(2, 30),
            options=request_options,
        )

    async def list_shipments(
        self,
        query_type: fulfillment_inbound_v0.FulfillmentInboundV0QueryType | str,
        marketplace_id: str,
        *,
        shipment_status_list: list[fulfillment_inbound_v0.FulfillmentInboundV0ShipmentStatusList] | None = None,
        shipment_id_list: list[str] | None = None,
        last_updated_after: datetime.datetime | None = None,
        last_updated_before: datetime.datetime | None = None,
        next_token: str | None = None,
        request_options: RequestOptions | None = None,
    ) -> fulfillment_inbound_v0.GetShipmentsResponse:
        """Returns a list of inbound shipments based on criteria that you specify.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 2 | 30 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        GET /fba/inbound/v0/shipments
        """
        params: dict[str, Any] = {
            "ShipmentStatusList": joined(shipment_status_list, ","),
            "ShipmentIdList": joined(shipment_id_list, ","),
            "LastUpdatedAfter": last_updated_after,
            "LastUpdatedBefore": last_updated_before,
            "QueryType": query_type,
            "NextToken": next_token,
            "MarketplaceId": marketplace_id,
        }
        return await self._http.request(
            "GET",
            "/fba/inbound/v0/shipments",
            operation="getShipments",
            service=SERVICE,
            params=params,
            response=fulfillment_inbound_v0.GetShipmentsResponse,
            error=fulfillment_inbound_v0.GetShipmentsResponse,
            rate_limit=RateLimit(2, 30),
            options=request_options,
        )

    def iter_list_shipments(
        self,
        query_type: fulfillment_inbound_v0.FulfillmentInboundV0QueryType | str,
        marketplace_id: str,
        *,
        shipment_status_list: list[fulfillment_inbound_v0.FulfillmentInboundV0ShipmentStatusList] | None = None,
        shipment_id_list: list[str] | None = None,
        last_updated_after: datetime.datetime | None = None,
        last_updated_before: datetime.datetime | None = None,
        next_token: str | None = None,
        request_options: RequestOptions | None = None,
    ) -> AsyncIterator[fulfillment_inbound_v0.InboundShipmentInfo]:
        """every item of ``payload.ShipmentData`` across pages of ``list_shipments``, following ``payload.NextToken`` -> ``next_token``."""
        return apaginate(
            self.list_shipments,
            {
                "shipment_status_list": shipment_status_list,
                "shipment_id_list": shipment_id_list,
                "last_updated_after": last_updated_after,
                "last_updated_before": last_updated_before,
                "query_type": query_type,
                "next_token": next_token,
                "marketplace_id": marketplace_id,
                "request_options": request_options,
            },
            items=("payload", "shipment_data"),
            token=("payload", "next_token"),
            token_param="next_token",
            wire_items=("payload", "ShipmentData"),
            wire_token=("payload", "NextToken"),
        )

    async def get_shipment_items_by_shipment_id(
        self,
        shipment_id: str,
        *,
        marketplace_id: str | None = None,
        request_options: RequestOptions | None = None,
    ) -> fulfillment_inbound_v0.GetShipmentItemsResponse:
        """Returns a list of items in a specified inbound shipment.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 2 | 30 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        GET /fba/inbound/v0/shipments/{shipmentId}/items
        """
        params: dict[str, Any] = {"MarketplaceId": marketplace_id}
        return await self._http.request(
            "GET",
            f"/fba/inbound/v0/shipments/{path_segment(shipment_id)}/items",
            operation="getShipmentItemsByShipmentId",
            service=SERVICE,
            params=params,
            response=fulfillment_inbound_v0.GetShipmentItemsResponse,
            error=fulfillment_inbound_v0.GetShipmentItemsResponse,
            rate_limit=RateLimit(2, 30),
            options=request_options,
        )

    async def get_shipment_items(
        self,
        query_type: fulfillment_inbound_v0.FulfillmentInboundV0QueryType | str,
        marketplace_id: str,
        *,
        last_updated_after: datetime.datetime | None = None,
        last_updated_before: datetime.datetime | None = None,
        next_token: str | None = None,
        request_options: RequestOptions | None = None,
    ) -> fulfillment_inbound_v0.GetShipmentItemsResponse:
        """Returns a list of items in a specified inbound shipment, or a list of items that were updated within a specified time frame.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 2 | 30 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        GET /fba/inbound/v0/shipmentItems
        """
        params: dict[str, Any] = {
            "LastUpdatedAfter": last_updated_after,
            "LastUpdatedBefore": last_updated_before,
            "QueryType": query_type,
            "NextToken": next_token,
            "MarketplaceId": marketplace_id,
        }
        return await self._http.request(
            "GET",
            "/fba/inbound/v0/shipmentItems",
            operation="getShipmentItems",
            service=SERVICE,
            params=params,
            response=fulfillment_inbound_v0.GetShipmentItemsResponse,
            error=fulfillment_inbound_v0.GetShipmentItemsResponse,
            rate_limit=RateLimit(2, 30),
            options=request_options,
        )

    def iter_get_shipment_items(
        self,
        query_type: fulfillment_inbound_v0.FulfillmentInboundV0QueryType | str,
        marketplace_id: str,
        *,
        last_updated_after: datetime.datetime | None = None,
        last_updated_before: datetime.datetime | None = None,
        next_token: str | None = None,
        request_options: RequestOptions | None = None,
    ) -> AsyncIterator[fulfillment_inbound_v0.InboundShipmentItem]:
        """every item of ``payload.ItemData`` across pages of ``get_shipment_items``, following ``payload.NextToken`` -> ``next_token``."""
        return apaginate(
            self.get_shipment_items,
            {
                "last_updated_after": last_updated_after,
                "last_updated_before": last_updated_before,
                "query_type": query_type,
                "next_token": next_token,
                "marketplace_id": marketplace_id,
                "request_options": request_options,
            },
            items=("payload", "item_data"),
            token=("payload", "next_token"),
            token_param="next_token",
            wire_items=("payload", "ItemData"),
            wire_token=("payload", "NextToken"),
        )


__all__ = ["AsyncFulfillmentInboundV0Resource", "FulfillmentInboundV0Resource"]
