# Auto-generated by oagen. Do not edit.

"""``ListingsItemsV20200901`` resource of Selling Partner API.

Auto-generated by oagen from the OpenAPI spec; do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from ..http_client import AsyncHttpClient, HttpClient, RateLimit, RequestOptions, joined, path_segment
from ..models import listings_items_v2020_09_01

SERVICE = "listings_items_v2020_09_01"


class ListingsItemsV20200901Client:
    """Synchronous ``ListingsItemsV20200901`` resource."""

    __slots__ = ("_client",)

    def __init__(self, client: HttpClient) -> None:
        self._client = client

    def put_listings_item(
        self,
        *,
        seller_id: str,
        sku: str,
        marketplace_ids: list[str],
        body: listings_items_v2020_09_01.ListingsItemPutRequest | Mapping[str, Any],
        issue_locale: str | None = None,
        request_options: RequestOptions | None = None,
    ) -> listings_items_v2020_09_01.ListingsItemSubmissionResponse:
        """Creates a new or fully-updates an existing listings item for a selling partner.

        **Note:** The parameters associated with this operation may contain special characters that must be encoded to successfully call the API. To avoid errors with SKUs when encoding URLs, refer to [URL Encoding](https://developer-docs.amazon.com/sp-api/docs/url-encoding).

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 5 | 10 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        PUT /listings/2020-09-01/items/{sellerId}/{sku}
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ","), "issueLocale": issue_locale}
        return self._client.request(
            "PUT",
            f"/listings/2020-09-01/items/{path_segment(seller_id)}/{path_segment(sku)}",
            operation="putListingsItem",
            service=SERVICE,
            params=params,
            json=body,
            response=listings_items_v2020_09_01.ListingsItemSubmissionResponse,
            error=listings_items_v2020_09_01.ErrorList,
            rate_limit=RateLimit(5, 10),
            options=request_options,
        )

    def patch_listings_item(
        self,
        *,
        seller_id: str,
        sku: str,
        marketplace_ids: list[str],
        body: listings_items_v2020_09_01.ListingsItemPatchRequest | Mapping[str, Any],
        issue_locale: str | None = None,
        request_options: RequestOptions | None = None,
    ) -> listings_items_v2020_09_01.ListingsItemSubmissionResponse:
        """Partially update (patch) a listings item for a selling partner. Only top-level listings item attributes can be patched. Patching nested attributes is not supported.

        **Note:** The parameters associated with this operation may contain special characters that must be encoded to successfully call the API. To avoid errors with SKUs when encoding URLs, refer to [URL Encoding](https://developer-docs.amazon.com/sp-api/docs/url-encoding).

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 5 | 10 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        PATCH /listings/2020-09-01/items/{sellerId}/{sku}
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ","), "issueLocale": issue_locale}
        return self._client.request(
            "PATCH",
            f"/listings/2020-09-01/items/{path_segment(seller_id)}/{path_segment(sku)}",
            operation="patchListingsItem",
            service=SERVICE,
            params=params,
            json=body,
            response=listings_items_v2020_09_01.ListingsItemSubmissionResponse,
            error=listings_items_v2020_09_01.ErrorList,
            rate_limit=RateLimit(5, 10),
            options=request_options,
        )

    def delete_item(
        self,
        *,
        seller_id: str,
        sku: str,
        marketplace_ids: list[str],
        issue_locale: str | None = None,
        request_options: RequestOptions | None = None,
    ) -> listings_items_v2020_09_01.ListingsItemSubmissionResponse:
        """Delete a listings item for a selling partner.

        **Note:** The parameters associated with this operation may contain special characters that must be encoded to successfully call the API. To avoid errors with SKUs when encoding URLs, refer to [URL Encoding](https://developer-docs.amazon.com/sp-api/docs/url-encoding).

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 5 | 10 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        DELETE /listings/2020-09-01/items/{sellerId}/{sku}
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ","), "issueLocale": issue_locale}
        return self._client.request(
            "DELETE",
            f"/listings/2020-09-01/items/{path_segment(seller_id)}/{path_segment(sku)}",
            operation="deleteListingsItem",
            service=SERVICE,
            params=params,
            response=listings_items_v2020_09_01.ListingsItemSubmissionResponse,
            error=listings_items_v2020_09_01.ErrorList,
            rate_limit=RateLimit(5, 10),
            options=request_options,
        )


class AsyncListingsItemsV20200901Client:
    """Asynchronous ``ListingsItemsV20200901`` resource."""

    __slots__ = ("_client",)

    def __init__(self, client: AsyncHttpClient) -> None:
        self._client = client

    async def put_listings_item(
        self,
        *,
        seller_id: str,
        sku: str,
        marketplace_ids: list[str],
        body: listings_items_v2020_09_01.ListingsItemPutRequest | Mapping[str, Any],
        issue_locale: str | None = None,
        request_options: RequestOptions | None = None,
    ) -> listings_items_v2020_09_01.ListingsItemSubmissionResponse:
        """Creates a new or fully-updates an existing listings item for a selling partner.

        **Note:** The parameters associated with this operation may contain special characters that must be encoded to successfully call the API. To avoid errors with SKUs when encoding URLs, refer to [URL Encoding](https://developer-docs.amazon.com/sp-api/docs/url-encoding).

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 5 | 10 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        PUT /listings/2020-09-01/items/{sellerId}/{sku}
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ","), "issueLocale": issue_locale}
        return await self._client.request(
            "PUT",
            f"/listings/2020-09-01/items/{path_segment(seller_id)}/{path_segment(sku)}",
            operation="putListingsItem",
            service=SERVICE,
            params=params,
            json=body,
            response=listings_items_v2020_09_01.ListingsItemSubmissionResponse,
            error=listings_items_v2020_09_01.ErrorList,
            rate_limit=RateLimit(5, 10),
            options=request_options,
        )

    async def patch_listings_item(
        self,
        *,
        seller_id: str,
        sku: str,
        marketplace_ids: list[str],
        body: listings_items_v2020_09_01.ListingsItemPatchRequest | Mapping[str, Any],
        issue_locale: str | None = None,
        request_options: RequestOptions | None = None,
    ) -> listings_items_v2020_09_01.ListingsItemSubmissionResponse:
        """Partially update (patch) a listings item for a selling partner. Only top-level listings item attributes can be patched. Patching nested attributes is not supported.

        **Note:** The parameters associated with this operation may contain special characters that must be encoded to successfully call the API. To avoid errors with SKUs when encoding URLs, refer to [URL Encoding](https://developer-docs.amazon.com/sp-api/docs/url-encoding).

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 5 | 10 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        PATCH /listings/2020-09-01/items/{sellerId}/{sku}
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ","), "issueLocale": issue_locale}
        return await self._client.request(
            "PATCH",
            f"/listings/2020-09-01/items/{path_segment(seller_id)}/{path_segment(sku)}",
            operation="patchListingsItem",
            service=SERVICE,
            params=params,
            json=body,
            response=listings_items_v2020_09_01.ListingsItemSubmissionResponse,
            error=listings_items_v2020_09_01.ErrorList,
            rate_limit=RateLimit(5, 10),
            options=request_options,
        )

    async def delete_item(
        self,
        *,
        seller_id: str,
        sku: str,
        marketplace_ids: list[str],
        issue_locale: str | None = None,
        request_options: RequestOptions | None = None,
    ) -> listings_items_v2020_09_01.ListingsItemSubmissionResponse:
        """Delete a listings item for a selling partner.

        **Note:** The parameters associated with this operation may contain special characters that must be encoded to successfully call the API. To avoid errors with SKUs when encoding URLs, refer to [URL Encoding](https://developer-docs.amazon.com/sp-api/docs/url-encoding).

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 5 | 10 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        DELETE /listings/2020-09-01/items/{sellerId}/{sku}
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ","), "issueLocale": issue_locale}
        return await self._client.request(
            "DELETE",
            f"/listings/2020-09-01/items/{path_segment(seller_id)}/{path_segment(sku)}",
            operation="deleteListingsItem",
            service=SERVICE,
            params=params,
            response=listings_items_v2020_09_01.ListingsItemSubmissionResponse,
            error=listings_items_v2020_09_01.ErrorList,
            rate_limit=RateLimit(5, 10),
            options=request_options,
        )


__all__ = ["AsyncListingsItemsV20200901Client", "ListingsItemsV20200901Client"]
