# Auto-generated by oagen. Do not edit.

"""``MerchantFulfillmentV0`` resource of Selling Partner API.

Auto-generated by oagen from the OpenAPI spec; do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from ..http_client import AsyncHttpClient, HttpClient, RateLimit, RequestOptions, path_segment
from ..models import merchant_fulfillment_v0

SERVICE = "merchant_fulfillment_v0"


class MerchantFulfillmentV0Client:
    """Synchronous ``MerchantFulfillmentV0`` resource."""

    __slots__ = ("_client",)

    def __init__(self, client: HttpClient) -> None:
        self._client = client

    def create_eligible_shipping_service(
        self,
        *,
        body: merchant_fulfillment_v0.GetEligibleShipmentServicesRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> merchant_fulfillment_v0.GetEligibleShipmentServicesResponse:
        """Returns a list of shipping service offers that satisfy the specified shipment request details.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 6 | 12 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that are applied to the requested operation when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the SP-API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /mfn/v0/eligibleShippingServices
        """
        return self._client.request(
            "POST",
            "/mfn/v0/eligibleShippingServices",
            operation="getEligibleShipmentServices",
            service=SERVICE,
            json=body,
            response=merchant_fulfillment_v0.GetEligibleShipmentServicesResponse,
            error=merchant_fulfillment_v0.GetEligibleShipmentServicesResponse,
            rate_limit=RateLimit(6, 12),
            options=request_options,
        )

    def get_shipment(
        self,
        *,
        shipment_id: str,
        request_options: RequestOptions | None = None,
    ) -> merchant_fulfillment_v0.GetShipmentResponse:
        """Returns the shipment information for an existing shipment.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 1 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that are applied to the requested operation when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the SP-API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        GET /mfn/v0/shipments/{shipmentId}
        """
        return self._client.request(
            "GET",
            f"/mfn/v0/shipments/{path_segment(shipment_id)}",
            operation="getShipment",
            service=SERVICE,
            response=merchant_fulfillment_v0.GetShipmentResponse,
            error=merchant_fulfillment_v0.GetShipmentResponse,
            rate_limit=RateLimit(1, 1),
            options=request_options,
        )

    def delete_shipment(
        self,
        *,
        shipment_id: str,
        request_options: RequestOptions | None = None,
    ) -> merchant_fulfillment_v0.CancelShipmentResponse:
        """Cancel the shipment indicated by the specified shipment identifier.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 1 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that are applied to the requested operation when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the SP-API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        DELETE /mfn/v0/shipments/{shipmentId}
        """
        return self._client.request(
            "DELETE",
            f"/mfn/v0/shipments/{path_segment(shipment_id)}",
            operation="cancelShipment",
            service=SERVICE,
            response=merchant_fulfillment_v0.CancelShipmentResponse,
            error=merchant_fulfillment_v0.CancelShipmentResponse,
            rate_limit=RateLimit(1, 1),
            options=request_options,
        )

    def create_shipment(
        self,
        *,
        body: merchant_fulfillment_v0.CreateShipmentRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> merchant_fulfillment_v0.CreateShipmentResponse:
        """Create a shipment with the information provided.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 2 | 2 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that are applied to the requested operation when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the SP-API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /mfn/v0/shipments
        """
        return self._client.request(
            "POST",
            "/mfn/v0/shipments",
            operation="createShipment",
            service=SERVICE,
            json=body,
            response=merchant_fulfillment_v0.CreateShipmentResponse,
            error=merchant_fulfillment_v0.CreateShipmentResponse,
            rate_limit=RateLimit(2, 2),
            options=request_options,
        )

    def create_additional_seller_input(
        self,
        *,
        body: merchant_fulfillment_v0.GetAdditionalSellerInputsRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> merchant_fulfillment_v0.GetAdditionalSellerInputsResponse:
        """Gets a list of additional seller inputs required for a ship method. This is generally used for international shipping.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 1 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that are applied to the requested operation when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the SP-API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /mfn/v0/additionalSellerInputs
        """
        return self._client.request(
            "POST",
            "/mfn/v0/additionalSellerInputs",
            operation="getAdditionalSellerInputs",
            service=SERVICE,
            json=body,
            response=merchant_fulfillment_v0.GetAdditionalSellerInputsResponse,
            error=merchant_fulfillment_v0.GetAdditionalSellerInputsResponse,
            rate_limit=RateLimit(1, 1),
            options=request_options,
        )


class AsyncMerchantFulfillmentV0Client:
    """Asynchronous ``MerchantFulfillmentV0`` resource."""

    __slots__ = ("_client",)

    def __init__(self, client: AsyncHttpClient) -> None:
        self._client = client

    async def create_eligible_shipping_service(
        self,
        *,
        body: merchant_fulfillment_v0.GetEligibleShipmentServicesRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> merchant_fulfillment_v0.GetEligibleShipmentServicesResponse:
        """Returns a list of shipping service offers that satisfy the specified shipment request details.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 6 | 12 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that are applied to the requested operation when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the SP-API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /mfn/v0/eligibleShippingServices
        """
        return await self._client.request(
            "POST",
            "/mfn/v0/eligibleShippingServices",
            operation="getEligibleShipmentServices",
            service=SERVICE,
            json=body,
            response=merchant_fulfillment_v0.GetEligibleShipmentServicesResponse,
            error=merchant_fulfillment_v0.GetEligibleShipmentServicesResponse,
            rate_limit=RateLimit(6, 12),
            options=request_options,
        )

    async def get_shipment(
        self,
        *,
        shipment_id: str,
        request_options: RequestOptions | None = None,
    ) -> merchant_fulfillment_v0.GetShipmentResponse:
        """Returns the shipment information for an existing shipment.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 1 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that are applied to the requested operation when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the SP-API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        GET /mfn/v0/shipments/{shipmentId}
        """
        return await self._client.request(
            "GET",
            f"/mfn/v0/shipments/{path_segment(shipment_id)}",
            operation="getShipment",
            service=SERVICE,
            response=merchant_fulfillment_v0.GetShipmentResponse,
            error=merchant_fulfillment_v0.GetShipmentResponse,
            rate_limit=RateLimit(1, 1),
            options=request_options,
        )

    async def delete_shipment(
        self,
        *,
        shipment_id: str,
        request_options: RequestOptions | None = None,
    ) -> merchant_fulfillment_v0.CancelShipmentResponse:
        """Cancel the shipment indicated by the specified shipment identifier.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 1 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that are applied to the requested operation when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the SP-API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        DELETE /mfn/v0/shipments/{shipmentId}
        """
        return await self._client.request(
            "DELETE",
            f"/mfn/v0/shipments/{path_segment(shipment_id)}",
            operation="cancelShipment",
            service=SERVICE,
            response=merchant_fulfillment_v0.CancelShipmentResponse,
            error=merchant_fulfillment_v0.CancelShipmentResponse,
            rate_limit=RateLimit(1, 1),
            options=request_options,
        )

    async def create_shipment(
        self,
        *,
        body: merchant_fulfillment_v0.CreateShipmentRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> merchant_fulfillment_v0.CreateShipmentResponse:
        """Create a shipment with the information provided.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 2 | 2 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that are applied to the requested operation when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the SP-API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /mfn/v0/shipments
        """
        return await self._client.request(
            "POST",
            "/mfn/v0/shipments",
            operation="createShipment",
            service=SERVICE,
            json=body,
            response=merchant_fulfillment_v0.CreateShipmentResponse,
            error=merchant_fulfillment_v0.CreateShipmentResponse,
            rate_limit=RateLimit(2, 2),
            options=request_options,
        )

    async def create_additional_seller_input(
        self,
        *,
        body: merchant_fulfillment_v0.GetAdditionalSellerInputsRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> merchant_fulfillment_v0.GetAdditionalSellerInputsResponse:
        """Gets a list of additional seller inputs required for a ship method. This is generally used for international shipping.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 1 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that are applied to the requested operation when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the SP-API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /mfn/v0/additionalSellerInputs
        """
        return await self._client.request(
            "POST",
            "/mfn/v0/additionalSellerInputs",
            operation="getAdditionalSellerInputs",
            service=SERVICE,
            json=body,
            response=merchant_fulfillment_v0.GetAdditionalSellerInputsResponse,
            error=merchant_fulfillment_v0.GetAdditionalSellerInputsResponse,
            rate_limit=RateLimit(1, 1),
            options=request_options,
        )


__all__ = ["AsyncMerchantFulfillmentV0Client", "MerchantFulfillmentV0Client"]
