# Auto-generated by oagen. Do not edit.

"""``MessagingV1`` resource of Selling Partner API.

Auto-generated by oagen from the OpenAPI spec; do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from ..http_client import AsyncHttpClient, HttpClient, RateLimit, RequestOptions, joined, path_segment
from ..models import messaging_v1

SERVICE = "messaging_v1"


class MessagingV1Client:
    """Synchronous ``MessagingV1`` resource."""

    __slots__ = ("_client",)

    def __init__(self, client: HttpClient) -> None:
        self._client = client

    def get_order(
        self,
        *,
        amazon_order_id: str,
        marketplace_ids: list[str],
        request_options: RequestOptions | None = None,
    ) -> messaging_v1.GetMessagingActionsForOrderResponse:
        """Returns a list of message types that are available for an order that you specify. A message type is represented by an actions object, which contains a path and query parameter(s). You can use the path and parameter(s) to call an operation that sends a message.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        GET /messaging/v1/orders/{amazonOrderId}
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ",")}
        return self._client.request(
            "GET",
            f"/messaging/v1/orders/{path_segment(amazon_order_id)}",
            operation="getMessagingActionsForOrder",
            service=SERVICE,
            params=params,
            response=messaging_v1.GetMessagingActionsForOrderResponse,
            rate_limit=RateLimit(1, 5),
            options=request_options,
        )

    def create_confirm_customization_detail(
        self,
        *,
        amazon_order_id: str,
        marketplace_ids: list[str],
        body: messaging_v1.CreateConfirmCustomizationDetailsRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> messaging_v1.CreateConfirmCustomizationDetailsResponse:
        """Sends a message asking a buyer to provide or verify customization details such as name spelling, images, initials, etc.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /messaging/v1/orders/{amazonOrderId}/messages/confirmCustomizationDetails
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ",")}
        return self._client.request(
            "POST",
            f"/messaging/v1/orders/{path_segment(amazon_order_id)}/messages/confirmCustomizationDetails",
            operation="confirmCustomizationDetails",
            service=SERVICE,
            params=params,
            json=body,
            response=messaging_v1.CreateConfirmCustomizationDetailsResponse,
            rate_limit=RateLimit(1, 5),
            options=request_options,
        )

    def create_confirm_delivery_detail(
        self,
        *,
        amazon_order_id: str,
        marketplace_ids: list[str],
        body: messaging_v1.CreateConfirmDeliveryDetailsRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> messaging_v1.CreateConfirmDeliveryDetailsResponse:
        """Sends a message to a buyer to arrange a delivery or to confirm contact information for making a delivery.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /messaging/v1/orders/{amazonOrderId}/messages/confirmDeliveryDetails
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ",")}
        return self._client.request(
            "POST",
            f"/messaging/v1/orders/{path_segment(amazon_order_id)}/messages/confirmDeliveryDetails",
            operation="createConfirmDeliveryDetails",
            service=SERVICE,
            params=params,
            json=body,
            response=messaging_v1.CreateConfirmDeliveryDetailsResponse,
            rate_limit=RateLimit(1, 5),
            options=request_options,
        )

    def create_legal_disclosure(
        self,
        *,
        amazon_order_id: str,
        marketplace_ids: list[str],
        body: messaging_v1.CreateLegalDisclosureRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> messaging_v1.CreateLegalDisclosureResponse:
        """Sends a critical message that contains documents that a seller is legally obligated to provide to the buyer. This message should only be used to deliver documents that are required by law.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /messaging/v1/orders/{amazonOrderId}/messages/legalDisclosure
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ",")}
        return self._client.request(
            "POST",
            f"/messaging/v1/orders/{path_segment(amazon_order_id)}/messages/legalDisclosure",
            operation="createLegalDisclosure",
            service=SERVICE,
            params=params,
            json=body,
            response=messaging_v1.CreateLegalDisclosureResponse,
            rate_limit=RateLimit(1, 5),
            options=request_options,
        )

    def create_confirm_order_detail(
        self,
        *,
        amazon_order_id: str,
        marketplace_ids: list[str],
        body: messaging_v1.CreateConfirmOrderDetailsRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> messaging_v1.CreateConfirmOrderDetailsResponse:
        """Sends a message to ask a buyer an order-related question prior to shipping their order.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /messaging/v1/orders/{amazonOrderId}/messages/confirmOrderDetails
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ",")}
        return self._client.request(
            "POST",
            f"/messaging/v1/orders/{path_segment(amazon_order_id)}/messages/confirmOrderDetails",
            operation="createConfirmOrderDetails",
            service=SERVICE,
            params=params,
            json=body,
            response=messaging_v1.CreateConfirmOrderDetailsResponse,
            rate_limit=RateLimit(1, 5),
            options=request_options,
        )

    def create_confirm_service_detail(
        self,
        *,
        amazon_order_id: str,
        marketplace_ids: list[str],
        body: messaging_v1.CreateConfirmServiceDetailsRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> messaging_v1.CreateConfirmServiceDetailsResponse:
        """Sends a message to contact a Home Service customer to arrange a service call or to gather information prior to a service call.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /messaging/v1/orders/{amazonOrderId}/messages/confirmServiceDetails
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ",")}
        return self._client.request(
            "POST",
            f"/messaging/v1/orders/{path_segment(amazon_order_id)}/messages/confirmServiceDetails",
            operation="createConfirmServiceDetails",
            service=SERVICE,
            params=params,
            json=body,
            response=messaging_v1.CreateConfirmServiceDetailsResponse,
            rate_limit=RateLimit(1, 5),
            options=request_options,
        )

    def create_warranty(
        self,
        *,
        amazon_order_id: str,
        marketplace_ids: list[str],
        body: messaging_v1.CreateWarrantyRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> messaging_v1.CreateWarrantyResponse:
        """Sends a message to a buyer to provide details about warranty information on a purchase in their order.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /messaging/v1/orders/{amazonOrderId}/messages/warranty
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ",")}
        return self._client.request(
            "POST",
            f"/messaging/v1/orders/{path_segment(amazon_order_id)}/messages/warranty",
            operation="CreateWarranty",
            service=SERVICE,
            params=params,
            json=body,
            response=messaging_v1.CreateWarrantyResponse,
            rate_limit=RateLimit(1, 5),
            options=request_options,
        )

    def list_order_attributes(
        self,
        *,
        amazon_order_id: str,
        marketplace_ids: list[str],
        request_options: RequestOptions | None = None,
    ) -> messaging_v1.GetAttributesResponse:
        """Returns a response containing attributes related to an order. This includes buyer preferences.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        GET /messaging/v1/orders/{amazonOrderId}/attributes
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ",")}
        return self._client.request(
            "GET",
            f"/messaging/v1/orders/{path_segment(amazon_order_id)}/attributes",
            operation="GetAttributes",
            service=SERVICE,
            params=params,
            response=messaging_v1.GetAttributesResponse,
            rate_limit=RateLimit(1, 5),
            options=request_options,
        )

    def create_digital_access_key(
        self,
        *,
        amazon_order_id: str,
        marketplace_ids: list[str],
        body: messaging_v1.CreateDigitalAccessKeyRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> messaging_v1.CreateDigitalAccessKeyResponse:
        """Sends a buyer a message to share a digital access key that is required to utilize digital content in their order.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /messaging/v1/orders/{amazonOrderId}/messages/digitalAccessKey
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ",")}
        return self._client.request(
            "POST",
            f"/messaging/v1/orders/{path_segment(amazon_order_id)}/messages/digitalAccessKey",
            operation="createDigitalAccessKey",
            service=SERVICE,
            params=params,
            json=body,
            response=messaging_v1.CreateDigitalAccessKeyResponse,
            rate_limit=RateLimit(1, 5),
            options=request_options,
        )

    def create_unexpected_problem(
        self,
        *,
        amazon_order_id: str,
        marketplace_ids: list[str],
        body: messaging_v1.CreateUnexpectedProblemRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> messaging_v1.CreateUnexpectedProblemResponse:
        """Sends a critical message to a buyer that an unexpected problem was encountered affecting the completion of the order.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /messaging/v1/orders/{amazonOrderId}/messages/unexpectedProblem
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ",")}
        return self._client.request(
            "POST",
            f"/messaging/v1/orders/{path_segment(amazon_order_id)}/messages/unexpectedProblem",
            operation="createUnexpectedProblem",
            service=SERVICE,
            params=params,
            json=body,
            response=messaging_v1.CreateUnexpectedProblemResponse,
            rate_limit=RateLimit(1, 5),
            options=request_options,
        )

    def create_invoice(
        self,
        *,
        amazon_order_id: str,
        marketplace_ids: list[str],
        body: messaging_v1.InvoiceRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> messaging_v1.InvoiceResponse:
        """Sends a message providing the buyer an invoice

        POST /messaging/v1/orders/{amazonOrderId}/messages/invoice
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ",")}
        return self._client.request(
            "POST",
            f"/messaging/v1/orders/{path_segment(amazon_order_id)}/messages/invoice",
            operation="sendInvoice",
            service=SERVICE,
            params=params,
            json=body,
            response=messaging_v1.InvoiceResponse,
            options=request_options,
        )


class AsyncMessagingV1Client:
    """Asynchronous ``MessagingV1`` resource."""

    __slots__ = ("_client",)

    def __init__(self, client: AsyncHttpClient) -> None:
        self._client = client

    async def get_order(
        self,
        *,
        amazon_order_id: str,
        marketplace_ids: list[str],
        request_options: RequestOptions | None = None,
    ) -> messaging_v1.GetMessagingActionsForOrderResponse:
        """Returns a list of message types that are available for an order that you specify. A message type is represented by an actions object, which contains a path and query parameter(s). You can use the path and parameter(s) to call an operation that sends a message.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        GET /messaging/v1/orders/{amazonOrderId}
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ",")}
        return await self._client.request(
            "GET",
            f"/messaging/v1/orders/{path_segment(amazon_order_id)}",
            operation="getMessagingActionsForOrder",
            service=SERVICE,
            params=params,
            response=messaging_v1.GetMessagingActionsForOrderResponse,
            rate_limit=RateLimit(1, 5),
            options=request_options,
        )

    async def create_confirm_customization_detail(
        self,
        *,
        amazon_order_id: str,
        marketplace_ids: list[str],
        body: messaging_v1.CreateConfirmCustomizationDetailsRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> messaging_v1.CreateConfirmCustomizationDetailsResponse:
        """Sends a message asking a buyer to provide or verify customization details such as name spelling, images, initials, etc.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /messaging/v1/orders/{amazonOrderId}/messages/confirmCustomizationDetails
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ",")}
        return await self._client.request(
            "POST",
            f"/messaging/v1/orders/{path_segment(amazon_order_id)}/messages/confirmCustomizationDetails",
            operation="confirmCustomizationDetails",
            service=SERVICE,
            params=params,
            json=body,
            response=messaging_v1.CreateConfirmCustomizationDetailsResponse,
            rate_limit=RateLimit(1, 5),
            options=request_options,
        )

    async def create_confirm_delivery_detail(
        self,
        *,
        amazon_order_id: str,
        marketplace_ids: list[str],
        body: messaging_v1.CreateConfirmDeliveryDetailsRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> messaging_v1.CreateConfirmDeliveryDetailsResponse:
        """Sends a message to a buyer to arrange a delivery or to confirm contact information for making a delivery.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /messaging/v1/orders/{amazonOrderId}/messages/confirmDeliveryDetails
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ",")}
        return await self._client.request(
            "POST",
            f"/messaging/v1/orders/{path_segment(amazon_order_id)}/messages/confirmDeliveryDetails",
            operation="createConfirmDeliveryDetails",
            service=SERVICE,
            params=params,
            json=body,
            response=messaging_v1.CreateConfirmDeliveryDetailsResponse,
            rate_limit=RateLimit(1, 5),
            options=request_options,
        )

    async def create_legal_disclosure(
        self,
        *,
        amazon_order_id: str,
        marketplace_ids: list[str],
        body: messaging_v1.CreateLegalDisclosureRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> messaging_v1.CreateLegalDisclosureResponse:
        """Sends a critical message that contains documents that a seller is legally obligated to provide to the buyer. This message should only be used to deliver documents that are required by law.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /messaging/v1/orders/{amazonOrderId}/messages/legalDisclosure
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ",")}
        return await self._client.request(
            "POST",
            f"/messaging/v1/orders/{path_segment(amazon_order_id)}/messages/legalDisclosure",
            operation="createLegalDisclosure",
            service=SERVICE,
            params=params,
            json=body,
            response=messaging_v1.CreateLegalDisclosureResponse,
            rate_limit=RateLimit(1, 5),
            options=request_options,
        )

    async def create_confirm_order_detail(
        self,
        *,
        amazon_order_id: str,
        marketplace_ids: list[str],
        body: messaging_v1.CreateConfirmOrderDetailsRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> messaging_v1.CreateConfirmOrderDetailsResponse:
        """Sends a message to ask a buyer an order-related question prior to shipping their order.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /messaging/v1/orders/{amazonOrderId}/messages/confirmOrderDetails
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ",")}
        return await self._client.request(
            "POST",
            f"/messaging/v1/orders/{path_segment(amazon_order_id)}/messages/confirmOrderDetails",
            operation="createConfirmOrderDetails",
            service=SERVICE,
            params=params,
            json=body,
            response=messaging_v1.CreateConfirmOrderDetailsResponse,
            rate_limit=RateLimit(1, 5),
            options=request_options,
        )

    async def create_confirm_service_detail(
        self,
        *,
        amazon_order_id: str,
        marketplace_ids: list[str],
        body: messaging_v1.CreateConfirmServiceDetailsRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> messaging_v1.CreateConfirmServiceDetailsResponse:
        """Sends a message to contact a Home Service customer to arrange a service call or to gather information prior to a service call.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /messaging/v1/orders/{amazonOrderId}/messages/confirmServiceDetails
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ",")}
        return await self._client.request(
            "POST",
            f"/messaging/v1/orders/{path_segment(amazon_order_id)}/messages/confirmServiceDetails",
            operation="createConfirmServiceDetails",
            service=SERVICE,
            params=params,
            json=body,
            response=messaging_v1.CreateConfirmServiceDetailsResponse,
            rate_limit=RateLimit(1, 5),
            options=request_options,
        )

    async def create_warranty(
        self,
        *,
        amazon_order_id: str,
        marketplace_ids: list[str],
        body: messaging_v1.CreateWarrantyRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> messaging_v1.CreateWarrantyResponse:
        """Sends a message to a buyer to provide details about warranty information on a purchase in their order.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /messaging/v1/orders/{amazonOrderId}/messages/warranty
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ",")}
        return await self._client.request(
            "POST",
            f"/messaging/v1/orders/{path_segment(amazon_order_id)}/messages/warranty",
            operation="CreateWarranty",
            service=SERVICE,
            params=params,
            json=body,
            response=messaging_v1.CreateWarrantyResponse,
            rate_limit=RateLimit(1, 5),
            options=request_options,
        )

    async def list_order_attributes(
        self,
        *,
        amazon_order_id: str,
        marketplace_ids: list[str],
        request_options: RequestOptions | None = None,
    ) -> messaging_v1.GetAttributesResponse:
        """Returns a response containing attributes related to an order. This includes buyer preferences.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        GET /messaging/v1/orders/{amazonOrderId}/attributes
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ",")}
        return await self._client.request(
            "GET",
            f"/messaging/v1/orders/{path_segment(amazon_order_id)}/attributes",
            operation="GetAttributes",
            service=SERVICE,
            params=params,
            response=messaging_v1.GetAttributesResponse,
            rate_limit=RateLimit(1, 5),
            options=request_options,
        )

    async def create_digital_access_key(
        self,
        *,
        amazon_order_id: str,
        marketplace_ids: list[str],
        body: messaging_v1.CreateDigitalAccessKeyRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> messaging_v1.CreateDigitalAccessKeyResponse:
        """Sends a buyer a message to share a digital access key that is required to utilize digital content in their order.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /messaging/v1/orders/{amazonOrderId}/messages/digitalAccessKey
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ",")}
        return await self._client.request(
            "POST",
            f"/messaging/v1/orders/{path_segment(amazon_order_id)}/messages/digitalAccessKey",
            operation="createDigitalAccessKey",
            service=SERVICE,
            params=params,
            json=body,
            response=messaging_v1.CreateDigitalAccessKeyResponse,
            rate_limit=RateLimit(1, 5),
            options=request_options,
        )

    async def create_unexpected_problem(
        self,
        *,
        amazon_order_id: str,
        marketplace_ids: list[str],
        body: messaging_v1.CreateUnexpectedProblemRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> messaging_v1.CreateUnexpectedProblemResponse:
        """Sends a critical message to a buyer that an unexpected problem was encountered affecting the completion of the order.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 5 |

        The `x-amzn-RateLimit-Limit` response header contains the usage plan rate limits for the operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput might have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /messaging/v1/orders/{amazonOrderId}/messages/unexpectedProblem
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ",")}
        return await self._client.request(
            "POST",
            f"/messaging/v1/orders/{path_segment(amazon_order_id)}/messages/unexpectedProblem",
            operation="createUnexpectedProblem",
            service=SERVICE,
            params=params,
            json=body,
            response=messaging_v1.CreateUnexpectedProblemResponse,
            rate_limit=RateLimit(1, 5),
            options=request_options,
        )

    async def create_invoice(
        self,
        *,
        amazon_order_id: str,
        marketplace_ids: list[str],
        body: messaging_v1.InvoiceRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> messaging_v1.InvoiceResponse:
        """Sends a message providing the buyer an invoice

        POST /messaging/v1/orders/{amazonOrderId}/messages/invoice
        """
        params: dict[str, Any] = {"marketplaceIds": joined(marketplace_ids, ",")}
        return await self._client.request(
            "POST",
            f"/messaging/v1/orders/{path_segment(amazon_order_id)}/messages/invoice",
            operation="sendInvoice",
            service=SERVICE,
            params=params,
            json=body,
            response=messaging_v1.InvoiceResponse,
            options=request_options,
        )


__all__ = ["AsyncMessagingV1Client", "MessagingV1Client"]
