# Auto-generated by oagen. Do not edit.

"""``ReplenishmentV20221107`` resource of Selling Partner API.

Auto-generated by oagen from the OpenAPI spec; do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from ..http_client import AsyncHttpClient, HttpClient, RateLimit, RequestOptions
from ..models import replenishment_v2022_11_07

SERVICE = "replenishment_v2022_11_07"


class ReplenishmentV20221107Client:
    """Synchronous ``ReplenishmentV20221107`` resource."""

    __slots__ = ("_client",)

    def __init__(self, client: HttpClient) -> None:
        self._client = client

    def get_selling_partner_metrics(
        self,
        *,
        body: replenishment_v2022_11_07.GetSellingPartnerMetricsRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> replenishment_v2022_11_07.GetSellingPartnerMetricsResponse:
        """Returns aggregated replenishment program metrics for a selling partner.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 1 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /replenishment/2022-11-07/sellingPartners/metrics/search
        """
        return self._client.request(
            "POST",
            "/replenishment/2022-11-07/sellingPartners/metrics/search",
            operation="getSellingPartnerMetrics",
            service=SERVICE,
            json=body,
            response=replenishment_v2022_11_07.GetSellingPartnerMetricsResponse,
            error=replenishment_v2022_11_07.ErrorList,
            rate_limit=RateLimit(1, 1),
            options=request_options,
        )

    def list_offer_metrics(
        self,
        *,
        body: replenishment_v2022_11_07.ListOfferMetricsRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> replenishment_v2022_11_07.ListOfferMetricsResponse:
        """Returns aggregated replenishment program metrics for a selling partner's offers.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 1 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /replenishment/2022-11-07/offers/metrics/search
        """
        return self._client.request(
            "POST",
            "/replenishment/2022-11-07/offers/metrics/search",
            operation="listOfferMetrics",
            service=SERVICE,
            json=body,
            response=replenishment_v2022_11_07.ListOfferMetricsResponse,
            error=replenishment_v2022_11_07.ErrorList,
            rate_limit=RateLimit(1, 1),
            options=request_options,
        )

    def list_offers(
        self,
        *,
        body: replenishment_v2022_11_07.ListOffersRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> replenishment_v2022_11_07.ListOffersResponse:
        """Returns the details of a selling partner's replenishment program offers.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 1 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /replenishment/2022-11-07/offers/search
        """
        return self._client.request(
            "POST",
            "/replenishment/2022-11-07/offers/search",
            operation="listOffers",
            service=SERVICE,
            json=body,
            response=replenishment_v2022_11_07.ListOffersResponse,
            error=replenishment_v2022_11_07.ErrorList,
            rate_limit=RateLimit(1, 1),
            options=request_options,
        )


class AsyncReplenishmentV20221107Client:
    """Asynchronous ``ReplenishmentV20221107`` resource."""

    __slots__ = ("_client",)

    def __init__(self, client: AsyncHttpClient) -> None:
        self._client = client

    async def get_selling_partner_metrics(
        self,
        *,
        body: replenishment_v2022_11_07.GetSellingPartnerMetricsRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> replenishment_v2022_11_07.GetSellingPartnerMetricsResponse:
        """Returns aggregated replenishment program metrics for a selling partner.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 1 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /replenishment/2022-11-07/sellingPartners/metrics/search
        """
        return await self._client.request(
            "POST",
            "/replenishment/2022-11-07/sellingPartners/metrics/search",
            operation="getSellingPartnerMetrics",
            service=SERVICE,
            json=body,
            response=replenishment_v2022_11_07.GetSellingPartnerMetricsResponse,
            error=replenishment_v2022_11_07.ErrorList,
            rate_limit=RateLimit(1, 1),
            options=request_options,
        )

    async def list_offer_metrics(
        self,
        *,
        body: replenishment_v2022_11_07.ListOfferMetricsRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> replenishment_v2022_11_07.ListOfferMetricsResponse:
        """Returns aggregated replenishment program metrics for a selling partner's offers.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 1 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /replenishment/2022-11-07/offers/metrics/search
        """
        return await self._client.request(
            "POST",
            "/replenishment/2022-11-07/offers/metrics/search",
            operation="listOfferMetrics",
            service=SERVICE,
            json=body,
            response=replenishment_v2022_11_07.ListOfferMetricsResponse,
            error=replenishment_v2022_11_07.ErrorList,
            rate_limit=RateLimit(1, 1),
            options=request_options,
        )

    async def list_offers(
        self,
        *,
        body: replenishment_v2022_11_07.ListOffersRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> replenishment_v2022_11_07.ListOffersResponse:
        """Returns the details of a selling partner's replenishment program offers.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 1 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).

        POST /replenishment/2022-11-07/offers/search
        """
        return await self._client.request(
            "POST",
            "/replenishment/2022-11-07/offers/search",
            operation="listOffers",
            service=SERVICE,
            json=body,
            response=replenishment_v2022_11_07.ListOffersResponse,
            error=replenishment_v2022_11_07.ErrorList,
            rate_limit=RateLimit(1, 1),
            options=request_options,
        )


__all__ = ["AsyncReplenishmentV20221107Client", "ReplenishmentV20221107Client"]
