# Auto-generated by oagen. Do not edit.

"""``ShippingV1`` resource of Selling Partner API.

Auto-generated by oagen from the OpenAPI spec; do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from .._http import AsyncHttpClient, HttpClient, RateLimit, RequestOptions, path_segment
from ..models import shipping_v1

SERVICE = "shipping_v1"


class ShippingV1Resource:
    """Synchronous ``ShippingV1`` resource."""

    __slots__ = ("_http",)

    def __init__(self, http: HttpClient) -> None:
        self._http = http

    def create_shipment(
        self,
        body: shipping_v1.CreateShipmentRequest | Mapping[str, Any],
        *,
        request_options: RequestOptions | None = None,
    ) -> shipping_v1.CreateShipmentResponse:
        """Create a new shipment.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 5 | 15 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).

        POST /shipping/v1/shipments
        """
        return self._http.request(
            "POST",
            "/shipping/v1/shipments",
            operation="createShipment",
            service=SERVICE,
            json=body,
            response=shipping_v1.CreateShipmentResponse,
            error=shipping_v1.CreateShipmentResponse,
            rate_limit=RateLimit(5, 15),
            options=request_options,
        )

    def get_shipment(
        self,
        shipment_id: str,
        *,
        request_options: RequestOptions | None = None,
    ) -> shipping_v1.GetShipmentResponse:
        """Return the entire shipment object for the shipmentId.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 5 | 15 |

        For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.

        GET /shipping/v1/shipments/{shipmentId}
        """
        return self._http.request(
            "GET",
            f"/shipping/v1/shipments/{path_segment(shipment_id)}",
            operation="getShipment",
            service=SERVICE,
            response=shipping_v1.GetShipmentResponse,
            error=shipping_v1.GetShipmentResponse,
            rate_limit=RateLimit(5, 15),
            options=request_options,
        )

    def create_shipment_cancel(
        self,
        shipment_id: str,
        *,
        request_options: RequestOptions | None = None,
    ) -> shipping_v1.CancelShipmentResponse:
        """Cancel a shipment by the given shipmentId.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 5 | 15 |

        For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.

        POST /shipping/v1/shipments/{shipmentId}/cancel
        """
        return self._http.request(
            "POST",
            f"/shipping/v1/shipments/{path_segment(shipment_id)}/cancel",
            operation="cancelShipment",
            service=SERVICE,
            response=shipping_v1.CancelShipmentResponse,
            error=shipping_v1.CancelShipmentResponse,
            rate_limit=RateLimit(5, 15),
            options=request_options,
        )

    def create_shipment_purchase_label(
        self,
        shipment_id: str,
        body: shipping_v1.PurchaseLabelsRequest | Mapping[str, Any],
        *,
        request_options: RequestOptions | None = None,
    ) -> shipping_v1.PurchaseLabelsResponse:
        """Purchase shipping labels based on a given rate.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 5 | 15 |

        For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.

        POST /shipping/v1/shipments/{shipmentId}/purchaseLabels
        """
        return self._http.request(
            "POST",
            f"/shipping/v1/shipments/{path_segment(shipment_id)}/purchaseLabels",
            operation="purchaseLabels",
            service=SERVICE,
            json=body,
            response=shipping_v1.PurchaseLabelsResponse,
            error=shipping_v1.PurchaseLabelsResponse,
            rate_limit=RateLimit(5, 15),
            options=request_options,
        )

    def create_container_label(
        self,
        shipment_id: str,
        tracking_id: str,
        body: shipping_v1.RetrieveShippingLabelRequest | Mapping[str, Any],
        *,
        request_options: RequestOptions | None = None,
    ) -> shipping_v1.RetrieveShippingLabelResponse:
        """Retrieve shipping label based on the shipment id and tracking id.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 5 | 15 |

        For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.

        POST /shipping/v1/shipments/{shipmentId}/containers/{trackingId}/label
        """
        return self._http.request(
            "POST",
            f"/shipping/v1/shipments/{path_segment(shipment_id)}/containers/{path_segment(tracking_id)}/label",
            operation="retrieveShippingLabel",
            service=SERVICE,
            json=body,
            response=shipping_v1.RetrieveShippingLabelResponse,
            error=shipping_v1.RetrieveShippingLabelResponse,
            rate_limit=RateLimit(5, 15),
            options=request_options,
        )

    def create_purchase_shipment(
        self,
        body: shipping_v1.PurchaseShipmentRequest | Mapping[str, Any],
        *,
        request_options: RequestOptions | None = None,
    ) -> shipping_v1.PurchaseShipmentResponse:
        """Purchase shipping labels.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 5 | 15 |

        For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.

        POST /shipping/v1/purchaseShipment
        """
        return self._http.request(
            "POST",
            "/shipping/v1/purchaseShipment",
            operation="purchaseShipment",
            service=SERVICE,
            json=body,
            response=shipping_v1.PurchaseShipmentResponse,
            error=shipping_v1.PurchaseShipmentResponse,
            rate_limit=RateLimit(5, 15),
            options=request_options,
        )

    def create_rate(
        self,
        body: shipping_v1.GetRatesRequest | Mapping[str, Any],
        *,
        request_options: RequestOptions | None = None,
    ) -> shipping_v1.GetRatesResponse:
        """Get service rates.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 5 | 15 |

        For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.

        POST /shipping/v1/rates
        """
        return self._http.request(
            "POST",
            "/shipping/v1/rates",
            operation="getRates",
            service=SERVICE,
            json=body,
            response=shipping_v1.GetRatesResponse,
            error=shipping_v1.GetRatesResponse,
            rate_limit=RateLimit(5, 15),
            options=request_options,
        )

    def list_account(
        self,
        *,
        request_options: RequestOptions | None = None,
    ) -> shipping_v1.GetAccountResponse:
        """Verify if the current account is valid.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 5 | 15 |

        For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.

        GET /shipping/v1/account
        """
        return self._http.request(
            "GET",
            "/shipping/v1/account",
            operation="getAccount",
            service=SERVICE,
            response=shipping_v1.GetAccountResponse,
            error=shipping_v1.GetAccountResponse,
            rate_limit=RateLimit(5, 15),
            options=request_options,
        )

    def get_tracking(
        self,
        tracking_id: str,
        *,
        request_options: RequestOptions | None = None,
    ) -> shipping_v1.GetTrackingInformationResponse:
        """Return the tracking information of a shipment.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 1 |

        For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.

        GET /shipping/v1/tracking/{trackingId}
        """
        return self._http.request(
            "GET",
            f"/shipping/v1/tracking/{path_segment(tracking_id)}",
            operation="getTrackingInformation",
            service=SERVICE,
            response=shipping_v1.GetTrackingInformationResponse,
            error=shipping_v1.GetTrackingInformationResponse,
            rate_limit=RateLimit(1, 1),
            options=request_options,
        )


class AsyncShippingV1Resource:
    """Asynchronous ``ShippingV1`` resource."""

    __slots__ = ("_http",)

    def __init__(self, http: AsyncHttpClient) -> None:
        self._http = http

    async def create_shipment(
        self,
        body: shipping_v1.CreateShipmentRequest | Mapping[str, Any],
        *,
        request_options: RequestOptions | None = None,
    ) -> shipping_v1.CreateShipmentResponse:
        """Create a new shipment.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 5 | 15 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).

        POST /shipping/v1/shipments
        """
        return await self._http.request(
            "POST",
            "/shipping/v1/shipments",
            operation="createShipment",
            service=SERVICE,
            json=body,
            response=shipping_v1.CreateShipmentResponse,
            error=shipping_v1.CreateShipmentResponse,
            rate_limit=RateLimit(5, 15),
            options=request_options,
        )

    async def get_shipment(
        self,
        shipment_id: str,
        *,
        request_options: RequestOptions | None = None,
    ) -> shipping_v1.GetShipmentResponse:
        """Return the entire shipment object for the shipmentId.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 5 | 15 |

        For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.

        GET /shipping/v1/shipments/{shipmentId}
        """
        return await self._http.request(
            "GET",
            f"/shipping/v1/shipments/{path_segment(shipment_id)}",
            operation="getShipment",
            service=SERVICE,
            response=shipping_v1.GetShipmentResponse,
            error=shipping_v1.GetShipmentResponse,
            rate_limit=RateLimit(5, 15),
            options=request_options,
        )

    async def create_shipment_cancel(
        self,
        shipment_id: str,
        *,
        request_options: RequestOptions | None = None,
    ) -> shipping_v1.CancelShipmentResponse:
        """Cancel a shipment by the given shipmentId.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 5 | 15 |

        For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.

        POST /shipping/v1/shipments/{shipmentId}/cancel
        """
        return await self._http.request(
            "POST",
            f"/shipping/v1/shipments/{path_segment(shipment_id)}/cancel",
            operation="cancelShipment",
            service=SERVICE,
            response=shipping_v1.CancelShipmentResponse,
            error=shipping_v1.CancelShipmentResponse,
            rate_limit=RateLimit(5, 15),
            options=request_options,
        )

    async def create_shipment_purchase_label(
        self,
        shipment_id: str,
        body: shipping_v1.PurchaseLabelsRequest | Mapping[str, Any],
        *,
        request_options: RequestOptions | None = None,
    ) -> shipping_v1.PurchaseLabelsResponse:
        """Purchase shipping labels based on a given rate.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 5 | 15 |

        For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.

        POST /shipping/v1/shipments/{shipmentId}/purchaseLabels
        """
        return await self._http.request(
            "POST",
            f"/shipping/v1/shipments/{path_segment(shipment_id)}/purchaseLabels",
            operation="purchaseLabels",
            service=SERVICE,
            json=body,
            response=shipping_v1.PurchaseLabelsResponse,
            error=shipping_v1.PurchaseLabelsResponse,
            rate_limit=RateLimit(5, 15),
            options=request_options,
        )

    async def create_container_label(
        self,
        shipment_id: str,
        tracking_id: str,
        body: shipping_v1.RetrieveShippingLabelRequest | Mapping[str, Any],
        *,
        request_options: RequestOptions | None = None,
    ) -> shipping_v1.RetrieveShippingLabelResponse:
        """Retrieve shipping label based on the shipment id and tracking id.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 5 | 15 |

        For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.

        POST /shipping/v1/shipments/{shipmentId}/containers/{trackingId}/label
        """
        return await self._http.request(
            "POST",
            f"/shipping/v1/shipments/{path_segment(shipment_id)}/containers/{path_segment(tracking_id)}/label",
            operation="retrieveShippingLabel",
            service=SERVICE,
            json=body,
            response=shipping_v1.RetrieveShippingLabelResponse,
            error=shipping_v1.RetrieveShippingLabelResponse,
            rate_limit=RateLimit(5, 15),
            options=request_options,
        )

    async def create_purchase_shipment(
        self,
        body: shipping_v1.PurchaseShipmentRequest | Mapping[str, Any],
        *,
        request_options: RequestOptions | None = None,
    ) -> shipping_v1.PurchaseShipmentResponse:
        """Purchase shipping labels.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 5 | 15 |

        For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.

        POST /shipping/v1/purchaseShipment
        """
        return await self._http.request(
            "POST",
            "/shipping/v1/purchaseShipment",
            operation="purchaseShipment",
            service=SERVICE,
            json=body,
            response=shipping_v1.PurchaseShipmentResponse,
            error=shipping_v1.PurchaseShipmentResponse,
            rate_limit=RateLimit(5, 15),
            options=request_options,
        )

    async def create_rate(
        self,
        body: shipping_v1.GetRatesRequest | Mapping[str, Any],
        *,
        request_options: RequestOptions | None = None,
    ) -> shipping_v1.GetRatesResponse:
        """Get service rates.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 5 | 15 |

        For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.

        POST /shipping/v1/rates
        """
        return await self._http.request(
            "POST",
            "/shipping/v1/rates",
            operation="getRates",
            service=SERVICE,
            json=body,
            response=shipping_v1.GetRatesResponse,
            error=shipping_v1.GetRatesResponse,
            rate_limit=RateLimit(5, 15),
            options=request_options,
        )

    async def list_account(
        self,
        *,
        request_options: RequestOptions | None = None,
    ) -> shipping_v1.GetAccountResponse:
        """Verify if the current account is valid.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 5 | 15 |

        For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.

        GET /shipping/v1/account
        """
        return await self._http.request(
            "GET",
            "/shipping/v1/account",
            operation="getAccount",
            service=SERVICE,
            response=shipping_v1.GetAccountResponse,
            error=shipping_v1.GetAccountResponse,
            rate_limit=RateLimit(5, 15),
            options=request_options,
        )

    async def get_tracking(
        self,
        tracking_id: str,
        *,
        request_options: RequestOptions | None = None,
    ) -> shipping_v1.GetTrackingInformationResponse:
        """Return the tracking information of a shipment.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 1 | 1 |

        For more information, see "Usage Plans and Rate Limits" in the Selling Partner API documentation.

        GET /shipping/v1/tracking/{trackingId}
        """
        return await self._http.request(
            "GET",
            f"/shipping/v1/tracking/{path_segment(tracking_id)}",
            operation="getTrackingInformation",
            service=SERVICE,
            response=shipping_v1.GetTrackingInformationResponse,
            error=shipping_v1.GetTrackingInformationResponse,
            rate_limit=RateLimit(1, 1),
            options=request_options,
        )


__all__ = ["AsyncShippingV1Resource", "ShippingV1Resource"]
