# Auto-generated by oagen. Do not edit.

"""``VendorDirectFulfillmentSandboxDataV20211028`` resource of Selling Partner API.

Auto-generated by oagen from the OpenAPI spec; do not edit by hand.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from ..http_client import AsyncHttpClient, HttpClient, RequestOptions, path_segment
from ..models import vendor_direct_fulfillment_sandbox_data_v2021_10_28

SERVICE = "vendor_direct_fulfillment_sandbox_data_v2021_10_28"


class VendorDirectFulfillmentSandboxDataV20211028Client:
    """Synchronous ``VendorDirectFulfillmentSandboxDataV20211028`` resource."""

    __slots__ = ("_client",)

    def __init__(self, client: HttpClient) -> None:
        self._client = client

    def create_order(
        self,
        *,
        body: vendor_direct_fulfillment_sandbox_data_v2021_10_28.GenerateOrderScenarioRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> vendor_direct_fulfillment_sandbox_data_v2021_10_28.TransactionReference:
        """Submits a request to generate test order data for Vendor Direct Fulfillment API entities.

        POST /vendor/directFulfillment/sandbox/2021-10-28/orders
        """
        return self._client.request(
            "POST",
            "/vendor/directFulfillment/sandbox/2021-10-28/orders",
            operation="generateOrderScenarios",
            service=SERVICE,
            json=body,
            response=vendor_direct_fulfillment_sandbox_data_v2021_10_28.TransactionReference,
            error=vendor_direct_fulfillment_sandbox_data_v2021_10_28.ErrorList,
            options=request_options,
        )

    def get_transaction(
        self,
        *,
        transaction_id: str,
        request_options: RequestOptions | None = None,
    ) -> vendor_direct_fulfillment_sandbox_data_v2021_10_28.TransactionStatus:
        """Returns the status of the transaction indicated by the specified transactionId. If the transaction was successful, also returns the requested test order data.

        GET /vendor/directFulfillment/sandbox/2021-10-28/transactions/{transactionId}
        """
        return self._client.request(
            "GET",
            f"/vendor/directFulfillment/sandbox/2021-10-28/transactions/{path_segment(transaction_id)}",
            operation="getOrderScenarios",
            service=SERVICE,
            response=vendor_direct_fulfillment_sandbox_data_v2021_10_28.TransactionStatus,
            error=vendor_direct_fulfillment_sandbox_data_v2021_10_28.ErrorList,
            options=request_options,
        )


class AsyncVendorDirectFulfillmentSandboxDataV20211028Client:
    """Asynchronous ``VendorDirectFulfillmentSandboxDataV20211028`` resource."""

    __slots__ = ("_client",)

    def __init__(self, client: AsyncHttpClient) -> None:
        self._client = client

    async def create_order(
        self,
        *,
        body: vendor_direct_fulfillment_sandbox_data_v2021_10_28.GenerateOrderScenarioRequest | Mapping[str, Any],
        request_options: RequestOptions | None = None,
    ) -> vendor_direct_fulfillment_sandbox_data_v2021_10_28.TransactionReference:
        """Submits a request to generate test order data for Vendor Direct Fulfillment API entities.

        POST /vendor/directFulfillment/sandbox/2021-10-28/orders
        """
        return await self._client.request(
            "POST",
            "/vendor/directFulfillment/sandbox/2021-10-28/orders",
            operation="generateOrderScenarios",
            service=SERVICE,
            json=body,
            response=vendor_direct_fulfillment_sandbox_data_v2021_10_28.TransactionReference,
            error=vendor_direct_fulfillment_sandbox_data_v2021_10_28.ErrorList,
            options=request_options,
        )

    async def get_transaction(
        self,
        *,
        transaction_id: str,
        request_options: RequestOptions | None = None,
    ) -> vendor_direct_fulfillment_sandbox_data_v2021_10_28.TransactionStatus:
        """Returns the status of the transaction indicated by the specified transactionId. If the transaction was successful, also returns the requested test order data.

        GET /vendor/directFulfillment/sandbox/2021-10-28/transactions/{transactionId}
        """
        return await self._client.request(
            "GET",
            f"/vendor/directFulfillment/sandbox/2021-10-28/transactions/{path_segment(transaction_id)}",
            operation="getOrderScenarios",
            service=SERVICE,
            response=vendor_direct_fulfillment_sandbox_data_v2021_10_28.TransactionStatus,
            error=vendor_direct_fulfillment_sandbox_data_v2021_10_28.ErrorList,
            options=request_options,
        )


__all__ = ["AsyncVendorDirectFulfillmentSandboxDataV20211028Client", "VendorDirectFulfillmentSandboxDataV20211028Client"]
