# Auto-generated by oagen. Do not edit.

"""Enums of vendor_direct_fulfillment_shipping_v2021_12_28.

Auto-generated by oagen from the OpenAPI spec; do not edit by hand.
"""

from __future__ import annotations

from enum import Enum


class CarrierId(str, Enum):
    SWA = "SWA"


class ContainerContainerType(str, Enum):
    CARTON = "Carton"
    PALLET = "Pallet"


class ContainerLabelFormat(str, Enum):
    PNG = "PNG"
    ZPL = "ZPL"


class DimensionsUnitOfMeasure(str, Enum):
    IN = "IN"
    CM = "CM"


class ShipmentDetailsShipmentStatus(str, Enum):
    SHIPPED = "SHIPPED"
    FLOOR_DENIAL = "FLOOR_DENIAL"


class ShippingLabelLabelFormat(str, Enum):
    PNG = "PNG"
    ZPL = "ZPL"


class TaxRegistrationDetailsTaxRegistrationType(str, Enum):
    VAT = "VAT"
    GST = "GST"


class VendorDirectFulfillmentShippingV20211228SortOrder(str, Enum):
    ASC = "ASC"
    DESC = "DESC"


class WeightUnitOfMeasure(str, Enum):
    KG = "KG"
    LB = "LB"


__all__ = [
    "CarrierId",
    "ContainerContainerType",
    "ContainerLabelFormat",
    "DimensionsUnitOfMeasure",
    "ShipmentDetailsShipmentStatus",
    "ShippingLabelLabelFormat",
    "TaxRegistrationDetailsTaxRegistrationType",
    "VendorDirectFulfillmentShippingV20211228SortOrder",
    "WeightUnitOfMeasure",
]
